from pathlib import Path
ROOT = Path.cwd()
if not (ROOT / "package.json").exists(): raise SystemExit("ERROR: Run from repository root.")
def apply(path, patches):
    p = ROOT / path
    t = p.read_text(encoding='utf-8')
    for label, old, new in patches:
        if new in t: continue
        if old not in t: raise SystemExit(f'ERROR: Could not find current block: {label}')
        t = t.replace(old, new, 1)
    p.write_text(t, encoding='utf-8')
apply('lib/items/admin-inventory-actions.ts', [('remove container rejection', '    if (item.categorySlug === "container") {\n      throw new Error(\n        "Containers must be granted as individual instances so they can hold Items.",\n      );\n    }\n\n    const quantity = integer(formData, "quantity", 1) ?? 1;\n', '    const quantity = integer(formData, "quantity", 1) ?? 1;\n'), ('container grant branch', '    if (!item.stackable) {\n      const rows = Array.from({ length: quantity }).map(() => ({\n        character_id: characterId,\n        item_id: itemId,\n        quantity: 1,\n        container_instance_id: containerId,\n        acquisition_source: "staff",\n        assigned_by: staff.userId,\n      }));\n\n      const { error } = await supabase.from("character_items").insert(rows);\n      if (error) throw new Error(error.message);\n    } else {\n', '    if (item.categorySlug === "container") {\n      if (containerId) {\n        throw new Error(\n          "A Container cannot be granted inside another Container from this panel.",\n        );\n      }\n\n      for (let index = 0; index < quantity; index += 1) {\n        const { error } = await supabase\n          .from("character_item_instances")\n          .insert({\n            item_id: itemId,\n            owner_character_id: characterId,\n            charges_remaining:\n              item.use_behaviour === "limited_charges"\n                ? item.max_charges\n                : null,\n            vault_status: "owned",\n            acquisition_source: "staff",\n            assigned_by: staff.userId,\n          });\n\n        if (error) throw new Error(error.message);\n      }\n    } else if (!item.stackable) {\n      const rows = Array.from({ length: quantity }).map(() => ({\n        character_id: characterId,\n        item_id: itemId,\n        quantity: 1,\n        container_instance_id: containerId,\n        acquisition_source: "staff",\n        assigned_by: staff.userId,\n      }));\n\n      const { error } = await supabase.from("character_items").insert(rows);\n      if (error) throw new Error(error.message);\n    } else {\n')])
apply('app/(portal)/admin/characters/[id]/inventory/page.tsx', [('ordinary split', '  const containers = uniqueRows.filter(\n    (row) => one(one(row.item)?.category ?? null)?.slug === "container",\n  );\n\n  const nonContainerItems = items.filter(\n    (item) => one(item.category)?.slug !== "container",\n  );\n\n  const returnTo = `/admin/characters/${character.id}/inventory`;\n', '  const containers = uniqueRows.filter(\n    (row) => one(one(row.item)?.category ?? null)?.slug === "container",\n  );\n\n  const ordinaryContainers = containers.filter(\n    (row) =>\n      !row.custom_name &&\n      !row.custom_description &&\n      !row.custom_image_url &&\n      !row.quality_override &&\n      !row.transfer_policy_override &&\n      row.is_quest_item_override === null &&\n      !row.notes,\n  );\n\n  const bespokeUniqueRows = uniqueRows.filter(\n    (row) => !ordinaryContainers.some((container) => container.id === row.id),\n  );\n\n  const returnTo = `/admin/characters/${character.id}/inventory`;\n'), ('dropdown containers', '{nonContainerItems.map((item) => (', '{items.map((item) => ('), ('standard heading', 'Grant standard Item', 'Grant Item'), ('unique heading', 'Create Unique Item', 'Create Bespoke Unique Item'), ('unique button', 'Create & Grant Unique Item', 'Create & Grant Bespoke Item'), ('std condition', '{standardRows.length ? (', '{standardRows.length || ordinaryContainers.length ? ('), ('uniq condition', '{uniqueRows.length ? (', '{bespokeUniqueRows.length ? ('), ('uniq map', '{uniqueRows.map((row) => {', '{bespokeUniqueRows.map((row) => {')])
p = ROOT / 'app/(portal)/admin/characters/[id]/inventory/page.tsx'
t = p.read_text(encoding='utf-8')
marker = '              })}\n            </div>\n          ) : (\n'
insert = '\n              {ordinaryContainers.map((row) => {\n                const item = one(row.item);\n                const category = one(item?.category ?? null);\n\n                return (\n                  <article\n                    key={row.id}\n                    className="border border-[#59432c]/40 bg-[#100c09] p-4"\n                  >\n                    <p className="font-serif text-lg text-[#d8bf91]">\n                      {item?.name ?? "Unknown Container"}\n                    </p>\n                    <p className="mt-1 text-[8px] uppercase tracking-[0.13em] text-[#756958]">\n                      {category?.name ?? "Container"} · Loose\n                    </p>\n                    <p className="mt-3 text-[9px] leading-5 text-[#8f8271]">\n                      Standard Container possession.\n                    </p>\n                    <form action={sendUniqueItemToVault} className="mt-3">\n                      <input type="hidden" name="instanceId" value={row.id} />\n                      <input type="hidden" name="returnTo" value={returnTo} />\n                      <button\n                        type="submit"\n                        className="border border-red-900/55 bg-red-950/20 px-3 py-2 text-[8px] uppercase tracking-[0.14em] text-red-300"\n                      >\n                        Remove\n                      </button>\n                    </form>\n                  </article>\n                );\n              })}\n'
if insert.strip() not in t:
    if marker not in t: raise SystemExit('ERROR: Standard Items grid insertion point not found.')
    t = t.replace(marker, '              })}\n' + insert + '            </div>\n          ) : (\n', 1)
p.write_text(t, encoding='utf-8')
print('SUCCESS')
print('Admin character Inventory now grants ordinary Containers from the normal Item panel.')
print('No SQL required. Run: npm run build')
