import Link from "next/link";
import {notFound} from "next/navigation";
import {AdminActionForm} from "@/components/admin/admin-action-form";
import {requireStaff} from "@/lib/auth/require-staff";
import {createClient} from "@/lib/supabase/server";
import {getEffectiveCharacterWarping} from "@/lib/warping/get-effective-character-warping";
import {assignManualShape,removeManualShape,updateWarpingBase} from "./actions";
const f="w-full border border-[rgb(var(--sep-colour-60482e))]/50 bg-[rgb(var(--sep-colour-100c09))] px-3 py-2.5 text-xs text-[rgb(var(--sep-colour-d7c4a5))] outline-none";
const l="mb-1 block text-[7px] uppercase tracking-[0.18em] text-[rgb(var(--sep-colour-756958))]";
const b="border border-[rgb(var(--sep-colour-765937))]/55 bg-[rgb(var(--sep-colour-261b12))] px-4 py-2.5 text-[8px] uppercase tracking-[0.14em] text-[rgb(var(--sep-colour-ccb083))]";
export default async function Page({params}:{params:Promise<{id:string}>}){await requireStaff();const{id}=await params,db=await createClient();const[cq,sq,aq]=await Promise.all([db.from("characters").select("id,display_name,warping_affinity,warps_per_day").eq("id",id).single(),db.from("shapes").select("id,name,level,school,word_of_power").eq("is_active",true).order("level").order("name"),db.from("character_shapes").select("shape_id,acquisition_source,level_override,shape:shapes(id,name,level,school,word_of_power)").eq("character_id",id)]);if(cq.error||!cq.data)notFound();if(sq.error)throw Error(sq.error.message);if(aq.error)throw Error(aq.error.message);const c=cq.data,effectiveWarping=await getEffectiveCharacterWarping(id),a=aq.data??[],manual=a.filter(x=>x.acquisition_source==="staff"),order=a.filter(x=>x.acquisition_source==="order");return <main className="p-5 sm:p-7 lg:p-9"><div className="mx-auto max-w-6xl">
<div className="flex items-end justify-between border-b border-[rgb(var(--sep-colour-60482e))]/35 pb-5"><div><p className="text-[9px] uppercase tracking-[0.28em] text-[rgb(var(--sep-colour-8c704b))]">Character Administration</p><h1 className="mt-2 font-serif text-4xl text-[rgb(var(--sep-colour-ead5ac))]">Manage Warping</h1><p className="mt-1 text-[11px] text-[rgb(var(--sep-colour-8f8271))]">{c.display_name}</p></div><Link href={`/admin/characters/${id}`} className={b}>Back to Character</Link></div>
<section className="mt-7 border border-[rgb(var(--sep-colour-60482e))]/45 bg-[rgb(var(--sep-colour-15100d))] p-5">
<p className="text-[8px] uppercase tracking-[0.22em] text-[rgb(var(--sep-colour-806b50))]">Current Effective Warping</p>
<h2 className="mt-1 font-serif text-2xl text-[rgb(var(--sep-colour-dec69a))]">Effective Capability</h2>
<div className="mt-4 grid gap-3 sm:grid-cols-2">
<div className="border border-[rgb(var(--sep-colour-59432c))]/35 bg-[rgb(var(--sep-colour-100c09))] p-4">
<p className="text-[7px] uppercase tracking-[0.18em] text-[rgb(var(--sep-colour-756958))]">Current Affinity</p>
<p className="mt-1 font-serif text-3xl text-[rgb(var(--sep-colour-e1c28d))]">{effectiveWarping.affinity}</p>
<p className="mt-1 text-[8px] text-[rgb(var(--sep-colour-8f8271))]">{effectiveWarping.baseAffinity} Base · {effectiveWarping.itemAffinity >= 0 ? "+" : ""}{effectiveWarping.itemAffinity} Items · {effectiveWarping.featAffinity >= 0 ? "+" : ""}{effectiveWarping.featAffinity} Feats</p>
</div>
<div className="border border-[rgb(var(--sep-colour-59432c))]/35 bg-[rgb(var(--sep-colour-100c09))] p-4">
<p className="text-[7px] uppercase tracking-[0.18em] text-[rgb(var(--sep-colour-756958))]">Shapes per day</p>
<p className="mt-1 font-serif text-3xl text-[rgb(var(--sep-colour-e1c28d))]">{effectiveWarping.warpsPerDay}</p>
<p className="mt-1 text-[8px] text-[rgb(var(--sep-colour-8f8271))]">{effectiveWarping.baseWarpsPerDay} Base · {effectiveWarping.itemWarpsPerDay >= 0 ? "+" : ""}{effectiveWarping.itemWarpsPerDay} Items · {effectiveWarping.featWarpsPerDay >= 0 ? "+" : ""}{effectiveWarping.featWarpsPerDay} Feats</p>
</div>
</div>
</section>
<section className="mt-7 border border-[rgb(var(--sep-colour-60482e))]/45 bg-[rgb(var(--sep-colour-15100d))] p-5"><p className="text-[8px] uppercase tracking-[0.22em] text-[rgb(var(--sep-colour-806b50))]">Base Warping</p><h2 className="mt-1 font-serif text-2xl text-[rgb(var(--sep-colour-dec69a))]">Progression</h2><AdminActionForm action={updateWarpingBase} className="mt-4 grid gap-3 sm:grid-cols-[1fr_1fr_auto] sm:items-end"><input type="hidden" name="character_id" value={id}/><label><span className={l}>Affinity</span><input className={f} type="number" min={1} max={9} name="warping_affinity" defaultValue={c.warping_affinity??1}/></label><label><span className={l}>Shapes per day</span><input className={f} type="number" min={0} max={100} name="warps_per_day" defaultValue={c.warps_per_day??3}/></label><button className={b}>Save</button></AdminActionForm></section>
<section className="mt-5 border border-[rgb(var(--sep-colour-60482e))]/45 bg-[rgb(var(--sep-colour-15100d))] p-5"><p className="text-[8px] uppercase tracking-[0.22em] text-[rgb(var(--sep-colour-806b50))]">Staff Grants</p><h2 className="mt-1 font-serif text-2xl text-[rgb(var(--sep-colour-dec69a))]">Manual Shapes</h2><p className="mt-2 text-[10px] text-[rgb(var(--sep-colour-8f8271))]">Level Override bypasses Affinity only. Attribute prerequisites still apply.</p><AdminActionForm action={assignManualShape} className="mt-4 grid gap-3 lg:grid-cols-[1fr_auto_auto] lg:items-end"><input type="hidden" name="character_id" value={id}/><label><span className={l}>Shape</span><select className={f} name="shape_id" required defaultValue=""><option value="" disabled>Select Shape</option>{(sq.data??[]).map(s=><option key={s.id} value={s.id}>L{s.level} - {s.name} - {s.word_of_power}</option>)}</select></label><label className="flex min-h-[38px] items-center gap-2 border border-[rgb(var(--sep-colour-60482e))]/35 bg-[rgb(var(--sep-colour-100c09))] px-3 text-[9px] text-[rgb(var(--sep-colour-bba889))]"><input type="checkbox" name="override_level"/>Level Override</label><button className={b}>Assign Shape</button></AdminActionForm><div className="mt-4 space-y-2">{manual.map((x:any)=>{const s=Array.isArray(x.shape)?x.shape[0]:x.shape;return <AdminActionForm key={x.shape_id} action={removeManualShape} className="flex items-center justify-between border border-[rgb(var(--sep-colour-59432c))]/35 bg-[rgb(var(--sep-colour-100c09))] p-3"><input type="hidden" name="character_id" value={id}/><input type="hidden" name="shape_id" value={x.shape_id}/><span className="text-[10px] text-[rgb(var(--sep-colour-cdb48d))]">L{s?.level} - {s?.name}{x.level_override?" - LEVEL OVERRIDE":""}</span><button className="text-[8px] uppercase text-red-300">Remove</button></AdminActionForm>})}{!manual.length?<p className="p-3 text-[10px] italic text-[rgb(var(--sep-colour-746858))]">No manually granted Shapes.</p>:null}</div></section>
<section className="mt-5 border border-[rgb(var(--sep-colour-60482e))]/45 bg-[rgb(var(--sep-colour-15100d))] p-5"><p className="text-[8px] uppercase tracking-[0.22em] text-[rgb(var(--sep-colour-806b50))]">Order Progression</p><h2 className="mt-1 font-serif text-2xl text-[rgb(var(--sep-colour-dec69a))]">Order Shapes</h2><p className="mt-2 text-[10px] text-[rgb(var(--sep-colour-8f8271))]">Inherited cumulatively from current and lower Order Levels. These bypass Affinity and Attribute prerequisites.</p><div className="mt-4 space-y-2">{order.map((x:any)=>{const s=Array.isArray(x.shape)?x.shape[0]:x.shape;return <div key={x.shape_id} className="flex justify-between border border-[rgb(var(--sep-colour-59432c))]/35 bg-[rgb(var(--sep-colour-100c09))] p-3"><span className="text-[10px] text-[rgb(var(--sep-colour-cdb48d))]">L{s?.level} - {s?.name}</span><span className="text-[8px] uppercase text-[rgb(var(--sep-colour-b8bd83))]">Order Grant</span></div>})}{!order.length?<p className="p-3 text-[10px] italic text-[rgb(var(--sep-colour-746858))]">No inherited Order Shapes.</p>:null}</div></section>
</div></main>}
