from pathlib import Path

ROOT = Path.cwd()
rel = 'app/(portal)/layout.tsx'
path = ROOT / rel
text = path.read_text(encoding='utf-8')
old = '                [data-portal-shell-inner][data-has-cosmetic-left-panel="true"]\n                  .portal-left-shell > [data-portal-column],\n                [data-portal-shell-inner][data-has-cosmetic-right-panel="true"]\n                  .portal-right-shell > [data-portal-column],\n                [data-portal-shell-inner][data-has-cosmetic-centre-panel="true"]\n                  [data-portal-centre-host] > [data-portal-column] {\n                  position: relative;\n                  isolation: isolate;\n                  overflow: visible;\n                }\n\n                [data-portal-shell-inner][data-has-cosmetic-left-panel="true"]\n                  .portal-left-shell > [data-portal-column]::after,\n                [data-portal-shell-inner][data-has-cosmetic-right-panel="true"]\n                  .portal-right-shell > [data-portal-column]::after,\n                [data-portal-shell-inner][data-has-cosmetic-centre-panel="true"]\n                  [data-portal-centre-host] > [data-portal-column]::after {\n                  content: "";\n                  position: absolute;\n                  z-index: 35;\n                  inset: 1px;\n                  border: 14px solid transparent;\n                  border-image-width: 1;\n                  border-image-repeat: stretch;\n                  pointer-events: none;\n                  filter: drop-shadow(0 3px 8px rgba(0,0,0,.35));\n                }\n\n                [data-portal-shell-inner][data-has-cosmetic-left-panel="true"]\n                  .portal-left-shell > [data-portal-column]::after {\n                  border-image-source: var(--sep-cosmetic-left-panel-frame);\n                  border-image-slice: 10% 13%;\n                }\n\n                [data-portal-shell-inner][data-has-cosmetic-right-panel="true"]\n                  .portal-right-shell > [data-portal-column]::after {\n                  border-image-source: var(--sep-cosmetic-right-panel-frame);\n                  border-image-slice: 10% 13%;\n                }\n\n                [data-portal-shell-inner][data-has-cosmetic-centre-panel="true"]\n                  [data-portal-centre-host] > [data-portal-column]::after {\n                  border-image-source: var(--sep-cosmetic-centre-panel-frame);\n                  border-image-slice: 9% 7%;\n                }\n'
new = '                /*\n                 * Panel frames belong to the non-scrolling shell wrappers.\n                 * Never change overflow on [data-portal-column]: those elements\n                 * are the independent scroll containers.\n                 */\n                [data-portal-shell-inner][data-has-cosmetic-left-panel="true"]\n                  .portal-left-shell,\n                [data-portal-shell-inner][data-has-cosmetic-right-panel="true"]\n                  .portal-right-shell,\n                [data-portal-shell-inner][data-has-cosmetic-centre-panel="true"]\n                  [data-portal-centre-host] {\n                  position: relative;\n                  isolation: isolate;\n                }\n\n                [data-portal-shell-inner][data-has-cosmetic-left-panel="true"]\n                  .portal-left-shell::after,\n                [data-portal-shell-inner][data-has-cosmetic-right-panel="true"]\n                  .portal-right-shell::after,\n                [data-portal-shell-inner][data-has-cosmetic-centre-panel="true"]\n                  [data-portal-centre-host]::after {\n                  content: "";\n                  position: absolute;\n                  z-index: 35;\n                  inset: 1px;\n                  border: 14px solid transparent;\n                  border-image-width: 1;\n                  border-image-repeat: stretch;\n                  pointer-events: none;\n                  filter: drop-shadow(0 3px 8px rgba(0,0,0,.35));\n                }\n\n                [data-portal-shell-inner][data-has-cosmetic-left-panel="true"]\n                  .portal-left-shell::after {\n                  border-image-source: var(--sep-cosmetic-left-panel-frame);\n                  border-image-slice: 10% 13%;\n                }\n\n                [data-portal-shell-inner][data-has-cosmetic-right-panel="true"]\n                  .portal-right-shell::after {\n                  border-image-source: var(--sep-cosmetic-right-panel-frame);\n                  border-image-slice: 10% 13%;\n                }\n\n                [data-portal-shell-inner][data-has-cosmetic-centre-panel="true"]\n                  [data-portal-centre-host]::after {\n                  border-image-source: var(--sep-cosmetic-centre-panel-frame);\n                  border-image-slice: 9% 7%;\n                }\n'
if old not in text:
    raise SystemExit('Panel-frame CSS block not found. Nothing changed.')
text = text.replace(old, new, 1)
old_location = '              [data-portal-shell-inner][data-has-cosmetic-location-frame="true"]\n                [data-game-location-surface] {\n                position: relative;\n                isolation: isolate;\n                overflow: visible;\n              }\n'
new_location = '              [data-portal-shell-inner][data-has-cosmetic-location-frame="true"]\n                [data-game-location-surface] {\n                position: relative;\n                isolation: isolate;\n              }\n'
if old_location not in text:
    raise SystemExit('Location-frame overflow block not found. Nothing changed.')
text = text.replace(old_location, new_location, 1)
path.write_text(text, encoding='utf-8')
print('SUCCESS: cosmetic panel frames moved off the scroll containers.')
print('Left, centre and right columns retain their original scrolling.')
print('Location Frame no longer overrides overflow either.')
print('Run npm run build.')
