from pathlib import Path
import subprocess, sys

ROOT = Path.cwd()
EXPECTED_PREFIX = 'f8b48a2'

def fail(msg):
    print(f'\nERROR: {msg}\n')
    sys.exit(1)

head = subprocess.check_output(['git','rev-parse','HEAD'], cwd=ROOT, text=True).strip()
if not head.startswith(EXPECTED_PREFIX):
    fail(f'This patch targets {EXPECTED_PREFIX}, but HEAD is {head}.')

paths = {
  'player': ROOT / 'app/(portal)/game/components/RoomMusicPlayer.tsx',
  'mobile': ROOT / 'components/portal/mobile-portal-navigation.tsx',
  'manager': ROOT / 'components/admin/music-feature-manager.tsx',
}
for name, p in paths.items():
    if not p.exists(): fail(f'Missing {p.relative_to(ROOT)}')
files = {name: p.read_text(encoding='utf-8') for name,p in paths.items()}

def repl(name, old, new, label):
    count = files[name].count(old)
    if count != 1:
        fail(f'Preflight failed for {label}: expected 1 anchor, found {count}.')
    files[name] = files[name].replace(old, new, 1)

repl('player', '  const lastSavedSecondRef =\n    useRef(-1);', '  const lastSavedSecondRef =\n    useRef(-1);\n\n  const sourceLoadingRef =\n    useRef(false);\n\n  const pendingResumeRef =\n    useRef(0);', 'music source-loading refs')
repl('player', '  const [playing, setPlaying] =\n    useState(false);\n\n  const [\n    needsGesture,', '  const [playing, setPlaying] =\n    useState(false);\n\n  const [currentTime, setCurrentTime] =\n    useState(0);\n\n  const [duration, setDuration] =\n    useState(0);\n\n  const [\n    needsGesture,', 'music progress state')
repl('player', '  function restorePosition(\n    audio: HTMLAudioElement,\n    trackId: string,\n  ) {\n    try {\n      const raw =\n        window.localStorage.getItem(\n          positionKey(trackId),\n        );\n\n      const saved = Number(raw);\n\n      if (\n        Number.isFinite(saved) &&\n        saved > 0 &&\n        Number.isFinite(\n          audio.duration,\n        ) &&\n        audio.duration > 0\n      ) {\n        audio.currentTime =\n          Math.min(\n            saved,\n            Math.max(\n              0,\n              audio.duration - 0.25,\n            ),\n          );\n      }\n    } catch {\n      // Ignore unavailable local storage.\n    }\n  }', '  function readPosition(\n    trackId: string,\n  ) {\n    try {\n      const raw =\n        window.localStorage.getItem(\n          positionKey(trackId),\n        );\n\n      const saved = Number(raw);\n\n      return Number.isFinite(saved) &&\n        saved > 0\n        ? saved\n        : 0;\n    } catch {\n      return 0;\n    }\n  }\n\n  function restorePosition(\n    audio: HTMLAudioElement,\n    trackId: string,\n  ) {\n    const saved =\n      pendingResumeRef.current ||\n      readPosition(trackId);\n\n    if (\n      saved > 0 &&\n      Number.isFinite(audio.duration) &&\n      audio.duration > 0\n    ) {\n      const restored =\n        Math.min(\n          saved,\n          Math.max(\n            0,\n            audio.duration - 0.25,\n          ),\n        );\n\n      audio.currentTime = restored;\n      setCurrentTime(restored);\n    }\n\n    pendingResumeRef.current = 0;\n    sourceLoadingRef.current = false;\n  }', 'position restore logic')
repl('player', '    lastSavedSecondRef.current = -1;\n\n    audio.pause();\n    audio.src = track.url;', '    lastSavedSecondRef.current = -1;\n    pendingResumeRef.current =\n      readPosition(track.id);\n    sourceLoadingRef.current = true;\n    setCurrentTime(\n      pendingResumeRef.current,\n    );\n    setDuration(0);\n\n    audio.pause();\n    audio.src = track.url;', 'source initialization resume guard')
repl('player', '  function chooseMode(\n    personal: boolean,\n  ) {', '  function seek(\n    value: number,\n  ) {\n    const audio = audioRef.current;\n\n    if (\n      !audio ||\n      !Number.isFinite(value)\n    ) {\n      return;\n    }\n\n    const next = Math.max(\n      0,\n      Math.min(\n        value,\n        duration || value,\n      ),\n    );\n\n    audio.currentTime = next;\n    setCurrentTime(next);\n\n    if (activeTrack) {\n      savePosition(\n        activeTrack.id,\n        next,\n      );\n    }\n  }\n\n  function chooseMode(\n    personal: boolean,\n  ) {', 'seek function')
repl('player', '          <label className="mt-3 block">\n            <span className="mb-1.5 block text-[7px] uppercase tracking-[0.16em] text-[rgb(var(--sep-colour-756957))]">\n              Volume\n            </span>', '          <div className="mt-3">\n            <div className="mb-1.5 flex items-center justify-between gap-2 text-[7px] uppercase tracking-[0.14em] text-[rgb(var(--sep-colour-756957))]">\n              <span>Progress</span>\n              <span className="tabular-nums">\n                {Math.floor(currentTime / 60)}:{String(\n                  Math.floor(currentTime % 60),\n                ).padStart(2, "0")}\n                {" / "}\n                {Math.floor(duration / 60)}:{String(\n                  Math.floor(duration % 60),\n                ).padStart(2, "0")}\n              </span>\n            </div>\n            <input\n              type="range"\n              min={0}\n              max={duration > 0 ? duration : 0}\n              step={0.1}\n              value={Math.min(\n                currentTime,\n                duration || 0,\n              )}\n              onChange={(event) =>\n                seek(\n                  Number(\n                    event.target.value,\n                  ),\n                )\n              }\n              disabled={duration <= 0}\n              aria-label="Music progress"\n              className="block h-1.5 w-full cursor-pointer accent-[rgb(var(--sep-colour-a77b43))] disabled:cursor-not-allowed disabled:opacity-40"\n            />\n          </div>\n\n          <label className="mt-3 block">\n            <span className="mb-1.5 block text-[7px] uppercase tracking-[0.16em] text-[rgb(var(--sep-colour-756957))]">\n              Volume\n            </span>', 'music seek bar UI')
repl('player', '        onLoadedMetadata={(event) => {\n          if (activeTrack) {\n            restorePosition(\n              event.currentTarget,\n              activeTrack.id,\n            );\n          }\n        }}\n        onPlay={() => {\n          setPlaying(true);\n          setNeedsGesture(false);\n        }}\n        onPause={() => {\n          setPlaying(false);\n\n          if (activeTrack) {\n            savePosition(\n              activeTrack.id,\n            );\n          }\n        }}\n        onTimeUpdate={(event) => {\n          if (!activeTrack) return;\n\n          const second =\n            Math.floor(\n              event.currentTarget\n                .currentTime,\n            );\n\n          if (\n            second -\n              lastSavedSecondRef.current >=\n            2\n          ) {\n            lastSavedSecondRef.current =\n              second;\n\n            savePosition(\n              activeTrack.id,\n              event.currentTarget\n                .currentTime,\n            );\n          }\n        }}', '        onLoadedMetadata={(event) => {\n          const loadedDuration =\n            event.currentTarget.duration;\n\n          setDuration(\n            Number.isFinite(\n              loadedDuration,\n            )\n              ? loadedDuration\n              : 0,\n          );\n\n          if (activeTrack) {\n            restorePosition(\n              event.currentTarget,\n              activeTrack.id,\n            );\n          } else {\n            sourceLoadingRef.current =\n              false;\n          }\n        }}\n        onPlay={() => {\n          setPlaying(true);\n          setNeedsGesture(false);\n        }}\n        onPause={(event) => {\n          setPlaying(false);\n\n          if (\n            activeTrack &&\n            !sourceLoadingRef.current\n          ) {\n            savePosition(\n              activeTrack.id,\n              event.currentTarget\n                .currentTime,\n            );\n          }\n        }}\n        onTimeUpdate={(event) => {\n          const time =\n            event.currentTarget\n              .currentTime;\n\n          setCurrentTime(time);\n\n          if (!activeTrack) return;\n\n          const second =\n            Math.floor(time);\n\n          if (\n            second -\n              lastSavedSecondRef.current >=\n            2\n          ) {\n            lastSavedSecondRef.current =\n              second;\n\n            savePosition(\n              activeTrack.id,\n              time,\n            );\n          }\n        }}', 'audio progress and resume handlers')
repl('mobile', '<span className="min-w-0 flex-1 truncate text-[10px] uppercase tracking-[0.16em] text-[rgb(var(--sep-colour-b8a98f))]">\n                          Rules', '<span className="min-w-0 flex-1 truncate text-[10px] uppercase tracking-[0.16em] !text-[rgb(var(--sep-colour-b6a894))]">\n                          Rules', 'mobile Rules colour')
repl('mobile', '<span className="min-w-0 flex-1 truncate text-[10px] uppercase tracking-[0.16em] text-[rgb(var(--sep-colour-b8a98f))]">\n                          Economy & Crafting', '<span className="min-w-0 flex-1 truncate text-[10px] uppercase tracking-[0.16em] !text-[rgb(var(--sep-colour-b6a894))]">\n                          Economy & Crafting', 'mobile Economy & Crafting colour')
repl('mobile', '<span className="min-w-0 flex-1 text-[10px] uppercase tracking-[0.16em] text-[rgb(var(--sep-colour-b8a98f))]">\n                        Legal & Safety', '<span className="min-w-0 flex-1 text-[10px] uppercase tracking-[0.16em] !text-[rgb(var(--sep-colour-b6a894))]">\n                        Legal & Safety', 'mobile Legal & Safety colour')
repl('manager', 'function sizeLabel(bytes: number | null) {\n  if (bytes == null) return "Unknown size";\n  return bytes < 1048576 ? `${(bytes / 1024).toFixed(1)} KB` : `${(bytes / 1048576).toFixed(2)} MB`;\n}', 'function sizeLabel(bytes: number | null) {\n  if (bytes == null) return "Unknown size";\n  return bytes < 1048576 ? `${(bytes / 1024).toFixed(1)} KB` : `${(bytes / 1048576).toFixed(2)} MB`;\n}\n\nconst MAX_AUDIO_BYTES =\n  30 * 1024 * 1024;\n\nasync function responseJson(\n  response: Response,\n) {\n  const text = await response.text();\n\n  if (!text.trim()) {\n    return {} as {\n      error?: string;\n      tracks?: MusicTrackAdminRow[];\n    };\n  }\n\n  try {\n    return JSON.parse(text) as {\n      error?: string;\n      tracks?: MusicTrackAdminRow[];\n    };\n  } catch {\n    return {\n      error:\n        response.ok\n          ? "The server returned an invalid response."\n          : `Upload failed (${response.status}). The file may be too large for the request.`,\n    };\n  }\n}', 'safe music response helper')
if files['manager'].count('await r.json()') != 4:
    fail(f"Expected 4 music response JSON parses, found {files['manager'].count('await r.json()')}.")
files['manager'] = files['manager'].replace('await r.json()', 'await responseJson(r)')
repl('manager', '  async function upload(fd: FormData) {\n    setBusy(true); setMessage(""); setFailed(false);\n    try {', '  async function upload(fd: FormData) {\n    const file = fd.get("file");\n\n    if (\n      file instanceof File &&\n      file.size > MAX_AUDIO_BYTES\n    ) {\n      setFailed(true);\n      setMessage(\n        `That file is ${(file.size / 1048576).toFixed(2)} MB. Music files must be 30 MB or smaller.`,\n      );\n      return;\n    }\n\n    setBusy(true); setMessage(""); setFailed(false);\n    try {', 'client upload size check')

print('Preflight passed. Applying final music/mobile fixes...')
for name, p in paths.items():
    p.write_text(files[name], encoding='utf-8')
    print('  wrote', p.relative_to(ROOT))
print('\nDone. Run npm run build.')