from pathlib import Path

TARGET = Path("components/store/store-paddle-purchase-button.tsx")
current = TARGET.read_text(encoding="utf-8")
expected_marker = 'const src = "https://cdn.paddle.com/paddle/v2/paddle.js";'
if expected_marker not in current:
    raise SystemExit("Expected the 0600a40 Paddle CDN version, but it was not found. No files were changed.")

replacement = '"use client";\n\nimport { initializePaddle, type Paddle } from "@paddle/paddle-js";\nimport { useActionState, useEffect, useRef, useState } from "react";\n\nimport {\n  startStorePaddleCheckout,\n  type StorePaddleState,\n} from "@/app/(portal)/store/actions";\n\nconst initialState: StorePaddleState = {\n  ok: false,\n  error: null,\n  checkoutUrl: null,\n  transactionId: null,\n};\n\nlet paddlePromise: Promise<Paddle | undefined> | null = null;\n\nfunction getPaddle(): Promise<Paddle | undefined> {\n  if (paddlePromise) return paddlePromise;\n\n  const token = process.env.NEXT_PUBLIC_PADDLE_CLIENT_TOKEN?.trim();\n\n  if (!token) {\n    return Promise.reject(\n      new Error("Paddle client-side token is not configured."),\n    );\n  }\n\n  paddlePromise = initializePaddle({\n    token,\n    environment: token.startsWith("test_") ? "sandbox" : "production",\n  });\n\n  return paddlePromise;\n}\n\nexport function StorePaddlePurchaseButton({\n  productId,\n  label,\n}: {\n  productId: string;\n  label: string;\n}) {\n  const [state, action, pending] = useActionState(\n    startStorePaddleCheckout,\n    initialState,\n  );\n  const [clientError, setClientError] = useState<string | null>(null);\n  const openedTransactionRef = useRef<string | null>(null);\n\n  useEffect(() => {\n    if (!state.ok || !state.transactionId) return;\n    if (openedTransactionRef.current === state.transactionId) return;\n\n    openedTransactionRef.current = state.transactionId;\n    setClientError(null);\n\n    void getPaddle()\n      .then((paddle) => {\n        if (!paddle) {\n          throw new Error("Paddle.js did not initialize.");\n        }\n\n        paddle.Checkout.open({\n          transactionId: state.transactionId!,\n        });\n      })\n      .catch((error) => {\n        openedTransactionRef.current = null;\n        setClientError(\n          error instanceof Error\n            ? error.message\n            : "Paddle checkout could not be opened.",\n        );\n      });\n  }, [state.ok, state.transactionId]);\n\n  return (\n    <form action={action} className="mt-2">\n      <input type="hidden" name="productId" value={productId} />\n\n      <button\n        type="submit"\n        disabled={pending}\n        className="w-full border border-[rgb(var(--sep-colour-987344))]/70 bg-[rgb(var(--sep-colour-2a1d12))] px-3 py-2 text-[8px] uppercase tracking-[0.16em] text-[rgb(var(--sep-colour-efd9aa))] transition hover:border-[rgb(var(--sep-colour-b78b50))] disabled:cursor-wait disabled:opacity-55"\n      >\n        {pending ? "Opening checkout..." : `Buy for ${label}`}\n      </button>\n\n      {state.error || clientError ? (\n        <p className="mt-2 text-[9px] leading-4 text-red-300">\n          {state.error ?? clientError}\n        </p>\n      ) : null}\n    </form>\n  );\n}\n'
TARGET.write_text(replacement, encoding="utf-8")
print("Patched Paddle checkout to use @paddle/paddle-js.")
print(f"Updated: {TARGET}")
