from pathlib import Path
import subprocess

EXPECTED_HEAD = '660eda55f39eac8675a643a936cd5a97b051801a'
ROOT = Path.cwd()
REPLACEMENTS = {'components/portal/admin-record-search-context.tsx': [('Admin Items direct jump',
                                                        '    if (mode === "items") {\n'
                                                        '      target =\n'
                                                        '        document\n'
                                                        '          .querySelector<HTMLInputElement>(\n'
                                                        '            '
                                                        '`input[name="itemId"][value="${CSS.escape(entry.id)}"]`,\n'
                                                        '          )\n'
                                                        '          ?.closest<HTMLElement>("details, section, article") '
                                                        '?? null;\n'
                                                        '    }\n',
                                                        '    if (mode === "items") {\n'
                                                        '      target =\n'
                                                        '        document.getElementById(`item-${entry.id}`) ??\n'
                                                        '        document\n'
                                                        '          .querySelector<HTMLInputElement>(\n'
                                                        '            '
                                                        '`input[name="itemId"][value="${CSS.escape(entry.id)}"]`,\n'
                                                        '          )\n'
                                                        '          ?.closest<HTMLElement>("details") ??\n'
                                                        '        null;\n'
                                                        '    }\n')],
 'app/(portal)/game/components/RoomChatForm.tsx': [('ChatItem weapon fields',
                                                    '  cooldownReadyAt: string | null;\n  effects: {\n',
                                                    '  cooldownReadyAt: string | null;\n'
                                                    '  successDie?: number | null;\n'
                                                    '  successThreshold?: number | null;\n'
                                                    '  successAttribute?: CharacterAttributeKey | null;\n'
                                                    '  damageDice?: string | null;\n'
                                                    '  damageType?: string | null;\n'
                                                    '  categorySlug?: string | null;\n'
                                                    '  isEquipped?: boolean;\n'
                                                    '  equippedSlot?: string | null;\n'
                                                    '  effects: {\n'),
                                                   ('split regular Items and Weapons',
                                                    '  const [selectedItemKey, setSelectedItemKey] =\n'
                                                    '    useState(\n'
                                                    '      items[0]\n'
                                                    '        ? `${items[0].recordKind}:${items[0].recordId}`\n'
                                                    '        : "",\n'
                                                    '    );\n'
                                                    '\n'
                                                    '  const [itemTargetId, setItemTargetId] =\n'
                                                    '    useState("");\n'
                                                    '\n'
                                                    '  const selectedItem = useMemo(\n'
                                                    '    () =>\n'
                                                    '      items.find(\n'
                                                    '        (item) =>\n'
                                                    '          `${item.recordKind}:${item.recordId}` ===\n'
                                                    '          selectedItemKey,\n'
                                                    '      ) ??\n'
                                                    '      items[0] ??\n'
                                                    '      null,\n'
                                                    '    [items, selectedItemKey],\n'
                                                    '  );\n'
                                                    '\n'
                                                    '  useEffect(() => {\n'
                                                    '    setItemTargetId("");\n'
                                                    '  }, [selectedItemKey]);\n',
                                                    '  const regularItems = useMemo(\n'
                                                    '    () =>\n'
                                                    '      items.filter(\n'
                                                    '        (item) => item.categorySlug !== "weapon",\n'
                                                    '      ),\n'
                                                    '    [items],\n'
                                                    '  );\n'
                                                    '\n'
                                                    '  const weaponItems = useMemo(\n'
                                                    '    () =>\n'
                                                    '      items.filter(\n'
                                                    '        (item) =>\n'
                                                    '          item.categorySlug === "weapon" &&\n'
                                                    '          item.isEquipped === true &&\n'
                                                    '          ["main_hand", "off_hand"].includes(\n'
                                                    '            String(item.equippedSlot ?? ""),\n'
                                                    '          ),\n'
                                                    '      ),\n'
                                                    '    [items],\n'
                                                    '  );\n'
                                                    '\n'
                                                    '  const [selectedItemKey, setSelectedItemKey] =\n'
                                                    '    useState("");\n'
                                                    '\n'
                                                    '  const [itemTargetId, setItemTargetId] =\n'
                                                    '    useState("");\n'
                                                    '\n'
                                                    '  const selectedItem = useMemo(\n'
                                                    '    () =>\n'
                                                    '      regularItems.find(\n'
                                                    '        (item) =>\n'
                                                    '          `${item.recordKind}:${item.recordId}` ===\n'
                                                    '          selectedItemKey,\n'
                                                    '      ) ??\n'
                                                    '      regularItems[0] ??\n'
                                                    '      null,\n'
                                                    '    [regularItems, selectedItemKey],\n'
                                                    '  );\n'
                                                    '\n'
                                                    '  const [selectedWeaponKey, setSelectedWeaponKey] =\n'
                                                    '    useState("");\n'
                                                    '\n'
                                                    '  const [weaponTargetId, setWeaponTargetId] =\n'
                                                    '    useState("");\n'
                                                    '\n'
                                                    '  const selectedWeapon = useMemo(\n'
                                                    '    () =>\n'
                                                    '      weaponItems.find(\n'
                                                    '        (item) =>\n'
                                                    '          `${item.recordKind}:${item.recordId}` ===\n'
                                                    '          selectedWeaponKey,\n'
                                                    '      ) ??\n'
                                                    '      weaponItems[0] ??\n'
                                                    '      null,\n'
                                                    '    [weaponItems, selectedWeaponKey],\n'
                                                    '  );\n'
                                                    '\n'
                                                    '  useEffect(() => {\n'
                                                    '    if (\n'
                                                    '      selectedItemKey &&\n'
                                                    '      regularItems.some(\n'
                                                    '        (item) =>\n'
                                                    '          `${item.recordKind}:${item.recordId}` ===\n'
                                                    '          selectedItemKey,\n'
                                                    '      )\n'
                                                    '    ) {\n'
                                                    '      return;\n'
                                                    '    }\n'
                                                    '\n'
                                                    '    setSelectedItemKey(\n'
                                                    '      regularItems[0]\n'
                                                    '        ? '
                                                    '`${regularItems[0].recordKind}:${regularItems[0].recordId}`\n'
                                                    '        : "",\n'
                                                    '    );\n'
                                                    '  }, [regularItems, selectedItemKey]);\n'
                                                    '\n'
                                                    '  useEffect(() => {\n'
                                                    '    if (\n'
                                                    '      selectedWeaponKey &&\n'
                                                    '      weaponItems.some(\n'
                                                    '        (item) =>\n'
                                                    '          `${item.recordKind}:${item.recordId}` ===\n'
                                                    '          selectedWeaponKey,\n'
                                                    '      )\n'
                                                    '    ) {\n'
                                                    '      return;\n'
                                                    '    }\n'
                                                    '\n'
                                                    '    setSelectedWeaponKey(\n'
                                                    '      weaponItems[0]\n'
                                                    '        ? '
                                                    '`${weaponItems[0].recordKind}:${weaponItems[0].recordId}`\n'
                                                    '        : "",\n'
                                                    '    );\n'
                                                    '  }, [weaponItems, selectedWeaponKey]);\n'
                                                    '\n'
                                                    '  useEffect(() => {\n'
                                                    '    setItemTargetId("");\n'
                                                    '  }, [selectedItemKey]);\n'
                                                    '\n'
                                                    '  useEffect(() => {\n'
                                                    '    setWeaponTargetId("");\n'
                                                    '  }, [selectedWeaponKey]);\n'),
                                                   ('weapon attack inside attributes panel',
                                                    '          <UtilityPanelHeader\n'
                                                    '            title="Use Attributes"\n'
                                                    '            description="Choose the check to perform. The current '
                                                    'effective score is shown before rolling."\n'
                                                    '            onClose={() => setUtilityMode(null)}\n'
                                                    '          />\n'
                                                    '\n'
                                                    '          <input\n'
                                                    '            type="hidden"\n'
                                                    '            name="client_nonce"\n'
                                                    '            value={checkNonce ?? ""}\n'
                                                    '            readOnly\n'
                                                    '          />\n'
                                                    '\n'
                                                    '          <div className="grid gap-3 '
                                                    'sm:grid-cols-[minmax(0,1fr)_auto] sm:items-end">\n',
                                                    '          <UtilityPanelHeader\n'
                                                    '            title="Atk / Def / Dodge / Resist"\n'
                                                    '            description="Attack with an equipped Weapon, or make '
                                                    'a defensive, dodge, resistance or Attribute check."\n'
                                                    '            onClose={() => setUtilityMode(null)}\n'
                                                    '          />\n'
                                                    '\n'
                                                    '          {selectedWeapon ? (\n'
                                                    '            <div className="mb-3 border border-[#6a5032]/45 '
                                                    'bg-[#15100d] p-3">\n'
                                                    '              <p className="text-[8px] uppercase '
                                                    'tracking-[0.16em] text-[#9a7d55]">\n'
                                                    '                Equipped Weapon Attack\n'
                                                    '              </p>\n'
                                                    '\n'
                                                    '              <div className="mt-2 grid gap-2 md:grid-cols-2">\n'
                                                    '                <label>\n'
                                                    '                  <span className="mb-1 block text-[8px] '
                                                    'uppercase tracking-[0.12em] text-[#806b50]">\n'
                                                    '                    Weapon\n'
                                                    '                  </span>\n'
                                                    '                  <select\n'
                                                    '                    value={selectedWeaponKey}\n'
                                                    '                    onChange={(event) =>\n'
                                                    '                      setSelectedWeaponKey(event.target.value)\n'
                                                    '                    }\n'
                                                    '                    className="w-full border border-[#654c31] '
                                                    'bg-[#0f0c09] px-3 py-2.5 text-[10px] text-[#d8c29b] outline-none '
                                                    'focus:border-[#a17a45]"\n'
                                                    '                  >\n'
                                                    '                    {weaponItems.map((item) => (\n'
                                                    '                      <option\n'
                                                    '                        '
                                                    'key={`${item.recordKind}:${item.recordId}`}\n'
                                                    '                        '
                                                    'value={`${item.recordKind}:${item.recordId}`}\n'
                                                    '                      >\n'
                                                    '                        {item.name}\n'
                                                    '                        {item.equippedSlot\n'
                                                    '                          ? ` - ${\n'
                                                    '                              item.equippedSlot === "main_hand"\n'
                                                    '                                ? "Main Hand"\n'
                                                    '                                : "Off Hand"\n'
                                                    '                            }`\n'
                                                    '                          : ""}\n'
                                                    '                      </option>\n'
                                                    '                    ))}\n'
                                                    '                  </select>\n'
                                                    '                </label>\n'
                                                    '\n'
                                                    '                <label>\n'
                                                    '                  <span className="mb-1 block text-[8px] '
                                                    'uppercase tracking-[0.12em] text-[#806b50]">\n'
                                                    '                    Target\n'
                                                    '                  </span>\n'
                                                    '                  <select\n'
                                                    '                    value={weaponTargetId}\n'
                                                    '                    onChange={(event) =>\n'
                                                    '                      setWeaponTargetId(event.target.value)\n'
                                                    '                    }\n'
                                                    '                    className="w-full border border-[#654c31] '
                                                    'bg-[#0f0c09] px-3 py-2.5 text-[10px] text-[#d8c29b] outline-none '
                                                    'focus:border-[#a17a45]"\n'
                                                    '                  >\n'
                                                    '                    <option value="">Choose '
                                                    'character...</option>\n'
                                                    '                    {presentCharacters.map((entry) => (\n'
                                                    '                      <option key={entry.id} value={entry.id}>\n'
                                                    '                        {entry.display_name}\n'
                                                    '                      </option>\n'
                                                    '                    ))}\n'
                                                    '                  </select>\n'
                                                    '                </label>\n'
                                                    '              </div>\n'
                                                    '\n'
                                                    '              <div className="mt-2 flex flex-wrap gap-1.5 '
                                                    'text-[8px] uppercase tracking-[0.1em] text-[#a98b61]">\n'
                                                    '                <span className="border border-[#59432c]/40 px-2 '
                                                    'py-1">\n'
                                                    '                  Success{" "}\n'
                                                    '                  {selectedWeapon.successDie\n'
                                                    '                    ? `d${selectedWeapon.successDie}${\n'
                                                    '                        selectedWeapon.successAttribute\n'
                                                    '                          ? ` + '
                                                    '${ATTRIBUTE_LABELS[selectedWeapon.successAttribute]}`\n'
                                                    '                          : ""\n'
                                                    '                      } >= ${selectedWeapon.successThreshold ?? '
                                                    '"?"}`\n'
                                                    '                    : "Automatic"}\n'
                                                    '                </span>\n'
                                                    '                <span className="border border-[#59432c]/40 px-2 '
                                                    'py-1">\n'
                                                    '                  Damage{" "}\n'
                                                    '                  {selectedWeapon.damageDice ?? "None"}\n'
                                                    '                  {selectedWeapon.successAttribute\n'
                                                    '                    ? ` + '
                                                    '${ATTRIBUTE_LABELS[selectedWeapon.successAttribute]}`\n'
                                                    '                    : ""}\n'
                                                    '                  {selectedWeapon.damageType\n'
                                                    '                    ? ` ${selectedWeapon.damageType}`\n'
                                                    '                    : ""}\n'
                                                    '                </span>\n'
                                                    '              </div>\n'
                                                    '\n'
                                                    '              <div className="mt-3">\n'
                                                    '                <button\n'
                                                    '                  type="submit"\n'
                                                    '                  formAction={itemAction}\n'
                                                    '                  formNoValidate\n'
                                                    '                  disabled={\n'
                                                    '                    !weaponTargetId ||\n'
                                                    '                    Boolean(\n'
                                                    '                      selectedWeapon.cooldownReadyAt &&\n'
                                                    '                        '
                                                    'Date.parse(selectedWeapon.cooldownReadyAt) > Date.now(),\n'
                                                    '                    )\n'
                                                    '                  }\n'
                                                    '                  name="weapon_attack_submit"\n'
                                                    '                  value="1"\n'
                                                    '                  className="border border-[#85653c] bg-[#342617] '
                                                    'px-5 py-2.5 text-[9px] uppercase tracking-[0.18em] text-[#efd4a0] '
                                                    'transition hover:bg-[#4a351f] disabled:cursor-not-allowed '
                                                    'disabled:opacity-40"\n'
                                                    '                >\n'
                                                    '                  Attack\n'
                                                    '                </button>\n'
                                                    '                <input\n'
                                                    '                  type="hidden"\n'
                                                    '                  name="item_record_kind"\n'
                                                    '                  value={selectedWeapon.recordKind}\n'
                                                    '                  readOnly\n'
                                                    '                />\n'
                                                    '                <input\n'
                                                    '                  type="hidden"\n'
                                                    '                  name="item_record_id"\n'
                                                    '                  value={selectedWeapon.recordId}\n'
                                                    '                  readOnly\n'
                                                    '                />\n'
                                                    '                <input\n'
                                                    '                  type="hidden"\n'
                                                    '                  name="item_target_character_id"\n'
                                                    '                  value={weaponTargetId}\n'
                                                    '                  readOnly\n'
                                                    '                />\n'
                                                    '              </div>\n'
                                                    '            </div>\n'
                                                    '          ) : (\n'
                                                    '            <p className="mb-3 border border-[#59432c]/35 '
                                                    'bg-[#15100d] px-3 py-2 text-[9px] text-[#817565]">\n'
                                                    '              No Weapon is equipped in Main Hand or Off Hand.\n'
                                                    '            </p>\n'
                                                    '          )}\n'
                                                    '\n'
                                                    '          <input\n'
                                                    '            type="hidden"\n'
                                                    '            name="client_nonce"\n'
                                                    '            value={checkNonce ?? ""}\n'
                                                    '            readOnly\n'
                                                    '          />\n'
                                                    '\n'
                                                    '          <div className="grid gap-3 '
                                                    'sm:grid-cols-[minmax(0,1fr)_auto] sm:items-end">\n'),
                                                   ('generic Use Item excludes Weapons',
                                                    '                    {items.map((item) => (\n',
                                                    '                    {regularItems.map((item) => (\n'),
                                                   ('generic item empty label',
                                                    '              You have no usable Items.\n',
                                                    '              You have no usable non-Weapon Items.\n'),
                                                   ('utility button rename',
                                                    '          Use Attributes\n',
                                                    '          Atk / Def / Dodge / Resist\n')]}

def read(rel):
    p = ROOT / rel
    if not p.exists():
        raise SystemExit(f"Missing expected file: {rel}")
    return p.read_text(encoding="utf-8-sig")

def write(rel, text):
    (ROOT / rel).write_text(text, encoding="utf-8", newline="\n")
    print(f"UPDATED: {rel}")

head = subprocess.check_output(["git", "rev-parse", "HEAD"], text=True).strip()
if head != EXPECTED_HEAD:
    raise SystemExit(
        f"STOPPED: expected HEAD {EXPECTED_HEAD}, current HEAD is {head}. No files changed."
    )

for rel, replacements in REPLACEMENTS.items():
    text = read(rel)
    for label, old, new in replacements:
        count = text.count(old)
        if count != 1:
            raise SystemExit(
                f"STOPPED at {label} in {rel}: expected 1 match, found {count}. No guessing performed."
            )
        text = text.replace(old, new, 1)
    write(rel, text)

# tiny wording adjustments in the attributes panel
rel = "app/(portal)/game/components/RoomChatForm.tsx"
text = read(rel)
text = text.replace("Attribute check", "Check", 1)
text = text.replace('label="Use Attribute"', 'label="Roll Check"', 1)
write(rel, text)

print("\nPATCH COMPLETE.")
print("Run: npm run build")
