#!/usr/bin/env python3
from __future__ import annotations
import argparse
from pathlib import Path

BASELINE='89cc3ee'
def once(s,a,b,label):
    n=s.count(a)
    if n!=1: raise SystemExit(f'ERROR: {label}: expected anchor once, found {n}. Nothing written.')
    return s.replace(a,b,1)

def main():
    ap=argparse.ArgumentParser();ap.add_argument('--dry-run',action='store_true');args=ap.parse_args();root=Path.cwd();changes={}
    required=['app/(portal)/support/page.tsx','app/(portal)/support/[reference]/page.tsx','app/(portal)/admin/tickets/page.tsx','app/(portal)/admin/tickets/[reference]/page.tsx','app/(portal)/admin/layout.tsx','components/portal/portal-sidebar.tsx','components/portal/portal-header.tsx','components/portal/admin-context-panel.tsx','components/portal/portal-context-panel.tsx']
    for r in required:
        if not (root/r).exists(): raise SystemExit(f'ERROR: missing {r}. Nothing written.')

    def add(path,content): changes[root/path]=content

    add('supabase/patches/20260823_ticket_live_notifications.sql',r'''begin;
create table if not exists public.ticket_notification_reads (
 user_id uuid not null,
 ticket_id uuid not null references public.tickets(id) on delete cascade,
 last_read_at timestamptz not null default now(),
 primary key (user_id,ticket_id)
);
create index if not exists ticket_notification_reads_ticket_idx on public.ticket_notification_reads(ticket_id,last_read_at);
alter table public.ticket_notification_reads enable row level security;
commit;
''')

    add('components/support/ticket-live-sync.tsx',r'''"use client";
import {useEffect} from "react";import {useRouter} from "next/navigation";
export function TicketLiveSync({reference,admin=false}:{reference?:string;admin?:boolean}){const router=useRouter();useEffect(()=>{let dead=false;async function tick(){if(dead||document.visibilityState!=="visible")return;if(reference)await fetch("/api/support/read",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({reference,admin}),cache:"no-store"}).catch(()=>undefined);router.refresh();window.dispatchEvent(new Event("sepulchria:ticket-notifications-changed"));}void tick();const id=window.setInterval(()=>void tick(),2000);const focus=()=>void tick();window.addEventListener("focus",focus);return()=>{dead=true;window.clearInterval(id);window.removeEventListener("focus",focus)}},[admin,reference,router]);return null;}
''')

    add('components/support/ticket-notification-badge.tsx',r'''"use client";
import {useCallback,useEffect,useState} from "react";
export function TicketNotificationBadge({audience,variant}:{audience:"player"|"staff";variant:"sidebar"|"admin-nav"|"floating"}){const[count,setCount]=useState(0);const refresh=useCallback(async()=>{const r=await fetch(`/api/support/notifications?audience=${audience}`,{cache:"no-store"}).catch(()=>null);if(!r?.ok){setCount(0);return}const j=await r.json().catch(()=>({count:0}));setCount(Math.max(0,Number(j.count)||0))},[audience]);useEffect(()=>{void refresh();const id=window.setInterval(()=>void refresh(),2000);const f=()=>void refresh();window.addEventListener("focus",f);window.addEventListener("sepulchria:ticket-notifications-changed",f);return()=>{window.clearInterval(id);window.removeEventListener("focus",f);window.removeEventListener("sepulchria:ticket-notifications-changed",f)}},[refresh]);if(count<=0)return null;const label=count>99?"99+":String(count);const c="inline-flex items-center justify-center rounded-full border border-[rgb(var(--sep-colour-d19a4c))] bg-[rgb(var(--sep-colour-7a291f))] font-bold leading-none text-[rgb(var(--sep-colour-ffe1ac))]";if(variant==="floating")return <span className={`absolute -right-2 -top-2 h-5 min-w-5 px-1 text-[8px] ${c}`}>{label}</span>;return <span className={`ml-auto h-4 min-w-4 px-1 text-[7px] ${c}`}>{label}</span>}
''')

    add('app/(portal)/api/support/notifications/route.ts',r'''import {NextRequest,NextResponse} from "next/server";import {createAdminClient} from "@/lib/supabase/admin";import {createClient} from "@/lib/supabase/server";
const ROLES=["owner","admin","moderator","master"];
export async function GET(req:NextRequest){const sb=await createClient();const{data:{user}}=await sb.auth.getUser();if(!user)return NextResponse.json({count:0});const a=createAdminClient();const staff=req.nextUrl.searchParams.get("audience")==="staff";let ids:string[]=[];if(staff){const{data:s}=await a.from("staff_members").select("role").eq("user_id",user.id).maybeSingle();if(!s||!ROLES.includes(s.role))return NextResponse.json({count:0});const{data:t}=await a.from("tickets").select("id").limit(500);ids=(t??[]).map(x=>x.id)}else{const{data:t}=await a.from("tickets").select("id").eq("opened_by_user_id",user.id).limit(500);ids=(t??[]).map(x=>x.id)}if(!ids.length)return NextResponse.json({count:0});const types=staff?["ticket_created","player_replied","staff_replied"]:["staff_replied","ticket_state_changed"];const[{data:e},{data:r}]=await Promise.all([a.from("ticket_events").select("ticket_id,actor_user_id,event_type,created_at").in("ticket_id",ids).in("event_type",types),a.from("ticket_notification_reads").select("ticket_id,last_read_at").eq("user_id",user.id).in("ticket_id",ids)]);const reads=new Map((r??[]).map(x=>[x.ticket_id,new Date(x.last_read_at).getTime()]));let count=0;for(const x of e??[]){if(x.actor_user_id===user.id)continue;if(new Date(x.created_at).getTime()>(reads.get(x.ticket_id)??0))count++}return NextResponse.json({count})}
''')

    add('app/(portal)/api/support/read/route.ts',r'''import {NextRequest,NextResponse} from "next/server";import {createAdminClient} from "@/lib/supabase/admin";import {createClient} from "@/lib/supabase/server";const ROLES=["owner","admin","moderator","master"];
export async function POST(req:NextRequest){const sb=await createClient();const{data:{user}}=await sb.auth.getUser();if(!user)return NextResponse.json({ok:false},{status:401});const b=await req.json().catch(()=>({}));const ref=typeof b.reference==="string"?b.reference.slice(0,40):"";const admin=b.admin===true;const a=createAdminClient();let q=a.from("tickets").select("id").eq("public_reference",ref);if(admin){const{data:s}=await a.from("staff_members").select("role").eq("user_id",user.id).maybeSingle();if(!s||!ROLES.includes(s.role))return NextResponse.json({ok:false},{status:403})}else q=q.eq("opened_by_user_id",user.id);const{data:t}=await q.maybeSingle();if(!t)return NextResponse.json({ok:false},{status:404});const{error}=await a.from("ticket_notification_reads").upsert({user_id:user.id,ticket_id:t.id,last_read_at:new Date().toISOString()},{onConflict:"user_id,ticket_id"});return error?NextResponse.json({ok:false,error:error.message},{status:500}):NextResponse.json({ok:true})}
''')

    add('app/(portal)/api/support/context/route.ts',r'''import {NextRequest,NextResponse} from "next/server";import {createAdminClient} from "@/lib/supabase/admin";import {createClient} from "@/lib/supabase/server";const ROLES=["owner","admin","moderator","master"];
function text(type:string,d:any,actor:string){if(type==="ticket_created")return `${actor} opened the ticket`;if(type==="player_replied"||type==="staff_replied")return `${actor} replied`;if(type==="internal_note_added")return `${actor} added an internal note`;if(type==="staff_assigned")return `${actor} assigned the ticket`;if(type==="ticket_state_changed")return `${actor} changed the ticket${d?.status?` to ${String(d.status).replaceAll("_"," ")}`:""}${d?.priority?` · ${d.priority} priority`:""}`;return `${actor} updated the ticket`}
export async function GET(req:NextRequest){const sb=await createClient();const{data:{user}}=await sb.auth.getUser();if(!user)return NextResponse.json({error:"Unauthorized"},{status:401});const a=createAdminClient(),isAdmin=req.nextUrl.searchParams.get("admin")==="1",ref=req.nextUrl.searchParams.get("reference");if(isAdmin){const{data:s}=await a.from("staff_members").select("role").eq("user_id",user.id).maybeSingle();if(!s||!ROLES.includes(s.role))return NextResponse.json({error:"Forbidden"},{status:403})}let q=a.from("tickets").select("id,public_reference,status,priority,subject,assigned_staff_user_id,opened_by_user_id,updated_at").order("updated_at",{ascending:false}).limit(250);if(!isAdmin)q=q.eq("opened_by_user_id",user.id);const{data:tickets,error}=await q;if(error)return NextResponse.json({error:error.message},{status:500});if(ref){const t=(tickets??[]).find(x=>x.public_reference===ref);if(!t)return NextResponse.json({error:"Not found"},{status:404});let eq=a.from("ticket_events").select("id,actor_user_id,event_type,details,created_at").eq("ticket_id",t.id).order("created_at",{ascending:false}).limit(100);if(!isAdmin)eq=eq.neq("event_type","internal_note_added");const{data:e,error:ee}=await eq;if(ee)return NextResponse.json({error:ee.message},{status:500});const u=[...new Set((e??[]).map(x=>x.actor_user_id).filter(Boolean))];const{data:c}=u.length?await a.from("characters").select("user_id,display_name,first_name,surname").in("user_id",u):{data:[] as any[]};const names=new Map((c??[]).map(x=>[x.user_id,x.display_name||`${x.first_name??""} ${x.surname??""}`.trim()]));return NextResponse.json({events:(e??[]).map(x=>({...x,text:text(x.event_type,x.details,names.get(x.actor_user_id)??(x.actor_user_id===t.opened_by_user_id?"Player":"Staff"))}))})}const ids=(tickets??[]).map(x=>x.id);const{data:m}=ids.length?await a.from("ticket_messages").select("ticket_id,body").in("ticket_id",ids):{data:[] as any[]};const bodies=new Map<string,string[]>();for(const x of m??[]){const z=bodies.get(x.ticket_id)??[];z.push(String(x.body??""));bodies.set(x.ticket_id,z)}return NextResponse.json({tickets:(tickets??[]).map(x=>({...x,search_body:(bodies.get(x.id)??[]).join("\n")}))})}
''')

    add('components/support/ticket-context-panel.tsx',r'''"use client";import Link from "next/link";import {useEffect,useMemo,useState} from "react";
type T={id:string;public_reference:string;status:string;priority:string;subject:string;assigned_staff_user_id:string|null;search_body?:string};type E={id:string;text:string;created_at:string};function fmt(v:string){return new Intl.DateTimeFormat("en-GB",{day:"2-digit",month:"2-digit",year:"numeric",hour:"2-digit",minute:"2-digit"}).format(new Date(v))}
export function TicketContextPanel({admin=false,reference}:{admin?:boolean;reference?:string}){const[tickets,setTickets]=useState<T[]>([]),[events,setEvents]=useState<E[]>([]),[search,setSearch]=useState("");useEffect(()=>{let dead=false;async function load(){const qs=new URLSearchParams();if(admin)qs.set("admin","1");if(reference)qs.set("reference",reference);const r=await fetch(`/api/support/context?${qs}`,{cache:"no-store"});if(!r.ok||dead)return;const j=await r.json();reference?setEvents(j.events??[]):setTickets(j.tickets??[])}void load();const id=window.setInterval(()=>void load(),2000);return()=>{dead=true;window.clearInterval(id)}},[admin,reference]);const q=search.trim().toLowerCase();const visible=useMemo(()=>tickets.filter(t=>!q||[t.public_reference,t.status,t.priority,t.subject,t.assigned_staff_user_id??"",t.search_body??""].some(v=>String(v).toLowerCase().includes(q))),[q,tickets]);if(reference)return <div className="flex h-full min-h-0 flex-col"><p className="text-[8px] uppercase tracking-[0.24em] text-[rgb(var(--sep-colour-806b50))]">Ticket activity</p><h2 className="mt-1 font-serif text-xl text-[rgb(var(--sep-colour-d8bf91))]">{reference}</h2><div className="mt-3 max-h-[52vh] overflow-y-auto border border-[rgb(var(--sep-colour-59432c))]/40 bg-[rgb(var(--sep-colour-100c09))] p-2">{events.map(e=><div key={e.id} className="border-b border-[rgb(var(--sep-colour-59432c))]/30 px-1 py-2 last:border-b-0"><p className="text-[10px] leading-4 text-[rgb(var(--sep-colour-cbb28a))]">{e.text}</p><p className="mt-1 text-[7px] uppercase text-[rgb(var(--sep-colour-6f6353))]">{fmt(e.created_at)}</p></div>)}</div></div>;return <div className="flex h-full min-h-0 flex-col"><p className="text-[8px] uppercase tracking-[0.24em] text-[rgb(var(--sep-colour-806b50))]">{admin?"Administration":"Support"}</p><h2 className="mt-1 font-serif text-xl text-[rgb(var(--sep-colour-d8bf91))]">Jump to Ticket</h2><input type="search" value={search} onChange={e=>setSearch(e.target.value)} placeholder="Number, status, title, body, priority, assignee..." className="mt-3 w-full border border-[rgb(var(--sep-colour-59432c))]/45 bg-[rgb(var(--sep-colour-100c09))] px-3 py-2.5 text-xs outline-none"/><div className="mt-3 min-h-0 flex-1 space-y-1.5 overflow-y-auto">{visible.map(t=><Link key={t.id} href={`${admin?"/admin/tickets":"/support"}/${t.public_reference}`} className="block border border-[rgb(var(--sep-colour-59432c))]/40 bg-[rgb(var(--sep-colour-100c09))] px-3 py-2"><span className="block font-serif text-[13px] text-[rgb(var(--sep-colour-cbb28a))]">{t.subject}</span><span className="mt-1 block text-[7px] uppercase text-[rgb(var(--sep-colour-6f6353))]">{t.public_reference} · {t.status.replaceAll("_"," ")} · {t.priority}</span></Link>)}</div></div>}
''')

    # Inject live sync into exact Phase 2 pages without rewriting them.
    for rel, admin in [('app/(portal)/support/page.tsx',False),('app/(portal)/support/[reference]/page.tsx',False),('app/(portal)/admin/tickets/page.tsx',True),('app/(portal)/admin/tickets/[reference]/page.tsx',True)]:
        p=root/rel;s=p.read_text(encoding='utf-8')
        first=s.split('\n',1)[0]
        # all four have imports on first line(s); prepend safe import.
        s='import { TicketLiveSync } from "@/components/support/ticket-live-sync";\n'+s
        if rel.endswith('support/page.tsx'):
            s=once(s,'return <main className="p-5 sm:p-7 lg:p-9">','return <main className="p-5 sm:p-7 lg:p-9"><TicketLiveSync/>',rel+' render')
        elif rel.endswith('support/[reference]/page.tsx'):
            s=once(s,'return <main className="p-5 sm:p-7 lg:p-9">','return <main className="p-5 sm:p-7 lg:p-9"><TicketLiveSync reference={ticket.public_reference}/>',rel+' render')
        elif rel.endswith('admin/tickets/page.tsx'):
            s=once(s,'return <main className="p-5 sm:p-7 lg:p-9">','return <main className="p-5 sm:p-7 lg:p-9"><TicketLiveSync admin/>',rel+' render')
        else:
            s=once(s,'return <main className="p-5 sm:p-7 lg:p-9">','return <main className="p-5 sm:p-7 lg:p-9"><TicketLiveSync reference={t.public_reference} admin/>',rel+' render')
        changes[p]=s

    p=root/'app/(portal)/admin/layout.tsx';s=p.read_text(encoding='utf-8');s=once(s,'import { SubmittedCharacterBadge } from "@/components/admin/submitted-character-badge";','import { SubmittedCharacterBadge } from "@/components/admin/submitted-character-badge";\nimport { TicketNotificationBadge } from "@/components/support/ticket-notification-badge";','admin badge import');a='''            <AdminNavigationLink href="/admin/tidings">\n              Tidings\n            </AdminNavigationLink>            ''';s=once(s,a,a+'''\n\n            <AdminNavigationLink href="/admin/tickets">\n              <span className="flex items-center gap-2"><span>Tickets</span><TicketNotificationBadge audience="staff" variant="admin-nav" /></span>\n            </AdminNavigationLink>''','admin tickets link');changes[p]=s

    p=root/'components/portal/portal-header.tsx';s=p.read_text(encoding='utf-8');s=once(s,'import { SubmittedCharacterBadge } from "@/components/admin/submitted-character-badge";','import { SubmittedCharacterBadge } from "@/components/admin/submitted-character-badge";\nimport { TicketNotificationBadge } from "@/components/support/ticket-notification-badge";','header import');s=once(s,'<SubmittedCharacterBadge variant="floating" />','<SubmittedCharacterBadge variant="floating" />\n                <TicketNotificationBadge audience="staff" variant="floating" />','header badge');changes[p]=s

    p=root/'components/portal/portal-sidebar.tsx';s=p.read_text(encoding='utf-8');s=once(s,'import { UnreadMessageBadge } from "@/components/messages/unread-message-badge";','import { UnreadMessageBadge } from "@/components/messages/unread-message-badge";\nimport { TicketNotificationBadge } from "@/components/support/ticket-notification-badge";','sidebar import');old='''            <span className="block py-0.1 text-[9px] uppercase tracking-[0.18em] text-[rgb(var(--sep-colour-5f5549))]">\n              Support · Coming\n              soon\n            </span>''';new='''            <Link href="/support" className="flex items-center py-0.5 text-[9px] uppercase tracking-[0.18em] text-[rgb(var(--sep-colour-9f8b70))] transition hover:text-[rgb(var(--sep-colour-d8bf91))]">\n              <span>Support</span><TicketNotificationBadge audience="player" variant="sidebar" />\n            </Link>''';s=once(s,old,new,'support link');changes[p]=s

    p=root/'components/portal/admin-context-panel.tsx';s=p.read_text(encoding='utf-8');s=once(s,'import { createClient } from "@/lib/supabase/client";','import { createClient } from "@/lib/supabase/client";\nimport { TicketContextPanel } from "@/components/support/ticket-context-panel";','admin context import');s=once(s,'  | "characters"\n  | "forum";','  | "characters"\n  | "tickets"\n  | "forum";','admin type');anchor='''  if (\n    pathname === "/admin/forum" ||\n    pathname.startsWith(\n      "/admin/forum/",\n    )\n  ) {\n    return "forum";\n  }''';s=once(s,anchor,'''  if (pathname === "/admin/tickets" || pathname.startsWith("/admin/tickets/")) {\n    return "tickets";\n  }\n\n'''+anchor,'admin mode');anchor='''  if (mode === "forum") {\n    return (\n      <ForumModerationContext />\n    );\n  }''';s=once(s,anchor,anchor+'''\n\n  if (mode === "tickets") {\n    const match = pathname.match(/^\\/admin\\/tickets\\/([^/]+)$/);\n    return <TicketContextPanel admin reference={match ? decodeURIComponent(match[1]) : undefined} />;\n  }''','admin render');changes[p]=s

    p=root/'components/portal/portal-context-panel.tsx';s=p.read_text(encoding='utf-8');s=once(s,'import { OrderLeadershipContext } from "@/components/portal/order-leadership-context";','import { OrderLeadershipContext } from "@/components/portal/order-leadership-context";\nimport { TicketContextPanel } from "@/components/support/ticket-context-panel";','player context import');anchor='''  if (pathname === "/") {\n    return <DashboardContext context={context} />;\n  }''';s=once(s,anchor,anchor+'''\n\n  if (pathname === "/support" || pathname.startsWith("/support/")) {\n    const match = pathname.match(/^\\/support\\/([^/]+)$/);\n    const reference = match && match[1] !== "new" ? decodeURIComponent(match[1]) : undefined;\n    return <TicketContextPanel reference={reference} />;\n  }''','player context');changes[p]=s

    print(f'Baseline: {BASELINE}\nPrepared {len(changes)} local file change(s):')
    for p in changes: print(' ',p.relative_to(root))
    if args.dry_run: print('\nDRY RUN ONLY — no files written.');return
    for p,c in changes.items(): p.parent.mkdir(parents=True,exist_ok=True);p.write_text(c,encoding='utf-8',newline='\n');print('patched:',p.relative_to(root))
    print('\nApplied LOCALLY only. No GitHub write was performed.')
    print('IMPORTANT: run supabase/patches/20260823_ticket_live_notifications.sql in Supabase SQL Editor, then npm run build.')
if __name__=='__main__': main()
