from pathlib import Path
import base64

ROOT = Path.cwd()
game_page = ROOT / "app/(portal)/game/page.tsx"
action_path = ROOT / "app/(portal)/game/house-of-chances-actions.ts"
panel_path = ROOT / "app/(portal)/game/components/HouseOfChancesPanel.tsx"

if not game_page.exists():
    raise SystemExit(f"Missing expected file: {game_page}")

text = game_page.read_text(encoding="utf-8")

import_anchor = 'import { OddJobsPanel, type OddJobStateRow } from "./components/OddJobsPanel";'
import_line = """import {
  HouseOfChancesPanel,
  type HouseOfChancesStateRow,
} from "./components/HouseOfChancesPanel";"""

if import_line not in text:
    if import_anchor not in text:
        raise SystemExit("Could not find OddJobsPanel import anchor.")
    text = text.replace(import_anchor, import_anchor + "\n" + import_line, 1)

promise_anchor = """  const oddJobsPromise =
    room.slug === "odd-jobs-bureau"
      ? supabase.rpc(
          "get_my_odd_jobs_state",
        )
      : Promise.resolve({
          data: [],
          error: null,
        });
"""

if "const houseOfChancesPromise =" not in text:
    if promise_anchor not in text:
        raise SystemExit("Could not find Odd Jobs promise anchor.")
    addition = promise_anchor + """
  const houseOfChancesPromise =
    room.slug === "house-of-chances"
      ? supabase.rpc(
          "get_my_house_of_chances_state",
        )
      : Promise.resolve({
          data: [],
          error: null,
        });
"""
    text = text.replace(promise_anchor, addition, 1)

old = """    headquartersManageData,
    oddJobsResult,
    breezeLodgingsResult,
"""
new = """    headquartersManageData,
    oddJobsResult,
    houseOfChancesResult,
    breezeLodgingsResult,
"""
if "houseOfChancesResult," not in text:
    if old not in text:
        raise SystemExit("Could not find Promise destructuring anchor.")
    text = text.replace(old, new, 1)

old = """    headquartersManageDataPromise,
    oddJobsPromise,
    breezeLodgingsPromise,
"""
new = """    headquartersManageDataPromise,
    oddJobsPromise,
    houseOfChancesPromise,
    breezeLodgingsPromise,
"""
if "houseOfChancesPromise,\n    breezeLodgingsPromise" not in text:
    if old not in text:
        raise SystemExit("Could not find Promise values anchor.")
    text = text.replace(old, new, 1)

old = """  const oddJobs =
    (oddJobsData ?? []) as OddJobStateRow[];

  const {
    data: breezeLodgingsData,
"""
new = """  const oddJobs =
    (oddJobsData ?? []) as OddJobStateRow[];

  const {
    data: houseOfChancesData,
    error: houseOfChancesError,
  } = houseOfChancesResult;

  if (houseOfChancesError) {
    throw new Error(
      `Unable to load House of Chances: ${houseOfChancesError.message}`,
    );
  }

  const houseOfChancesState =
    ((houseOfChancesData ?? [])[0] ?? null) as
      | HouseOfChancesStateRow
      | null;

  const {
    data: breezeLodgingsData,
"""
if "const houseOfChancesState =" not in text:
    if old not in text:
        raise SystemExit("Could not find House state parse anchor.")
    text = text.replace(old, new, 1)

old = """    {room.slug === "odd-jobs-bureau" ? (
      <OddJobsPanel jobs={oddJobs} />
    ) : null}
"""
new = """    {room.slug === "house-of-chances" && houseOfChancesState ? (
      <HouseOfChancesPanel state={houseOfChancesState} />
    ) : null}

    {room.slug === "odd-jobs-bureau" ? (
      <OddJobsPanel jobs={oddJobs} />
    ) : null}
"""
if "<HouseOfChancesPanel state={houseOfChancesState} />" not in text:
    if old not in text:
        raise SystemExit("Could not find Odd Jobs render anchor.")
    text = text.replace(old, new, 1)

game_page.write_text(text, encoding="utf-8")
action_path.write_bytes(base64.b64decode("InVzZSBzZXJ2ZXIiOwoKaW1wb3J0IHsgcmV2YWxpZGF0ZVBhdGggfSBmcm9tICJuZXh0L2NhY2hlIjsKaW1wb3J0IHsgY3JlYXRlQ2xpZW50IH0gZnJvbSAiQC9saWIvc3VwYWJhc2Uvc2VydmVyIjsKCmV4cG9ydCB0eXBlIEhvdXNlT2ZDaGFuY2VzUGxheVJlc3VsdCA9IHsKICBwbGF5X2lkOiBzdHJpbmc7CiAgcm9sbF8xOiBudW1iZXI7CiAgcm9sbF8yOiBudW1iZXI7CiAgcm9sbF8zOiBudW1iZXI7CiAgcm9sbF90b3RhbDogbnVtYmVyOwogIGNvc3RfcGFpZDogbnVtYmVyOwogIG1hdGNoZWRfcnVsZV9pZDogc3RyaW5nIHwgbnVsbDsKICBtYXRjaGVkX3J1bGVfbmFtZTogc3RyaW5nIHwgbnVsbDsKICByZXdhcmRfc25hcHNob3Q6IEFycmF5PAogICAgfCB7IHR5cGU6ICJyZW1uYW50cyI7IGFtb3VudDogbnVtYmVyIH0KICAgIHwgeyB0eXBlOiAiaXRlbSI7IGl0ZW1faWQ6IHN0cmluZzsgbmFtZTogc3RyaW5nOyBxdWFudGl0eTogbnVtYmVyIH0KICA+OwogIHdhbGxldF9iYWxhbmNlOiBudW1iZXI7CiAgcGxheXNfdXNlZDogbnVtYmVyOwogIHBsYXlzX3JlbWFpbmluZzogbnVtYmVyOwp9OwoKZXhwb3J0IGFzeW5jIGZ1bmN0aW9uIHBsYXlIb3VzZU9mQ2hhbmNlcygpIHsKICBjb25zdCBzdXBhYmFzZSA9IGF3YWl0IGNyZWF0ZUNsaWVudCgpOwogIGNvbnN0IHsgZGF0YSwgZXJyb3IgfSA9IGF3YWl0IHN1cGFiYXNlLnJwYygicGxheV9ob3VzZV9vZl9jaGFuY2VzIik7CgogIGlmIChlcnJvcikgewogICAgcmV0dXJuIHsgb2s6IGZhbHNlIGFzIGNvbnN0LCBtZXNzYWdlOiBlcnJvci5tZXNzYWdlLCByZXN1bHQ6IG51bGwgfTsKICB9CgogIGNvbnN0IHJhdyA9IEFycmF5LmlzQXJyYXkoZGF0YSkgPyBkYXRhWzBdIDogZGF0YTsKCiAgaWYgKCFyYXcpIHsKICAgIHJldHVybiB7CiAgICAgIG9rOiBmYWxzZSBhcyBjb25zdCwKICAgICAgbWVzc2FnZTogIlRoZSBIb3VzZSBjb3VsZCBub3QgY29uZmlybSB0aGUgcGxheS4iLAogICAgICByZXN1bHQ6IG51bGwsCiAgICB9OwogIH0KCiAgY29uc3QgcmVzdWx0ID0gcmF3IGFzIEhvdXNlT2ZDaGFuY2VzUGxheVJlc3VsdDsKCiAgcmV2YWxpZGF0ZVBhdGgoIi9nYW1lIik7CiAgcmV2YWxpZGF0ZVBhdGgoIi9jaGFyYWN0ZXIiKTsKCiAgcmV0dXJuIHsKICAgIG9rOiB0cnVlIGFzIGNvbnN0LAogICAgbWVzc2FnZTogcmVzdWx0Lm1hdGNoZWRfcnVsZV9uYW1lCiAgICAgID8gYEZvcnR1bmUgc21pbGVzOiAke3Jlc3VsdC5tYXRjaGVkX3J1bGVfbmFtZX0uYAogICAgICA6ICJObyBwcml6ZSB0aGlzIHRpbWUuIiwKICAgIHJlc3VsdCwKICB9Owp9Cg=="))
panel_path.write_bytes(base64.b64decode("InVzZSBjbGllbnQiOwoKaW1wb3J0IHsgdXNlUmVmLCB1c2VTdGF0ZSwgdXNlVHJhbnNpdGlvbiB9IGZyb20gInJlYWN0IjsKaW1wb3J0IHsgdXNlUm91dGVyIH0gZnJvbSAibmV4dC9uYXZpZ2F0aW9uIjsKCmltcG9ydCB7CiAgcGxheUhvdXNlT2ZDaGFuY2VzLAogIHR5cGUgSG91c2VPZkNoYW5jZXNQbGF5UmVzdWx0LAp9IGZyb20gIi4uL2hvdXNlLW9mLWNoYW5jZXMtYWN0aW9ucyI7CmltcG9ydCB7IGZvcm1hdFJlbW5hbnRzIH0gZnJvbSAiQC9saWIvZWNvbm9teS9jdXJyZW5jeSI7CgpleHBvcnQgdHlwZSBIb3VzZU9mQ2hhbmNlc1N0YXRlUm93ID0gewogIGlzX29wZW46IGJvb2xlYW47CiAgcGxheV9jb3N0OiBudW1iZXI7CiAgZGFpbHlfcGxheV9saW1pdDogbnVtYmVyOwogIHBsYXlzX3VzZWQ6IG51bWJlcjsKICBwbGF5c19yZW1haW5pbmc6IG51bWJlcjsKICB3YWxsZXRfYmFsYW5jZTogbnVtYmVyOwogIHJvb21fc2x1Zzogc3RyaW5nOwp9OwoKdHlwZSBSZWVsVmFsdWVzID0gW251bWJlciB8IG51bGwsIG51bWJlciB8IG51bGwsIG51bWJlciB8IG51bGxdOwoKZnVuY3Rpb24gc2xlZXAobXM6IG51bWJlcikgewogIHJldHVybiBuZXcgUHJvbWlzZSgocmVzb2x2ZSkgPT4gd2luZG93LnNldFRpbWVvdXQocmVzb2x2ZSwgbXMpKTsKfQoKZnVuY3Rpb24gcmFuZG9tRDEwMCgpIHsKICByZXR1cm4gTWF0aC5mbG9vcihNYXRoLnJhbmRvbSgpICogMTAwKSArIDE7Cn0KCmZ1bmN0aW9uIHJld2FyZExhYmVsKAogIHJld2FyZDogSG91c2VPZkNoYW5jZXNQbGF5UmVzdWx0WyJyZXdhcmRfc25hcHNob3QiXVtudW1iZXJdLAopIHsKICBpZiAocmV3YXJkLnR5cGUgPT09ICJyZW1uYW50cyIpIHsKICAgIHJldHVybiBgKyR7Zm9ybWF0UmVtbmFudHMoTnVtYmVyKHJld2FyZC5hbW91bnQpKX1gOwogIH0KCiAgcmV0dXJuIGAke3Jld2FyZC5uYW1lfSDDlyAke3Jld2FyZC5xdWFudGl0eX1gOwp9CgpleHBvcnQgZnVuY3Rpb24gSG91c2VPZkNoYW5jZXNQYW5lbCh7CiAgc3RhdGUsCn06IHsKICBzdGF0ZTogSG91c2VPZkNoYW5jZXNTdGF0ZVJvdzsKfSkgewogIGNvbnN0IHJvdXRlciA9IHVzZVJvdXRlcigpOwogIGNvbnN0IFtwZW5kaW5nLCBzdGFydFRyYW5zaXRpb25dID0gdXNlVHJhbnNpdGlvbigpOwogIGNvbnN0IFtzcGlubmluZywgc2V0U3Bpbm5pbmddID0gdXNlU3RhdGUoZmFsc2UpOwogIGNvbnN0IFtyZWVscywgc2V0UmVlbHNdID0gdXNlU3RhdGU8UmVlbFZhbHVlcz4oW251bGwsIG51bGwsIG51bGxdKTsKICBjb25zdCBbbWVzc2FnZSwgc2V0TWVzc2FnZV0gPSB1c2VTdGF0ZTxzdHJpbmcgfCBudWxsPihudWxsKTsKICBjb25zdCBbcmVzdWx0LCBzZXRSZXN1bHRdID0gdXNlU3RhdGU8SG91c2VPZkNoYW5jZXNQbGF5UmVzdWx0IHwgbnVsbD4obnVsbCk7CiAgY29uc3QgaW50ZXJ2YWxSZWYgPSB1c2VSZWY8bnVtYmVyIHwgbnVsbD4obnVsbCk7CgogIGNvbnN0IGNhbkFmZm9yZCA9IE51bWJlcihzdGF0ZS53YWxsZXRfYmFsYW5jZSkgPj0gTnVtYmVyKHN0YXRlLnBsYXlfY29zdCk7CiAgY29uc3QgaGFzUGxheXMgPSBOdW1iZXIoc3RhdGUucGxheXNfcmVtYWluaW5nKSA+IDA7CiAgY29uc3QgY2FuUGxheSA9CiAgICBzdGF0ZS5pc19vcGVuICYmIGNhbkFmZm9yZCAmJiBoYXNQbGF5cyAmJiAhcGVuZGluZyAmJiAhc3Bpbm5pbmc7CgogIGZ1bmN0aW9uIHN0b3BTcGluSW50ZXJ2YWwoKSB7CiAgICBpZiAoaW50ZXJ2YWxSZWYuY3VycmVudCAhPT0gbnVsbCkgewogICAgICB3aW5kb3cuY2xlYXJJbnRlcnZhbChpbnRlcnZhbFJlZi5jdXJyZW50KTsKICAgICAgaW50ZXJ2YWxSZWYuY3VycmVudCA9IG51bGw7CiAgICB9CiAgfQoKICBmdW5jdGlvbiBwbGF5KCkgewogICAgaWYgKCFjYW5QbGF5KSByZXR1cm47CgogICAgc2V0TWVzc2FnZShudWxsKTsKICAgIHNldFJlc3VsdChudWxsKTsKICAgIHNldFNwaW5uaW5nKHRydWUpOwoKICAgIGludGVydmFsUmVmLmN1cnJlbnQgPSB3aW5kb3cuc2V0SW50ZXJ2YWwoKCkgPT4gewogICAgICBzZXRSZWVscyhbcmFuZG9tRDEwMCgpLCByYW5kb21EMTAwKCksIHJhbmRvbUQxMDAoKV0pOwogICAgfSwgNzApOwoKICAgIHN0YXJ0VHJhbnNpdGlvbihhc3luYyAoKSA9PiB7CiAgICAgIGNvbnN0IHN0YXJ0ZWQgPSBEYXRlLm5vdygpOwogICAgICBjb25zdCByZXNwb25zZSA9IGF3YWl0IHBsYXlIb3VzZU9mQ2hhbmNlcygpOwogICAgICBjb25zdCBlbGFwc2VkID0gRGF0ZS5ub3coKSAtIHN0YXJ0ZWQ7CgogICAgICBpZiAoZWxhcHNlZCA8IDEyMDApIHsKICAgICAgICBhd2FpdCBzbGVlcCgxMjAwIC0gZWxhcHNlZCk7CiAgICAgIH0KCiAgICAgIHN0b3BTcGluSW50ZXJ2YWwoKTsKCiAgICAgIGlmICghcmVzcG9uc2Uub2sgfHwgIXJlc3BvbnNlLnJlc3VsdCkgewogICAgICAgIHNldFNwaW5uaW5nKGZhbHNlKTsKICAgICAgICBzZXRNZXNzYWdlKHJlc3BvbnNlLm1lc3NhZ2UpOwogICAgICAgIHNldFJlZWxzKFtudWxsLCBudWxsLCBudWxsXSk7CiAgICAgICAgcmV0dXJuOwogICAgICB9CgogICAgICBjb25zdCBmaW5hbCA9IHJlc3BvbnNlLnJlc3VsdDsKCiAgICAgIHNldFJlZWxzKFtmaW5hbC5yb2xsXzEsIHJhbmRvbUQxMDAoKSwgcmFuZG9tRDEwMCgpXSk7CiAgICAgIGF3YWl0IHNsZWVwKDI2MCk7CiAgICAgIHNldFJlZWxzKFtmaW5hbC5yb2xsXzEsIGZpbmFsLnJvbGxfMiwgcmFuZG9tRDEwMCgpXSk7CiAgICAgIGF3YWl0IHNsZWVwKDI2MCk7CiAgICAgIHNldFJlZWxzKFtmaW5hbC5yb2xsXzEsIGZpbmFsLnJvbGxfMiwgZmluYWwucm9sbF8zXSk7CgogICAgICBzZXRSZXN1bHQoZmluYWwpOwogICAgICBzZXRNZXNzYWdlKHJlc3BvbnNlLm1lc3NhZ2UpOwogICAgICBzZXRTcGlubmluZyhmYWxzZSk7CiAgICAgIHJvdXRlci5yZWZyZXNoKCk7CiAgICB9KTsKICB9CgogIHJldHVybiAoCiAgICA8ZGV0YWlscyBjbGFzc05hbWU9Imdyb3VwIG1heC1oLVs3MiVdIHNocmluay0wIG92ZXJmbG93LXktYXV0byBib3JkZXItYiBib3JkZXItW3JnYih2YXIoLS1zZXAtY29sb3VyLTYwNDgyZSkpXS80NSBiZy1bcmdiKHZhcigtLXNlcC1jb2xvdXItMTIwZTBiKSldIj4KICAgICAgPHN1bW1hcnkgY2xhc3NOYW1lPSJzdGlja3kgdG9wLTAgei0zMCBmbGV4IGN1cnNvci1wb2ludGVyIGxpc3Qtbm9uZSBpdGVtcy1jZW50ZXIganVzdGlmeS1iZXR3ZWVuIGdhcC0zIGJnLVtyZ2IodmFyKC0tc2VwLWNvbG91ci0xMjBlMGIpKV0gcHgtMyBweS0yIFsmOjotd2Via2l0LWRldGFpbHMtbWFya2VyXTpoaWRkZW4iPgogICAgICAgIDxkaXY+CiAgICAgICAgICA8cCBjbGFzc05hbWU9InRleHQtWzdweF0gdXBwZXJjYXNlIHRyYWNraW5nLVswLjE4ZW1dIHRleHQtW3JnYih2YXIoLS1zZXAtY29sb3VyLTgwNmI1MCkpXSI+CiAgICAgICAgICAgIEhvdXNlIG9mIENoYW5jZXMKICAgICAgICAgIDwvcD4KICAgICAgICAgIDxwIGNsYXNzTmFtZT0ibXQtMC41IGZvbnQtc2VyaWYgdGV4dC1zbSB0ZXh0LVtyZ2IodmFyKC0tc2VwLWNvbG91ci1kZWM4OWYpKV0iPgogICAgICAgICAgICBUZW1wdCBGYXRlCiAgICAgICAgICA8L3A+CiAgICAgICAgPC9kaXY+CgogICAgICAgIDxkaXYgY2xhc3NOYW1lPSJmbGV4IGl0ZW1zLWNlbnRlciBnYXAtNSI+CiAgICAgICAgICA8ZGl2IGNsYXNzTmFtZT0idGV4dC1yaWdodCI+CiAgICAgICAgICAgIDxwIGNsYXNzTmFtZT0idGV4dC1bN3B4XSB1cHBlcmNhc2UgdHJhY2tpbmctWzAuMTJlbV0gdGV4dC1bcmdiKHZhcigtLXNlcC1jb2xvdXItNzU2OTU4KSldIj4KICAgICAgICAgICAgICBSZW1uYW50cwogICAgICAgICAgICA8L3A+CiAgICAgICAgICAgIDxwIGNsYXNzTmFtZT0iZm9udC1zZXJpZiB0ZXh0LWJhc2UgdGV4dC1bcmdiKHZhcigtLXNlcC1jb2xvdXItZTRjNTg5KSldIj4KICAgICAgICAgICAgICB7Zm9ybWF0UmVtbmFudHMoTnVtYmVyKHN0YXRlLndhbGxldF9iYWxhbmNlKSl9CiAgICAgICAgICAgIDwvcD4KICAgICAgICAgIDwvZGl2PgoKICAgICAgICAgIDxkaXYgY2xhc3NOYW1lPSJ0ZXh0LXJpZ2h0Ij4KICAgICAgICAgICAgPHAgY2xhc3NOYW1lPSJ0ZXh0LVs3cHhdIHVwcGVyY2FzZSB0cmFja2luZy1bMC4xMmVtXSB0ZXh0LVtyZ2IodmFyKC0tc2VwLWNvbG91ci03NTY5NTgpKV0iPgogICAgICAgICAgICAgIFBsYXlzCiAgICAgICAgICAgIDwvcD4KICAgICAgICAgICAgPHAgY2xhc3NOYW1lPSJmb250LXNlcmlmIHRleHQtYmFzZSB0ZXh0LVtyZ2IodmFyKC0tc2VwLWNvbG91ci1lNGM1ODkpKV0iPgogICAgICAgICAgICAgIHtzdGF0ZS5wbGF5c191c2VkfSAvIHtzdGF0ZS5kYWlseV9wbGF5X2xpbWl0fQogICAgICAgICAgICA8L3A+CiAgICAgICAgICA8L2Rpdj4KCiAgICAgICAgICA8c3BhbiBjbGFzc05hbWU9InRleHQtWzlweF0gdXBwZXJjYXNlIHRyYWNraW5nLVswLjEyZW1dIHRleHQtW3JnYih2YXIoLS1zZXAtY29sb3VyLWE4OGQ2NSkpXSI+CiAgICAgICAgICAgIDxzcGFuIGNsYXNzTmFtZT0iZ3JvdXAtb3BlbjpoaWRkZW4iPlBsYXkg4pa+PC9zcGFuPgogICAgICAgICAgICA8c3BhbiBjbGFzc05hbWU9ImhpZGRlbiBncm91cC1vcGVuOmlubGluZSI+SGlkZSDilrQ8L3NwYW4+CiAgICAgICAgICA8L3NwYW4+CiAgICAgICAgPC9kaXY+CiAgICAgIDwvc3VtbWFyeT4KCiAgICAgIDxkaXYgY2xhc3NOYW1lPSJib3JkZXItdCBib3JkZXItW3JnYih2YXIoLS1zZXAtY29sb3VyLTU5NDMyYykpXS8zMCBweC0zIHB5LTQiPgogICAgICAgIHshc3RhdGUuaXNfb3BlbiA/ICgKICAgICAgICAgIDxwIGNsYXNzTmFtZT0ibWItMyBib3JkZXIgYm9yZGVyLVtyZ2IodmFyKC0tc2VwLWNvbG91ci03MzQyMzgpKV0vNDUgYmctW3JnYih2YXIoLS1zZXAtY29sb3VyLTIxMTMwZikpXSBweC0zIHB5LTIgdGV4dC1bOXB4XSB0ZXh0LVtyZ2IodmFyKC0tc2VwLWNvbG91ci1jZjc2NmIpKV0iPgogICAgICAgICAgICBUaGUgdGFibGVzIGFyZSBwcmVzZW50bHkgY2xvc2VkLgogICAgICAgICAgPC9wPgogICAgICAgICkgOiBudWxsfQoKICAgICAgICA8ZGl2IGNsYXNzTmFtZT0ibXgtYXV0byBtYXgtdy0yeGwiPgogICAgICAgICAgPHAgY2xhc3NOYW1lPSJ0ZXh0LWNlbnRlciB0ZXh0LVs5cHhdIGxlYWRpbmctNSB0ZXh0LVtyZ2IodmFyKC0tc2VwLWNvbG91ci04ZjgyNzEpKV0iPgogICAgICAgICAgICBUaHJlZSB0dXJucyBvZiBmb3J0dW5lLiBPbmUgcHJpY2UuIFdoYXRldmVyIHRoZSBIb3VzZSByZXZlYWxzIGlzIGZpbmFsLgogICAgICAgICAgPC9wPgoKICAgICAgICAgIDxkaXYgY2xhc3NOYW1lPSJtdC00IGdyaWQgZ3JpZC1jb2xzLTMgZ2FwLTIgc206Z2FwLTMiPgogICAgICAgICAgICB7cmVlbHMubWFwKCh2YWx1ZSwgaW5kZXgpID0+ICgKICAgICAgICAgICAgICA8ZGl2CiAgICAgICAgICAgICAgICBrZXk9e2luZGV4fQogICAgICAgICAgICAgICAgY2xhc3NOYW1lPXtbCiAgICAgICAgICAgICAgICAgICJyZWxhdGl2ZSBmbGV4IGFzcGVjdC1bNS80XSBpdGVtcy1jZW50ZXIganVzdGlmeS1jZW50ZXIgb3ZlcmZsb3ctaGlkZGVuIiwKICAgICAgICAgICAgICAgICAgImJvcmRlciBib3JkZXItW3JnYih2YXIoLS1zZXAtY29sb3VyLThiNjczZikpXS83MCIsCiAgICAgICAgICAgICAgICAgICJiZy1bcmFkaWFsLWdyYWRpZW50KGNpcmNsZV9hdF9jZW50ZXIscmdiKHZhcigtLXNlcC1jb2xvdXItMmIyMTE3KSkscmdiKHZhcigtLXNlcC1jb2xvdXItMTAwYzA5KSlfNzIlKV0iLAogICAgICAgICAgICAgICAgICAic2hhZG93LVtpbnNldF8wXzBfMThweF9yZ2JhKDE5NiwxNTAsODIsMC4xNiksMF8wXzEwcHhfcmdiYSgwLDAsMCwwLjM1KV0iLAogICAgICAgICAgICAgICAgICBzcGlubmluZyA/ICJhbmltYXRlLXB1bHNlIiA6ICIiLAogICAgICAgICAgICAgICAgXS5qb2luKCIgIil9CiAgICAgICAgICAgICAgPgogICAgICAgICAgICAgICAgPGRpdiBjbGFzc05hbWU9InBvaW50ZXItZXZlbnRzLW5vbmUgYWJzb2x1dGUgaW5zZXQtWzNweF0gYm9yZGVyIGJvcmRlci1bcmdiKHZhcigtLXNlcC1jb2xvdXItYjU4YTRjKSldLzI1IiAvPgogICAgICAgICAgICAgICAgPHNwYW4gY2xhc3NOYW1lPSJmb250LXNlcmlmIHRleHQtM3hsIHRhYnVsYXItbnVtcyB0ZXh0LVtyZ2IodmFyKC0tc2VwLWNvbG91ci1lZmQ2YTgpKV0gc206dGV4dC00eGwiPgogICAgICAgICAgICAgICAgICB7dmFsdWUgPz8gIj8ifQogICAgICAgICAgICAgICAgPC9zcGFuPgogICAgICAgICAgICAgIDwvZGl2PgogICAgICAgICAgICApKX0KICAgICAgICAgIDwvZGl2PgoKICAgICAgICAgIDxkaXYgY2xhc3NOYW1lPSJtdC00IGZsZXggZmxleC13cmFwIGl0ZW1zLWNlbnRlciBqdXN0aWZ5LWNlbnRlciBnYXAtMyI+CiAgICAgICAgICAgIDxidXR0b24KICAgICAgICAgICAgICB0eXBlPSJidXR0b24iCiAgICAgICAgICAgICAgb25DbGljaz17cGxheX0KICAgICAgICAgICAgICBkaXNhYmxlZD17IWNhblBsYXl9CiAgICAgICAgICAgICAgY2xhc3NOYW1lPSJtaW4tdy1bMTkwcHhdIGJvcmRlciBib3JkZXItW3JnYih2YXIoLS1zZXAtY29sb3VyLTk4NzM0NCkpXSBiZy1bcmdiKHZhcigtLXNlcC1jb2xvdXItM2IyOTE5KSldIHB4LTUgcHktMyB0ZXh0LVs5cHhdIHVwcGVyY2FzZSB0cmFja2luZy1bMC4xOGVtXSB0ZXh0LVtyZ2IodmFyKC0tc2VwLWNvbG91ci1lZmQ2YTgpKV0gdHJhbnNpdGlvbiBob3Zlcjpib3JkZXItW3JnYih2YXIoLS1zZXAtY29sb3VyLWI3OGI1MCkpXSBob3ZlcjpiZy1bcmdiKHZhcigtLXNlcC1jb2xvdXItNGEzMzFmKSldIGRpc2FibGVkOmN1cnNvci1ub3QtYWxsb3dlZCBkaXNhYmxlZDpvcGFjaXR5LTQwIgogICAgICAgICAgICA+CiAgICAgICAgICAgICAge3NwaW5uaW5nIHx8IHBlbmRpbmcKICAgICAgICAgICAgICAgID8gIkZvcnR1bmUgdHVybnMuLi4iCiAgICAgICAgICAgICAgICA6IGBUZW1wdCBGYXRlIOKAlCAke2Zvcm1hdFJlbW5hbnRzKE51bWJlcihzdGF0ZS5wbGF5X2Nvc3QpKX1gfQogICAgICAgICAgICA8L2J1dHRvbj4KCiAgICAgICAgICAgIDxzcGFuIGNsYXNzTmFtZT0idGV4dC1bOHB4XSB1cHBlcmNhc2UgdHJhY2tpbmctWzAuMTJlbV0gdGV4dC1bcmdiKHZhcigtLXNlcC1jb2xvdXItNzU2OTU4KSldIj4KICAgICAgICAgICAgICB7c3RhdGUucGxheXNfcmVtYWluaW5nfSBwbGF5CiAgICAgICAgICAgICAge3N0YXRlLnBsYXlzX3JlbWFpbmluZyA9PT0gMSA/ICIiIDogInMifSByZW1haW5pbmcgdG9kYXkKICAgICAgICAgICAgPC9zcGFuPgogICAgICAgICAgPC9kaXY+CgogICAgICAgICAgeyFjYW5BZmZvcmQgJiYgc3RhdGUuaXNfb3BlbiA/ICgKICAgICAgICAgICAgPHAgY2xhc3NOYW1lPSJtdC0zIHRleHQtY2VudGVyIHRleHQtWzlweF0gdGV4dC1yZWQtNDAwIj4KICAgICAgICAgICAgICBZb3UgZG8gbm90IGhhdmUgZW5vdWdoIFJlbW5hbnRzIHRvIHBsYXkuCiAgICAgICAgICAgIDwvcD4KICAgICAgICAgICkgOiBudWxsfQoKICAgICAgICAgIHshaGFzUGxheXMgJiYgc3RhdGUuaXNfb3BlbiA/ICgKICAgICAgICAgICAgPHAgY2xhc3NOYW1lPSJtdC0zIHRleHQtY2VudGVyIHRleHQtWzlweF0gdGV4dC1bcmdiKHZhcigtLXNlcC1jb2xvdXItYTk4YjYxKSldIj4KICAgICAgICAgICAgICBGb3J0dW5lIGhhcyBoZWFyZCBlbm91Z2ggZnJvbSB5b3UgdG9kYXkuIFJldHVybiB0b21vcnJvdy4KICAgICAgICAgICAgPC9wPgogICAgICAgICAgKSA6IG51bGx9CgogICAgICAgICAge3Jlc3VsdCA/ICgKICAgICAgICAgICAgPGRpdiBjbGFzc05hbWU9Im10LTQgYm9yZGVyIGJvcmRlci1bcmdiKHZhcigtLXNlcC1jb2xvdXItNmY1NDM1KSldLzU1IGJnLVtyZ2IodmFyKC0tc2VwLWNvbG91ci0xNzExMGQpKV0gcC0zIHRleHQtY2VudGVyIj4KICAgICAgICAgICAgICA8cCBjbGFzc05hbWU9InRleHQtWzhweF0gdXBwZXJjYXNlIHRyYWNraW5nLVswLjE4ZW1dIHRleHQtW3JnYih2YXIoLS1zZXAtY29sb3VyLTgwNmI1MCkpXSI+CiAgICAgICAgICAgICAgICBSZXN1bHQKICAgICAgICAgICAgICA8L3A+CiAgICAgICAgICAgICAgPHAgY2xhc3NOYW1lPSJtdC0xIGZvbnQtc2VyaWYgdGV4dC1sZyB0ZXh0LVtyZ2IodmFyKC0tc2VwLWNvbG91ci1kZmM5OWYpKV0iPgogICAgICAgICAgICAgICAge3Jlc3VsdC5tYXRjaGVkX3J1bGVfbmFtZSA/PyAiTm8gUHJpemUifQogICAgICAgICAgICAgIDwvcD4KCiAgICAgICAgICAgICAge3Jlc3VsdC5yZXdhcmRfc25hcHNob3QubGVuZ3RoID8gKAogICAgICAgICAgICAgICAgPGRpdiBjbGFzc05hbWU9Im10LTIgZmxleCBmbGV4LXdyYXAganVzdGlmeS1jZW50ZXIgZ2FwLTIiPgogICAgICAgICAgICAgICAgICB7cmVzdWx0LnJld2FyZF9zbmFwc2hvdC5tYXAoKHJld2FyZCwgaW5kZXgpID0+ICgKICAgICAgICAgICAgICAgICAgICA8c3BhbgogICAgICAgICAgICAgICAgICAgICAga2V5PXtgJHtyZXdhcmQudHlwZX0tJHtpbmRleH1gfQogICAgICAgICAgICAgICAgICAgICAgY2xhc3NOYW1lPSJib3JkZXIgYm9yZGVyLVtyZ2IodmFyKC0tc2VwLWNvbG91ci03NjU3MzUpKV0vNTUgYmctW3JnYih2YXIoLS1zZXAtY29sb3VyLTIxMTcwZikpXSBweC0yIHB5LTEgdGV4dC1bOHB4XSB0ZXh0LVtyZ2IodmFyKC0tc2VwLWNvbG91ci1kOGJiOGEpKV0iCiAgICAgICAgICAgICAgICAgICAgPgogICAgICAgICAgICAgICAgICAgICAge3Jld2FyZExhYmVsKHJld2FyZCl9CiAgICAgICAgICAgICAgICAgICAgPC9zcGFuPgogICAgICAgICAgICAgICAgICApKX0KICAgICAgICAgICAgICAgIDwvZGl2PgogICAgICAgICAgICAgICkgOiAoCiAgICAgICAgICAgICAgICA8cCBjbGFzc05hbWU9Im10LTIgdGV4dC1bOXB4XSB0ZXh0LVtyZ2IodmFyKC0tc2VwLWNvbG91ci03NTY5NTgpKV0iPgogICAgICAgICAgICAgICAgICBObyB3aW5uaW5ncyB0aGlzIHRpbWUuCiAgICAgICAgICAgICAgICA8L3A+CiAgICAgICAgICAgICAgKX0KICAgICAgICAgICAgPC9kaXY+CiAgICAgICAgICApIDogbnVsbH0KCiAgICAgICAgICB7bWVzc2FnZSA/ICgKICAgICAgICAgICAgPHAKICAgICAgICAgICAgICBhcmlhLWxpdmU9InBvbGl0ZSIKICAgICAgICAgICAgICBjbGFzc05hbWU9e1sKICAgICAgICAgICAgICAgICJtdC0zIHRleHQtY2VudGVyIHRleHQtWzlweF0iLAogICAgICAgICAgICAgICAgcmVzdWx0CiAgICAgICAgICAgICAgICAgID8gInRleHQtW3JnYih2YXIoLS1zZXAtY29sb3VyLWMzYTc3OCkpXSIKICAgICAgICAgICAgICAgICAgOiAidGV4dC1yZWQtNDAwIiwKICAgICAgICAgICAgICBdLmpvaW4oIiAiKX0KICAgICAgICAgICAgPgogICAgICAgICAgICAgIHttZXNzYWdlfQogICAgICAgICAgICA8L3A+CiAgICAgICAgICApIDogbnVsbH0KICAgICAgICA8L2Rpdj4KICAgICAgPC9kaXY+CiAgICA8L2RldGFpbHM+CiAgKTsKfQo="))

print("SUCCESS")
print("Patched player House of Chances experience.")
print("Next: npm run build")
