from pathlib import Path
import base64

layout_path = Path("app/(portal)/layout.tsx")
css_path = Path("components/sepulchria/sep-ui-unified.css")
manager_path = Path("components/portal/portal-modal-viewport-manager.tsx")

if not layout_path.exists():
    raise SystemExit("Missing app/(portal)/layout.tsx. No files changed.")

if not css_path.exists():
    raise SystemExit(
        "Missing components/sepulchria/sep-ui-unified.css. "
        "Apply the successful unification patch first. No files changed."
    )

layout = layout_path.read_text(encoding="utf-8")
css = css_path.read_text(encoding="utf-8")

# ------------------------------------------------------------------
# 1. Fix the ugly/pale modal border in the existing unified CSS.
# ------------------------------------------------------------------
old_modal_border = """  --sep-unified-modal-border:
      color-mix(in srgb, rgb(var(--sep-colour-795a34)) 70%, transparent);"""

new_modal_border = """  --sep-unified-modal-border:
      var(--sep-unified-control-border);"""

if old_modal_border in css:
    css = css.replace(
        old_modal_border,
        new_modal_border,
        1,
    )

# Also replace the non-@supports fallback modal token when present.
css = css.replace(
    "--sep-unified-modal-border: rgba(var(--sep-rgb-121-90-52), 0.70);",
    "--sep-unified-modal-border: var(--sep-unified-control-border);",
)

# ------------------------------------------------------------------
# 2. Add the central modal viewport manager.
# ------------------------------------------------------------------
manager_path.write_text(
    base64.b64decode("InVzZSBjbGllbnQiOwoKaW1wb3J0IHsgdXNlRWZmZWN0IH0gZnJvbSAicmVhY3QiOwoKdHlwZSBNYW5hZ2VkTW9kYWxTdGF0ZSA9IHsKICBkaWFsb2c6IEhUTUxFbGVtZW50OwogIGZyYW1lOiBIVE1MRWxlbWVudDsKICB0b2dnbGU6IEhUTUxCdXR0b25FbGVtZW50OwogIHJlc3RvcmVkT25jZTogYm9vbGVhbjsKICBzYXZlZFdpZHRoOiBzdHJpbmcgfCBudWxsOwogIHNhdmVkSGVpZ2h0OiBzdHJpbmcgfCBudWxsOwp9OwoKY29uc3QgbWFuYWdlZCA9IG5ldyBXZWFrTWFwPEhUTUxFbGVtZW50LCBNYW5hZ2VkTW9kYWxTdGF0ZT4oKTsKCmZ1bmN0aW9uIGlzQmFja2Ryb3BFbGVtZW50KGVsZW1lbnQ6IEhUTUxFbGVtZW50KTogYm9vbGVhbiB7CiAgY29uc3QgY2xhc3NlcyA9IGVsZW1lbnQuY2xhc3NOYW1lOwoKICBpZiAodHlwZW9mIGNsYXNzZXMgIT09ICJzdHJpbmciKSB7CiAgICByZXR1cm4gZmFsc2U7CiAgfQoKICByZXR1cm4gKAogICAgZWxlbWVudC50YWdOYW1lID09PSAiQlVUVE9OIiAmJgogICAgY2xhc3Nlcy5pbmNsdWRlcygiYWJzb2x1dGUiKSAmJgogICAgY2xhc3Nlcy5pbmNsdWRlcygiaW5zZXQtMCIpCiAgKTsKfQoKZnVuY3Rpb24gcmVzb2x2ZUZyYW1lKGRpYWxvZzogSFRNTEVsZW1lbnQpOiBIVE1MRWxlbWVudCB7CiAgY29uc3QgZGlyZWN0Q2hpbGRyZW4gPSBBcnJheS5mcm9tKGRpYWxvZy5jaGlsZHJlbikuZmlsdGVyKAogICAgKGNoaWxkKTogY2hpbGQgaXMgSFRNTEVsZW1lbnQgPT4KICAgICAgY2hpbGQgaW5zdGFuY2VvZiBIVE1MRWxlbWVudCAmJgogICAgICAhaXNCYWNrZHJvcEVsZW1lbnQoY2hpbGQpLAogICk7CgogIGNvbnN0IHNlbWFudGljRnJhbWUgPSBkaXJlY3RDaGlsZHJlbi5maW5kKChjaGlsZCkgPT4KICAgIGNoaWxkLm1hdGNoZXMoInNlY3Rpb24sIGFydGljbGUiKSwKICApOwoKICBpZiAoc2VtYW50aWNGcmFtZSkgewogICAgcmV0dXJuIHNlbWFudGljRnJhbWU7CiAgfQoKICBjb25zdCBib3JkZXJlZEZyYW1lID0gZGlyZWN0Q2hpbGRyZW4uZmluZCgoY2hpbGQpID0+IHsKICAgIGNvbnN0IGNsYXNzZXMgPSBjaGlsZC5jbGFzc05hbWU7CgogICAgcmV0dXJuICgKICAgICAgdHlwZW9mIGNsYXNzZXMgPT09ICJzdHJpbmciICYmCiAgICAgICgKICAgICAgICBjbGFzc2VzLnNwbGl0KC9ccysvKS5pbmNsdWRlcygiYm9yZGVyIikgfHwKICAgICAgICBjbGFzc2VzLmluY2x1ZGVzKCJtYXgtdy0iKSB8fAogICAgICAgIGNsYXNzZXMuaW5jbHVkZXMoInNoYWRvdy0iKQogICAgICApCiAgICApOwogIH0pOwoKICBpZiAoYm9yZGVyZWRGcmFtZSkgewogICAgcmV0dXJuIGJvcmRlcmVkRnJhbWU7CiAgfQoKICByZXR1cm4gZGlyZWN0Q2hpbGRyZW5bMF0gPz8gZGlhbG9nOwp9CgpmdW5jdGlvbiBmaW5kQ29udHJvbCgKICBmcmFtZTogSFRNTEVsZW1lbnQsCiAga2luZDogIm1pbmltaXplIiB8ICJjbG9zZSIsCik6IEhUTUxCdXR0b25FbGVtZW50IHwgbnVsbCB7CiAgY29uc3QgYnV0dG9ucyA9IEFycmF5LmZyb20oCiAgICBmcmFtZS5xdWVyeVNlbGVjdG9yQWxsPEhUTUxCdXR0b25FbGVtZW50PigiYnV0dG9uIiksCiAgKTsKCiAgcmV0dXJuICgKICAgIGJ1dHRvbnMuZmluZCgoYnV0dG9uKSA9PiB7CiAgICAgIGNvbnN0IHRleHQgPSBbCiAgICAgICAgYnV0dG9uLmdldEF0dHJpYnV0ZSgiYXJpYS1sYWJlbCIpLAogICAgICAgIGJ1dHRvbi5nZXRBdHRyaWJ1dGUoInRpdGxlIiksCiAgICAgIF0KICAgICAgICAuZmlsdGVyKEJvb2xlYW4pCiAgICAgICAgLmpvaW4oIiAiKQogICAgICAgIC50b0xvd2VyQ2FzZSgpOwoKICAgICAgaWYgKGtpbmQgPT09ICJtaW5pbWl6ZSIpIHsKICAgICAgICByZXR1cm4gdGV4dC5pbmNsdWRlcygibWluaW1pemUiKSB8fCB0ZXh0LmluY2x1ZGVzKCJtaW5pbWlzZSIpOwogICAgICB9CgogICAgICByZXR1cm4gdGV4dC5pbmNsdWRlcygiY2xvc2UiKTsKICAgIH0pID8/IG51bGwKICApOwp9CgpmdW5jdGlvbiBzZXRUb2dnbGVBcHBlYXJhbmNlKAogIHN0YXRlOiBNYW5hZ2VkTW9kYWxTdGF0ZSwKICBtYXhpbWl6ZWQ6IGJvb2xlYW4sCikgewogIHN0YXRlLnRvZ2dsZS50ZXh0Q29udGVudCA9IG1heGltaXplZCA/ICLinZAiIDogIuKWoSI7CiAgc3RhdGUudG9nZ2xlLnNldEF0dHJpYnV0ZSgKICAgICJhcmlhLWxhYmVsIiwKICAgIG1heGltaXplZCA/ICJSZXN0b3JlIG1vZGFsIHNpemUiIDogIk1heGltaXplIG1vZGFsIiwKICApOwogIHN0YXRlLnRvZ2dsZS5zZXRBdHRyaWJ1dGUoCiAgICAidGl0bGUiLAogICAgbWF4aW1pemVkID8gIlJlc3RvcmUgc2l6ZSIgOiAiTWF4aW1pemUiLAogICk7CiAgc3RhdGUudG9nZ2xlLnNldEF0dHJpYnV0ZSgKICAgICJhcmlhLXByZXNzZWQiLAogICAgbWF4aW1pemVkID8gInRydWUiIDogImZhbHNlIiwKICApOwp9CgpmdW5jdGlvbiBzZXRNYXhpbWl6ZWQoCiAgc3RhdGU6IE1hbmFnZWRNb2RhbFN0YXRlLAogIG1heGltaXplZDogYm9vbGVhbiwKKSB7CiAgc3RhdGUuZGlhbG9nLmRhdGFzZXQuc2VwTW9kYWxNYXhpbWl6ZWQgPQogICAgbWF4aW1pemVkID8gInRydWUiIDogImZhbHNlIjsKCiAgc3RhdGUuZnJhbWUuZGF0YXNldC5zZXBNb2RhbE1heGltaXplZCA9CiAgICBtYXhpbWl6ZWQgPyAidHJ1ZSIgOiAiZmFsc2UiOwoKICBpZiAoIW1heGltaXplZCkgewogICAgaWYgKAogICAgICBzdGF0ZS5yZXN0b3JlZE9uY2UgJiYKICAgICAgc3RhdGUuc2F2ZWRXaWR0aCAmJgogICAgICBzdGF0ZS5zYXZlZEhlaWdodAogICAgKSB7CiAgICAgIHN0YXRlLmZyYW1lLnN0eWxlLndpZHRoID0gc3RhdGUuc2F2ZWRXaWR0aDsKICAgICAgc3RhdGUuZnJhbWUuc3R5bGUuaGVpZ2h0ID0gc3RhdGUuc2F2ZWRIZWlnaHQ7CiAgICB9CgogICAgc3RhdGUucmVzdG9yZWRPbmNlID0gdHJ1ZTsKICB9CgogIHNldFRvZ2dsZUFwcGVhcmFuY2Uoc3RhdGUsIG1heGltaXplZCk7Cn0KCmZ1bmN0aW9uIGNyZWF0ZVRvZ2dsZSgKICBkaWFsb2c6IEhUTUxFbGVtZW50LAogIGZyYW1lOiBIVE1MRWxlbWVudCwKKTogSFRNTEJ1dHRvbkVsZW1lbnQgewogIGNvbnN0IGV4aXN0aW5nID0KICAgIGZyYW1lLnF1ZXJ5U2VsZWN0b3I8SFRNTEJ1dHRvbkVsZW1lbnQ+KAogICAgICAiYnV0dG9uW2RhdGEtc2VwLW1vZGFsLXNpemUtdG9nZ2xlPSd0cnVlJ10iLAogICAgKTsKCiAgaWYgKGV4aXN0aW5nKSB7CiAgICByZXR1cm4gZXhpc3Rpbmc7CiAgfQoKICBjb25zdCB0b2dnbGUgPSBkb2N1bWVudC5jcmVhdGVFbGVtZW50KCJidXR0b24iKTsKCiAgdG9nZ2xlLnR5cGUgPSAiYnV0dG9uIjsKICB0b2dnbGUuZGF0YXNldC5zZXBNb2RhbFNpemVUb2dnbGUgPSAidHJ1ZSI7CiAgdG9nZ2xlLmNsYXNzTmFtZSA9ICJzZXAtbW9kYWwtc2l6ZS10b2dnbGUiOwoKICBjb25zdCBtaW5pbWl6ZSA9IGZpbmRDb250cm9sKGZyYW1lLCAibWluaW1pemUiKTsKICBjb25zdCBjbG9zZSA9IGZpbmRDb250cm9sKGZyYW1lLCAiY2xvc2UiKTsKCiAgaWYgKG1pbmltaXplPy5wYXJlbnRFbGVtZW50KSB7CiAgICBtaW5pbWl6ZS5pbnNlcnRBZGphY2VudEVsZW1lbnQoCiAgICAgICJhZnRlcmVuZCIsCiAgICAgIHRvZ2dsZSwKICAgICk7CiAgfSBlbHNlIGlmIChjbG9zZT8ucGFyZW50RWxlbWVudCkgewogICAgY2xvc2UucGFyZW50RWxlbWVudC5pbnNlcnRCZWZvcmUoCiAgICAgIHRvZ2dsZSwKICAgICAgY2xvc2UsCiAgICApOwogIH0gZWxzZSB7CiAgICB0b2dnbGUuZGF0YXNldC5zZXBNb2RhbFRvZ2dsZUZsb2F0aW5nID0gInRydWUiOwogICAgZnJhbWUuYXBwZW5kQ2hpbGQodG9nZ2xlKTsKICB9CgogIHJldHVybiB0b2dnbGU7Cn0KCmZ1bmN0aW9uIG1hbmFnZURpYWxvZyhkaWFsb2c6IEhUTUxFbGVtZW50KSB7CiAgY29uc3QgcHJldmlvdXMgPSBtYW5hZ2VkLmdldChkaWFsb2cpOwoKICBpZiAoCiAgICBwcmV2aW91cyAmJgogICAgcHJldmlvdXMudG9nZ2xlLmlzQ29ubmVjdGVkICYmCiAgICBwcmV2aW91cy5mcmFtZS5pc0Nvbm5lY3RlZAogICkgewogICAgcmV0dXJuOwogIH0KCiAgY29uc3QgZnJhbWUgPSByZXNvbHZlRnJhbWUoZGlhbG9nKTsKICBjb25zdCB0b2dnbGUgPSBjcmVhdGVUb2dnbGUoZGlhbG9nLCBmcmFtZSk7CgogIGRpYWxvZy5kYXRhc2V0LnNlcE1hbmFnZWRNb2RhbCA9ICJ0cnVlIjsKICBmcmFtZS5kYXRhc2V0LnNlcE1hbmFnZWRNb2RhbEZyYW1lID0gInRydWUiOwoKICBjb25zdCBzdGF0ZTogTWFuYWdlZE1vZGFsU3RhdGUgPSB7CiAgICBkaWFsb2csCiAgICBmcmFtZSwKICAgIHRvZ2dsZSwKICAgIHJlc3RvcmVkT25jZTogZmFsc2UsCiAgICBzYXZlZFdpZHRoOiBudWxsLAogICAgc2F2ZWRIZWlnaHQ6IG51bGwsCiAgfTsKCiAgbWFuYWdlZC5zZXQoZGlhbG9nLCBzdGF0ZSk7CgogIHRvZ2dsZS5hZGRFdmVudExpc3RlbmVyKCJjbGljayIsIChldmVudCkgPT4gewogICAgZXZlbnQucHJldmVudERlZmF1bHQoKTsKICAgIGV2ZW50LnN0b3BQcm9wYWdhdGlvbigpOwoKICAgIGNvbnN0IGlzTWF4aW1pemVkID0KICAgICAgZGlhbG9nLmRhdGFzZXQuc2VwTW9kYWxNYXhpbWl6ZWQgPT09ICJ0cnVlIjsKCiAgICBpZiAoIWlzTWF4aW1pemVkKSB7CiAgICAgIGNvbnN0IHJlY3QgPQogICAgICAgIGZyYW1lLmdldEJvdW5kaW5nQ2xpZW50UmVjdCgpOwoKICAgICAgc3RhdGUuc2F2ZWRXaWR0aCA9IGAke01hdGgucm91bmQocmVjdC53aWR0aCl9cHhgOwogICAgICBzdGF0ZS5zYXZlZEhlaWdodCA9IGAke01hdGgucm91bmQocmVjdC5oZWlnaHQpfXB4YDsKCiAgICAgIHNldE1heGltaXplZChzdGF0ZSwgdHJ1ZSk7CiAgICAgIHJldHVybjsKICAgIH0KCiAgICBzZXRNYXhpbWl6ZWQoc3RhdGUsIGZhbHNlKTsKICB9KTsKCiAgLy8gRXZlcnkgbW9kYWwgb3BlbnMgbWF4aW1pemVkIGJ5IGRlZmF1bHQuCiAgc2V0TWF4aW1pemVkKHN0YXRlLCB0cnVlKTsKfQoKZnVuY3Rpb24gc2NhbkZvck1vZGFscygpIHsKICBjb25zdCBkaWFsb2dzID0gQXJyYXkuZnJvbSgKICAgIGRvY3VtZW50LnF1ZXJ5U2VsZWN0b3JBbGw8SFRNTEVsZW1lbnQ+KAogICAgICAnW3JvbGU9ImRpYWxvZyJdLCBbYXJpYS1tb2RhbD0idHJ1ZSJdJywKICAgICksCiAgKTsKCiAgZGlhbG9ncy5mb3JFYWNoKChkaWFsb2cpID0+IHsKICAgIC8vIElmIGFuIGFyaWEtbW9kYWwgbm9kZSBpcyBpbnNpZGUgYSByb2xlPWRpYWxvZyBwYXJlbnQsIG1hbmFnZSBvbmx5CiAgICAvLyB0aGUgb3V0ZXIgbW9kYWwgcm9vdCBvbmNlLgogICAgY29uc3QgcGFyZW50RGlhbG9nID0gZGlhbG9nLnBhcmVudEVsZW1lbnQ/LmNsb3Nlc3Q8SFRNTEVsZW1lbnQ+KAogICAgICAnW3JvbGU9ImRpYWxvZyJdLCBbYXJpYS1tb2RhbD0idHJ1ZSJdJywKICAgICk7CgogICAgaWYgKHBhcmVudERpYWxvZykgewogICAgICByZXR1cm47CiAgICB9CgogICAgbWFuYWdlRGlhbG9nKGRpYWxvZyk7CiAgfSk7Cn0KCmV4cG9ydCBmdW5jdGlvbiBQb3J0YWxNb2RhbFZpZXdwb3J0TWFuYWdlcigpIHsKICB1c2VFZmZlY3QoKCkgPT4gewogICAgc2NhbkZvck1vZGFscygpOwoKICAgIGNvbnN0IG9ic2VydmVyID0gbmV3IE11dGF0aW9uT2JzZXJ2ZXIoKCkgPT4gewogICAgICBzY2FuRm9yTW9kYWxzKCk7CiAgICB9KTsKCiAgICBvYnNlcnZlci5vYnNlcnZlKGRvY3VtZW50LmJvZHksIHsKICAgICAgY2hpbGRMaXN0OiB0cnVlLAogICAgICBzdWJ0cmVlOiB0cnVlLAogICAgfSk7CgogICAgcmV0dXJuICgpID0+IHsKICAgICAgb2JzZXJ2ZXIuZGlzY29ubmVjdCgpOwogICAgfTsKICB9LCBbXSk7CgogIHJldHVybiBudWxsOwp9Cg==").decode("utf-8"),
    encoding="utf-8",
)

import_line = (
    'import { PortalModalViewportManager } '
    'from "@/components/portal/portal-modal-viewport-manager";'
)

if import_line not in layout:
    anchor = (
        'import { PortalResponsiveRightSidebar } '
        'from "@/components/portal/portal-responsive-right-sidebar";'
    )

    if anchor not in layout:
        raise SystemExit(
            "Could not find the expected Portal layout import anchor. "
            "No layout changes were written."
        )

    layout = layout.replace(
        anchor,
        anchor + "\n" + import_line,
        1,
    )

mount = "            <PortalModalViewportManager />"

if mount not in layout:
    anchor = "            <PortalSessionGuard />"

    if anchor not in layout:
        raise SystemExit(
            "Could not find PortalSessionGuard mount anchor. "
            "No layout changes were written."
        )

    layout = layout.replace(
        anchor,
        anchor + "\n\n" + mount,
        1,
    )

# ------------------------------------------------------------------
# 3. Append modal-specific CSS exactly once.
# ------------------------------------------------------------------
marker = "PORTAL MODALS — UNIFIED BORDER + MAXIMIZE / RESTORE"
addition = base64.b64decode("CgovKiA9PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT0KICAgUE9SVEFMIE1PREFMUyDigJQgVU5JRklFRCBCT1JERVIgKyBNQVhJTUlaRSAvIFJFU1RPUkUKICAgPT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09CiAgIFRoaXMgbGF5ZXIgYWZmZWN0cyBvbmx5IHJlYWwgc2VtYW50aWMgbW9kYWxzIG1hbmFnZWQgYnkKICAgUG9ydGFsTW9kYWxWaWV3cG9ydE1hbmFnZXIuIEl0IGRvZXMgbm90IGluZmVyIG9yZGluYXJ5IHBhbmVscy4KICAgPT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09ICovCgovKgogKiBUaGUgbW9kYWwgZnJhbWUgbm93IHVzZXMgRVhBQ1RMWSB0aGUgc2FtZSBib3JkZXIgZmFtaWx5IGFzIHRoZQogKiBjYW5vbmljYWwgdW5pZmllZCBidXR0b25zLiBUaGlzIG92ZXJyaWRlcyBmZWF0dXJlLXNwZWNpZmljIGlubGluZQogKiBhY2NlbnQgYm9yZGVycyBzdWNoIGFzIFNlcE1vZGFsRnJhbWUncyBhY2NlbnQgY29sb3VyLgogKi8KYm9keS5wb3J0YWwtc2tpbi1zY29wZQogIFtkYXRhLXNlcC1tYW5hZ2VkLW1vZGFsLWZyYW1lPSJ0cnVlIl0gewogIGJvcmRlci13aWR0aDogMXB4ICFpbXBvcnRhbnQ7CiAgYm9yZGVyLXN0eWxlOiBzb2xpZCAhaW1wb3J0YW50OwogIGJvcmRlci1jb2xvcjoKICAgIGNvbG9yLW1peCgKICAgICAgaW4gc3JnYiwKICAgICAgcmdiKHZhcigtLXNlcC1jb2xvdXItNjA0ODJlKSkgNTAlLAogICAgICB0cmFuc3BhcmVudAogICAgKSAhaW1wb3J0YW50OwogIGJvcmRlci1yYWRpdXM6IDAgIWltcG9ydGFudDsKfQoKLyogSWYgYSBtb2RhbCBsaXZlcyBpbnNpZGUgdGhlIHNoZWxsLCB1c2UgdGhlIGV4YWN0IHNoYXJlZCB0b2tlbi4gKi8KW2RhdGEtcG9ydGFsLXNoZWxsXQogIFtkYXRhLXNlcC1tYW5hZ2VkLW1vZGFsLWZyYW1lPSJ0cnVlIl0gewogIGJvcmRlci1jb2xvcjoKICAgIHZhcigtLXNlcC11bmlmaWVkLWNvbnRyb2wtYm9yZGVyKSAhaW1wb3J0YW50Owp9CgovKgogKiBNYXhpbWlzZSB0aGUgZXhpc3RpbmcgbW9kYWwgb3ZlcmxheS9mcmFtZSB3aXRob3V0IGNoYW5naW5nIGl0cyBKU1guCiAqIFRoZSA4cHggYnJlYXRoaW5nIGVkZ2UgZm9sbG93cyB0aGUgZXhpc3RpbmcgbmVhci1mdWxsc2NyZWVuIHBvcnRhbAogKiBtb2RhbCBsYW5ndWFnZSB3aGlsZSB1c2luZyB0aGUgZW50aXJlIGF2YWlsYWJsZSB2aWV3cG9ydC4KICovCmJvZHkucG9ydGFsLXNraW4tc2NvcGUKICBbZGF0YS1zZXAtbWFuYWdlZC1tb2RhbD0idHJ1ZSJdW2RhdGEtc2VwLW1vZGFsLW1heGltaXplZD0idHJ1ZSJdIHsKICBhbGlnbi1pdGVtczogc3RyZXRjaCAhaW1wb3J0YW50OwogIGp1c3RpZnktY29udGVudDogc3RyZXRjaCAhaW1wb3J0YW50OwogIHBhZGRpbmc6IDhweCAhaW1wb3J0YW50Owp9Cgpib2R5LnBvcnRhbC1za2luLXNjb3BlCiAgW2RhdGEtc2VwLW1hbmFnZWQtbW9kYWwtZnJhbWU9InRydWUiXVtkYXRhLXNlcC1tb2RhbC1tYXhpbWl6ZWQ9InRydWUiXSB7CiAgd2lkdGg6IDEwMCUgIWltcG9ydGFudDsKICBoZWlnaHQ6IDEwMCUgIWltcG9ydGFudDsKICBtaW4td2lkdGg6IDAgIWltcG9ydGFudDsKICBtaW4taGVpZ2h0OiAwICFpbXBvcnRhbnQ7CiAgbWF4LXdpZHRoOiBub25lICFpbXBvcnRhbnQ7CiAgbWF4LWhlaWdodDogbm9uZSAhaW1wb3J0YW50OwogIG1hcmdpbjogMCAhaW1wb3J0YW50Owp9CgovKgogKiBTb21lIHNlbWFudGljIGRpYWxvZ3MgYXJlIHRoZW1zZWx2ZXMgdGhlIHZpc2libGUgZnJhbWUgcmF0aGVyIHRoYW4KICogYW4gb3ZlcmxheSBjb250YWluaW5nIGEgZnJhbWUuCiAqLwpib2R5LnBvcnRhbC1za2luLXNjb3BlCiAgW2RhdGEtc2VwLW1hbmFnZWQtbW9kYWw9InRydWUiXVtkYXRhLXNlcC1tYW5hZ2VkLW1vZGFsLWZyYW1lPSJ0cnVlIl0KICBbZGF0YS1zZXAtbW9kYWwtbWF4aW1pemVkPSJ0cnVlIl0gewogIHBvc2l0aW9uOiBmaXhlZCAhaW1wb3J0YW50OwogIGluc2V0OiA4cHggIWltcG9ydGFudDsKICB3aWR0aDogYXV0byAhaW1wb3J0YW50OwogIGhlaWdodDogYXV0byAhaW1wb3J0YW50OwogIG1heC13aWR0aDogbm9uZSAhaW1wb3J0YW50OwogIG1heC1oZWlnaHQ6IG5vbmUgIWltcG9ydGFudDsKfQoKLyogQ2Fub25pY2FsIG1heGltaXNlIC8gcmVzdG9yZSBjb250cm9sLiAqLwpib2R5LnBvcnRhbC1za2luLXNjb3BlCiAgLnNlcC1tb2RhbC1zaXplLXRvZ2dsZSB7CiAgZGlzcGxheTogaW5saW5lLWZsZXg7CiAgZmxleDogMCAwIGF1dG87CiAgYWxpZ24taXRlbXM6IGNlbnRlcjsKICBqdXN0aWZ5LWNvbnRlbnQ6IGNlbnRlcjsKICB3aWR0aDogMzZweDsKICBoZWlnaHQ6IDM2cHg7CiAgcGFkZGluZzogMDsKICBib3JkZXI6IDFweCBzb2xpZAogICAgY29sb3ItbWl4KAogICAgICBpbiBzcmdiLAogICAgICByZ2IodmFyKC0tc2VwLWNvbG91ci02MDQ4MmUpKSA1MCUsCiAgICAgIHRyYW5zcGFyZW50CiAgICApICFpbXBvcnRhbnQ7CiAgYm9yZGVyLXJhZGl1czogMCAhaW1wb3J0YW50OwogIGJhY2tncm91bmQ6IHJnYih2YXIoLS1zZXAtY29sb3VyLTE4MTEwZCkpICFpbXBvcnRhbnQ7CiAgY29sb3I6IHJnYih2YXIoLS1zZXAtY29sb3VyLWJjYTI3YikpICFpbXBvcnRhbnQ7CiAgZm9udC1mYW1pbHk6IEdlb3JnaWEsIHNlcmlmOwogIGZvbnQtc2l6ZTogMTVweDsKICBsaW5lLWhlaWdodDogMTsKICBsZXR0ZXItc3BhY2luZzogMDsKICBjdXJzb3I6IHBvaW50ZXI7CiAgei1pbmRleDogODA7CiAgdHJhbnNpdGlvbjoKICAgIGJvcmRlci1jb2xvciAxNTBtcyBlYXNlLAogICAgYmFja2dyb3VuZC1jb2xvciAxNTBtcyBlYXNlLAogICAgY29sb3IgMTUwbXMgZWFzZTsKfQoKYm9keS5wb3J0YWwtc2tpbi1zY29wZQogIC5zZXAtbW9kYWwtc2l6ZS10b2dnbGU6aG92ZXIgewogIGJvcmRlci1jb2xvcjoKICAgIHJnYih2YXIoLS1zZXAtY29sb3VyLTliNzQ0NikpICFpbXBvcnRhbnQ7CiAgYmFja2dyb3VuZDoKICAgIHJnYih2YXIoLS1zZXAtY29sb3VyLTJiMWQxMikpICFpbXBvcnRhbnQ7CiAgY29sb3I6CiAgICByZ2IodmFyKC0tc2VwLWNvbG91ci1lY2QyYTMpKSAhaW1wb3J0YW50Owp9Cgpib2R5LnBvcnRhbC1za2luLXNjb3BlCiAgLnNlcC1tb2RhbC1zaXplLXRvZ2dsZTpmb2N1cy12aXNpYmxlIHsKICBvdXRsaW5lOiAxcHggc29saWQKICAgIHJnYih2YXIoLS1zZXAtY29sb3VyLTliNzQ0NikpOwogIG91dGxpbmUtb2Zmc2V0OiAycHg7Cn0KCi8qCiAqIE9ubHkgbW9kYWxzIHdpdGggbm8gZXhpc3RpbmcgbWluaW1pc2UvY2xvc2UgY29udHJvbCBuZWVkIGEgZmxvYXRpbmcKICogcGxhY2VtZW50LiBOb3JtYWwgbW9kYWxzIGluaGVyaXQgdGhlaXIgZXhpc3RpbmcgaGVhZGVyIGZsZXggbGF5b3V0LgogKi8KYm9keS5wb3J0YWwtc2tpbi1zY29wZQogIC5zZXAtbW9kYWwtc2l6ZS10b2dnbGVbZGF0YS1zZXAtbW9kYWwtdG9nZ2xlLWZsb2F0aW5nPSJ0cnVlIl0gewogIHBvc2l0aW9uOiBhYnNvbHV0ZTsKICB0b3A6IDEwcHg7CiAgcmlnaHQ6IDEwcHg7Cn0KCi8qCiAqIEEgbWF4aW1pc2VkIG1vZGFsIGZyYW1lIG11c3QgYWxsb3cgaXRzIG93biBwcmUtZXhpc3Rpbmcgc2Nyb2xsL2ZsZXgKICogcmVnaW9ucyB0byBjYWxjdWxhdGUgaGVpZ2h0IGNvcnJlY3RseS4KICovCmJvZHkucG9ydGFsLXNraW4tc2NvcGUKICBbZGF0YS1zZXAtbWFuYWdlZC1tb2RhbC1mcmFtZT0idHJ1ZSJdW2RhdGEtc2VwLW1vZGFsLW1heGltaXplZD0idHJ1ZSJdCiAgPiAqIHsKICBtaW4taGVpZ2h0OiAwOwp9CgpAbWVkaWEgKHByZWZlcnMtcmVkdWNlZC1tb3Rpb246IHJlZHVjZSkgewogIGJvZHkucG9ydGFsLXNraW4tc2NvcGUKICAgIC5zZXAtbW9kYWwtc2l6ZS10b2dnbGUgewogICAgdHJhbnNpdGlvbjogbm9uZSAhaW1wb3J0YW50OwogIH0KfQo=").decode("utf-8")

if marker not in css:
    css = css + addition

layout_path.write_text(layout, encoding="utf-8")
css_path.write_text(css, encoding="utf-8")

print("SUCCESS")
print("")
print("Portal modal standardisation applied.")
print("")
print("Changed/created:")
print("  app/(portal)/layout.tsx")
print("  components/sepulchria/sep-ui-unified.css")
print("  components/portal/portal-modal-viewport-manager.tsx")
print("")
print("Behaviour:")
print("  - actual semantic portal modals open maximized")
print("  - modal frame border now matches unified button border")
print("  - maximize/restore control is added centrally")
print("  - placed after Minimize when present, otherwise before Close")
print("  - restore returns to original size")
print("  - after manual resize, maximize remembers resized dimensions")
print("  - existing modal close/minimize/business logic is untouched")
print("")
print("Run: npm run build")
