from pathlib import Path
import subprocess, sys

ROOT = Path.cwd()
EXPECTED_PREFIX = "74fc1f6"

def fail(message):
    print(f"\nERROR: {message}\n")
    sys.exit(1)

head = subprocess.check_output(['git','rev-parse','HEAD'], cwd=ROOT, text=True).strip()
if not head.startswith(EXPECTED_PREFIX):
    fail(f"This patch targets {EXPECTED_PREFIX}, but HEAD is {head}.")

actions_path = ROOT / "app/(portal)/admin/characters/actions.ts"
music_path = ROOT / "app/(portal)/admin/characters/music-actions.ts"
helper_path = ROOT / "lib/premium-features/notifications.ts"
for p in (actions_path, music_path):
    if not p.exists(): fail(f'Missing {p.relative_to(ROOT)}')
if helper_path.exists(): fail('Premium feature notification helper already exists; inspect before applying.')
actions = actions_path.read_text(encoding='utf-8')
music = music_path.read_text(encoding='utf-8')

def repl(text, old, new, label):
    count = text.count(old)
    if count != 1:
        fail(f'{label}: expected 1 exact anchor, found {count}.')
    return text.replace(old, new, 1)

actions = repl(actions, 'import { createClient } from "@/lib/supabase/server";', 'import { createClient } from "@/lib/supabase/server";\nimport { createPremiumFeatureGrantNotification } from "@/lib/premium-features/notifications";', 'character actions notification import')
actions = repl(actions, 'type CharacterFeatureSource =\n  (typeof CHARACTER_FEATURE_SOURCES)[number];\n\n\nexport async function setCharacterPortalSkinEntitlement', 'type CharacterFeatureSource =\n  (typeof CHARACTER_FEATURE_SOURCES)[number];\n\nconst CHARACTER_FEATURE_NAMES: Record<\n  CharacterFeatureKey,\n  string\n> = {\n  private_chat: "Private Chats",\n  friend_list: "Friend List",\n};\n\n\nexport async function setCharacterPortalSkinEntitlement', 'feature display-name map')
actions = repl(actions, '  if (skin.is_default === true) {\n    throw new Error(\n      "The default Sepulchria skin does not require premium access.",\n    );\n  }\n\n  const now =\n    new Date().toISOString();', '  if (skin.is_default === true) {\n    throw new Error(\n      "The default Sepulchria skin does not require premium access.",\n    );\n  }\n\n  const {\n    data: previousSkinEntitlement,\n    error: previousSkinEntitlementError,\n  } = await admin\n    .from(\n      "user_portal_skin_entitlements",\n    )\n    .select("enabled")\n    .eq(\n      "user_id",\n      character.user_id,\n    )\n    .eq("skin_id", skinId)\n    .maybeSingle();\n\n  if (previousSkinEntitlementError) {\n    throw new Error(\n      `Unable to check existing portal skin access: ${previousSkinEntitlementError.message}`,\n    );\n  }\n\n  const wasSkinEnabled =\n    previousSkinEntitlement?.enabled ===\n    true;\n\n  const now =\n    new Date().toISOString();', 'portal skin previous entitlement lookup')
actions = repl(actions, '  if (!enabled) {\n    const {\n      data: preference,\n      error: preferenceError,\n    } = await admin', '  if (\n    enabled &&\n    !wasSkinEnabled\n  ) {\n    try {\n      await createPremiumFeatureGrantNotification({\n        characterId,\n        createdBy: staff.userId,\n        title: `Premium feature unlocked: ${skin.name}`,\n        body:\n          `You have unlocked the ${skin.name} portal skin. You can select it from Appearance.`,\n        href: "/appearance",\n      });\n    } catch (notificationError) {\n      console.error(\n        "Portal skin was granted, but its notification could not be created:",\n        notificationError,\n      );\n    }\n  }\n\n  if (!enabled) {\n    const {\n      data: preference,\n      error: preferenceError,\n    } = await admin', 'portal skin grant notification')
actions = repl(actions, '  revalidatePath(\n    `/admin/characters/${characterId}`,\n  );\n  revalidatePath("/appearance");\n}', '  revalidatePath(\n    `/admin/characters/${characterId}`,\n  );\n  revalidatePath("/appearance");\n  revalidatePath("/", "layout");\n}', 'portal skin notification revalidation')
actions = repl(actions, '  if (characterError || !character) {\n    throw new Error(\n      characterError?.message ?? "Character not found.",\n    );\n  }\n\n  const now = new Date().toISOString();\n\n  const { error } = await admin', '  if (characterError || !character) {\n    throw new Error(\n      characterError?.message ?? "Character not found.",\n    );\n  }\n\n  const {\n    data: previousFeatureEntitlement,\n    error: previousFeatureEntitlementError,\n  } = await admin\n    .from(\n      "character_feature_entitlements",\n    )\n    .select("enabled")\n    .eq("character_id", characterId)\n    .eq(\n      "feature_key",\n      featureKeyRaw,\n    )\n    .maybeSingle();\n\n  if (previousFeatureEntitlementError) {\n    throw new Error(\n      `Unable to check existing feature access: ${previousFeatureEntitlementError.message}`,\n    );\n  }\n\n  const wasFeatureEnabled =\n    previousFeatureEntitlement?.enabled ===\n    true;\n\n  const now = new Date().toISOString();\n\n  const { error } = await admin', 'feature previous entitlement lookup')
actions = repl(actions, '  if (error) {\n    throw new Error(\n      `Unable to update feature access: ${error.message}`,\n    );\n  }\n\n  revalidatePath(`/admin/characters/${characterId}`);', '  if (error) {\n    throw new Error(\n      `Unable to update feature access: ${error.message}`,\n    );\n  }\n\n  if (\n    enabled &&\n    !wasFeatureEnabled\n  ) {\n    const featureName =\n      CHARACTER_FEATURE_NAMES[\n        featureKeyRaw as CharacterFeatureKey\n      ];\n\n    try {\n      await createPremiumFeatureGrantNotification({\n        characterId,\n        createdBy: staff.userId,\n        title:\n          `Premium feature unlocked: ${featureName}`,\n        body:\n          `You now have access to ${featureName}.`,\n        href:\n          featureKeyRaw ===\n          "friend_list"\n            ? "/friends"\n            : "/game",\n      });\n    } catch (notificationError) {\n      console.error(\n        "Premium feature was granted, but its notification could not be created:",\n        notificationError,\n      );\n    }\n  }\n\n  revalidatePath(`/admin/characters/${characterId}`);\n  revalidatePath("/", "layout");', 'feature grant notification')
music = repl(music, 'import { createAdminClient } from "@/lib/supabase/admin";', 'import { createAdminClient } from "@/lib/supabase/admin";\nimport { createPremiumFeatureGrantNotification } from "@/lib/premium-features/notifications";', 'music notification import')
music = repl(music, '  await requireStaffCapability(\n    "character_economy",\n  );', '  const staff =\n    await requireStaffCapability(\n      "character_economy",\n    );', 'music staff session capture')
music = repl(music, '  const admin = createAdminClient();\n\n  const { error } = await admin\n    .from(\n      "character_music_entitlements",\n    )\n    .upsert(', '  const admin = createAdminClient();\n\n  const [\n    previousEntitlementResult,\n    trackResult,\n  ] = await Promise.all([\n    admin\n      .from(\n        "character_music_entitlements",\n      )\n      .select("enabled")\n      .eq(\n        "character_id",\n        characterId,\n      )\n      .eq(\n        "music_track_id",\n        musicTrackId,\n      )\n      .maybeSingle(),\n\n    admin\n      .from("music_tracks")\n      .select("id, name")\n      .eq("id", musicTrackId)\n      .maybeSingle(),\n  ]);\n\n  if (\n    previousEntitlementResult.error\n  ) {\n    throw new Error(\n      `Unable to check existing music ownership: ${previousEntitlementResult.error.message}`,\n    );\n  }\n\n  if (\n    trackResult.error ||\n    !trackResult.data\n  ) {\n    throw new Error(\n      `Unable to load music track: ${\n        trackResult.error?.message ??\n        "Track not found."\n      }`,\n    );\n  }\n\n  const wasMusicEnabled =\n    previousEntitlementResult.data\n      ?.enabled === true;\n\n  const musicTrack =\n    trackResult.data;\n\n  const { error } = await admin\n    .from(\n      "character_music_entitlements",\n    )\n    .upsert(', 'music previous entitlement and track lookup')
music = repl(music, '  if (!enabled) {\n    await admin\n      .from(\n        "character_music_preferences",\n      )', '  if (\n    enabled &&\n    !wasMusicEnabled\n  ) {\n    try {\n      await createPremiumFeatureGrantNotification({\n        characterId,\n        createdBy: staff.userId,\n        title:\n          `Premium feature unlocked: ${musicTrack.name}`,\n        body:\n          `You have unlocked the music track ${musicTrack.name}. You can select it from the music controls while in a location.`,\n        href: "/game",\n      });\n    } catch (notificationError) {\n      console.error(\n        "Music ownership was granted, but its notification could not be created:",\n        notificationError,\n      );\n    }\n  }\n\n  if (!enabled) {\n    await admin\n      .from(\n        "character_music_preferences",\n      )', 'music grant notification')
music = repl(music, '  revalidatePath(\n    `/admin/characters/${characterId}/premium-features`,\n  );\n  revalidatePath("/game");\n}', '  revalidatePath(\n    `/admin/characters/${characterId}/premium-features`,\n  );\n  revalidatePath("/game");\n  revalidatePath("/", "layout");\n}', 'music notification revalidation')

helper_path.parent.mkdir(parents=True, exist_ok=True)
actions_path.write_text(actions, encoding='utf-8')
music_path.write_text(music, encoding='utf-8')
helper_path.write_text('import "server-only";\n\nimport { createAdminClient } from "@/lib/supabase/admin";\n\ntype PremiumFeatureNotificationInput = {\n  characterId: string;\n  createdBy: string;\n  title: string;\n  body: string;\n  href?: string | null;\n};\n\nfunction thirtyDaysFromNow() {\n  const date = new Date();\n  date.setUTCDate(date.getUTCDate() + 30);\n  return date.toISOString();\n}\n\nexport async function createPremiumFeatureGrantNotification({\n  characterId,\n  createdBy,\n  title,\n  body,\n  href = null,\n}: PremiumFeatureNotificationInput) {\n  const admin = createAdminClient();\n  const now = new Date().toISOString();\n\n  const {\n    data: notification,\n    error: notificationError,\n  } = await admin\n    .from("notifications")\n    .insert({\n      type: "reward",\n      title,\n      body,\n      href,\n      starts_at: now,\n      expires_at: thirtyDaysFromNow(),\n      expires_game_at: null,\n      created_by: createdBy,\n      is_automatic: true,\n      staff_overridden: false,\n      is_active: true,\n    })\n    .select("id")\n    .single();\n\n  if (notificationError || !notification) {\n    throw new Error(\n      `Unable to create premium feature notification: ${\n        notificationError?.message ?? "Unknown error"\n      }`,\n    );\n  }\n\n  const { error: targetError } = await admin\n    .from("notification_targets")\n    .insert({\n      notification_id: notification.id,\n      target_type: "character",\n      target_id: characterId,\n    });\n\n  if (targetError) {\n    await admin\n      .from("notifications")\n      .delete()\n      .eq("id", notification.id);\n\n    throw new Error(\n      `Unable to target premium feature notification: ${targetError.message}`,\n    );\n  }\n}\n', encoding='utf-8')

print('Applied successfully:')
print('  general premium feature grants -> character notification')
print('  premium portal skin grants -> character notification')
print('  premium music grants -> character notification')
print('  already-enabled + Save -> no duplicate notification')
print('\nRun npm run build.')