from pathlib import Path
import base64
import re

root = Path.cwd()
admin_page = root / "app/(portal)/admin/character-audit/page.tsx"
api_route = root / "app/api/character-audit/route.ts"

for required in (admin_page, api_route):
    if not required.exists():
        raise SystemExit(
            f"Could not find {required.relative_to(root)}. "
            "Run this from the sepulchria-portal repository root."
        )

payloads = {'lib/audit/character-audit-display.ts': 'ZXhwb3J0IHR5cGUgQ2hhcmFjdGVyQXVkaXREaXNwbGF5QmFzZSA9IHsKICBpZDogc3RyaW5nOwogIGV2ZW50X3R5cGU6IHN0cmluZzsKICBlbnRpdHlfdHlwZTogc3RyaW5nOwogIGVudGl0eV9pZDogc3RyaW5nIHwgbnVsbDsKICBvcGVyYXRpb246IHN0cmluZzsKICBhY3Rvcl90eXBlOiAicGxheWVyIiB8ICJzdGFmZiIgfCAic3lzdGVtIjsKICBhY3Rvcl9sYWJlbDogc3RyaW5nIHwgbnVsbDsKICBhY3Rvcl9zdGFmZl9yb2xlOiBzdHJpbmcgfCBudWxsOwogIHNvdXJjZTogc3RyaW5nOwogIGNoYW5nZWRfZmllbGRzOiBzdHJpbmdbXTsKICBvbGRfdmFsdWVzOiBSZWNvcmQ8c3RyaW5nLCB1bmtub3duPiB8IG51bGw7CiAgbmV3X3ZhbHVlczogUmVjb3JkPHN0cmluZywgdW5rbm93bj4gfCBudWxsOwogIG1ldGFkYXRhOiBSZWNvcmQ8c3RyaW5nLCB1bmtub3duPiB8IG51bGw7CiAgY3JlYXRlZF9hdDogc3RyaW5nOwogIGl0ZW1fbmFtZT86IHN0cmluZyB8IG51bGw7Cn07CgpleHBvcnQgY29uc3QgVEVDSE5JQ0FMX0FVRElUX0ZJRUxEUyA9IG5ldyBTZXQoWwogICJpZCIsInVzZXJfaWQiLCJhY3Rvcl91c2VyX2lkIiwiY2hhcmFjdGVyX2lkIiwiY3JlYXRlZF9hdCIsInVwZGF0ZWRfYXQiLAogICJzb3VyY2VfaWQiLCJzb3VyY2VfdHlwZSIsInRyYW5zYWN0aW9uX3R5cGUiLCJpdGVtX2lkIiwKXSk7CgpleHBvcnQgZnVuY3Rpb24gZm9ybWF0QXVkaXREYXRlVGltZSh2YWx1ZTogc3RyaW5nKSB7CiAgY29uc3QgZGF0ZSA9IG5ldyBEYXRlKHZhbHVlKTsKICBpZiAoTnVtYmVyLmlzTmFOKGRhdGUuZ2V0VGltZSgpKSkgcmV0dXJuIHZhbHVlOwogIHJldHVybiBuZXcgSW50bC5EYXRlVGltZUZvcm1hdCgiZW4tR0IiLCB7CiAgICBkYXRlU3R5bGU6ICJtZWRpdW0iLAogICAgdGltZVN0eWxlOiAic2hvcnQiLAogIH0pLmZvcm1hdChkYXRlKTsKfQoKZXhwb3J0IGZ1bmN0aW9uIGh1bWFuQXVkaXRMYWJlbCh2YWx1ZTogc3RyaW5nKSB7CiAgcmV0dXJuIHZhbHVlLnJlcGxhY2VBbGwoIl8iLCAiICIpLnJlcGxhY2UoL1xiXHcvZywgKGxldHRlcikgPT4gbGV0dGVyLnRvVXBwZXJDYXNlKCkpOwp9CgpleHBvcnQgZnVuY3Rpb24gYXVkaXREaXNwbGF5VmFsdWUodmFsdWU6IHVua25vd24pOiBzdHJpbmcgewogIGlmICh2YWx1ZSA9PT0gbnVsbCB8fCB2YWx1ZSA9PT0gdW5kZWZpbmVkIHx8IHZhbHVlID09PSAiIikgcmV0dXJuICLigJQiOwogIGlmICh0eXBlb2YgdmFsdWUgPT09ICJib29sZWFuIikgcmV0dXJuIHZhbHVlID8gIlllcyIgOiAiTm8iOwogIGlmICh0eXBlb2YgdmFsdWUgPT09ICJudW1iZXIiKSByZXR1cm4gbmV3IEludGwuTnVtYmVyRm9ybWF0KCJlbi1HQiIpLmZvcm1hdCh2YWx1ZSk7CiAgaWYgKHR5cGVvZiB2YWx1ZSA9PT0gInN0cmluZyIpIHJldHVybiB2YWx1ZS5yZXBsYWNlQWxsKCJfIiwgIiAiKTsKICBpZiAoQXJyYXkuaXNBcnJheSh2YWx1ZSkpIHJldHVybiB2YWx1ZS5tYXAoYXVkaXREaXNwbGF5VmFsdWUpLmpvaW4oIiwgIik7CiAgcmV0dXJuIEpTT04uc3RyaW5naWZ5KHZhbHVlKTsKfQoKZXhwb3J0IGZ1bmN0aW9uIHByZXR0eUF1ZGl0VmFsdWUodmFsdWU6IHVua25vd24pIHsKICBpZiAodmFsdWUgPT09IG51bGwgfHwgdmFsdWUgPT09IHVuZGVmaW5lZCkgcmV0dXJuICLigJQiOwogIGlmICh0eXBlb2YgdmFsdWUgPT09ICJzdHJpbmciKSByZXR1cm4gdmFsdWU7CiAgcmV0dXJuIEpTT04uc3RyaW5naWZ5KHZhbHVlLCBudWxsLCAyKTsKfQoKZXhwb3J0IGZ1bmN0aW9uIG1lYW5pbmdmdWxBdWRpdEVudHJpZXModmFsdWU6IFJlY29yZDxzdHJpbmcsIHVua25vd24+IHwgbnVsbCkgewogIGlmICghdmFsdWUpIHJldHVybiBbXTsKICByZXR1cm4gT2JqZWN0LmVudHJpZXModmFsdWUpLmZpbHRlcigKICAgIChba2V5LCBlbnRyeVZhbHVlXSkgPT4KICAgICAgIVRFQ0hOSUNBTF9BVURJVF9GSUVMRFMuaGFzKGtleSkgJiYKICAgICAgZW50cnlWYWx1ZSAhPT0gbnVsbCAmJgogICAgICBlbnRyeVZhbHVlICE9PSB1bmRlZmluZWQgJiYKICAgICAgZW50cnlWYWx1ZSAhPT0gIiIsCiAgKTsKfQoKZnVuY3Rpb24gcXR5KHJvdzogQ2hhcmFjdGVyQXVkaXREaXNwbGF5QmFzZSwgc2lkZTogImJlZm9yZSIgfCAiYWZ0ZXIiKSB7CiAgY29uc3Qgc291cmNlID0gc2lkZSA9PT0gImJlZm9yZSIgPyByb3cub2xkX3ZhbHVlcyA6IHJvdy5uZXdfdmFsdWVzOwogIGNvbnN0IHJhdyA9IHNvdXJjZT8ucXVhbnRpdHk7CiAgcmV0dXJuIHR5cGVvZiByYXcgPT09ICJudW1iZXIiCiAgICA/IHJhdwogICAgOiByYXcgIT09IG51bGwgJiYgcmF3ICE9PSB1bmRlZmluZWQgJiYgTnVtYmVyLmlzRmluaXRlKE51bWJlcihyYXcpKQogICAgICA/IE51bWJlcihyYXcpCiAgICAgIDogbnVsbDsKfQoKZnVuY3Rpb24gaXNJbnZlbnRvcnkoZW50aXR5VHlwZTogc3RyaW5nKSB7CiAgcmV0dXJuIGVudGl0eVR5cGUgPT09ICJjaGFyYWN0ZXJfaXRlbXMiIHx8IGVudGl0eVR5cGUgPT09ICJjaGFyYWN0ZXJfaXRlbV9pbnN0YW5jZXMiOwp9CgpleHBvcnQgZnVuY3Rpb24gYXVkaXRTdW1tYXJ5KHJvdzogQ2hhcmFjdGVyQXVkaXREaXNwbGF5QmFzZSkgewogIGNvbnN0IGJlZm9yZSA9IHJvdy5vbGRfdmFsdWVzID8/IHt9OwogIGNvbnN0IGFmdGVyID0gcm93Lm5ld192YWx1ZXMgPz8ge307CgogIGlmIChpc0ludmVudG9yeShyb3cuZW50aXR5X3R5cGUpICYmIHJvdy5pdGVtX25hbWUpIHsKICAgIGNvbnN0IGJlZm9yZVF0eSA9IHF0eShyb3csICJiZWZvcmUiKTsKICAgIGNvbnN0IGFmdGVyUXR5ID0gcXR5KHJvdywgImFmdGVyIik7CgogICAgaWYgKHJvdy5vcGVyYXRpb24gPT09ICJpbnNlcnQiKSB7CiAgICAgIHJldHVybiBhZnRlclF0eSAhPT0gbnVsbAogICAgICAgID8gYCR7YWZ0ZXJRdHl9IMOXICR7cm93Lml0ZW1fbmFtZX0gYWRkZWQgdG8gaW52ZW50b3J5YAogICAgICAgIDogYCR7cm93Lml0ZW1fbmFtZX0gYWRkZWQgdG8gaW52ZW50b3J5YDsKICAgIH0KCiAgICBpZiAocm93Lm9wZXJhdGlvbiA9PT0gImRlbGV0ZSIpIHsKICAgICAgcmV0dXJuIGJlZm9yZVF0eSAhPT0gbnVsbAogICAgICAgID8gYCR7YmVmb3JlUXR5fSDDlyAke3Jvdy5pdGVtX25hbWV9IHJlbW92ZWQgZnJvbSBpbnZlbnRvcnlgCiAgICAgICAgOiBgJHtyb3cuaXRlbV9uYW1lfSByZW1vdmVkIGZyb20gaW52ZW50b3J5YDsKICAgIH0KCiAgICBpZiAoCiAgICAgIHJvdy5vcGVyYXRpb24gPT09ICJ1cGRhdGUiICYmCiAgICAgIGJlZm9yZVF0eSAhPT0gbnVsbCAmJgogICAgICBhZnRlclF0eSAhPT0gbnVsbCAmJgogICAgICBiZWZvcmVRdHkgIT09IGFmdGVyUXR5CiAgICApIHsKICAgICAgcmV0dXJuIGAke3Jvdy5pdGVtX25hbWV9IHF1YW50aXR5IGNoYW5nZWQ6ICR7YmVmb3JlUXR5fSDihpIgJHthZnRlclF0eX1gOwogICAgfQoKICAgIHJldHVybiBgJHtyb3cuaXRlbV9uYW1lfSBpbnZlbnRvcnkgcmVjb3JkIHVwZGF0ZWRgOwogIH0KCiAgaWYgKAogICAgcm93LmVudGl0eV90eXBlID09PSAicmVtbmFudF9sZWRnZXIiIHx8CiAgICAoImFtb3VudCIgaW4gYWZ0ZXIgJiYgImJhbGFuY2VfYWZ0ZXIiIGluIGFmdGVyKQogICkgewogICAgY29uc3QgYW1vdW50ID0gTnVtYmVyKGFmdGVyLmFtb3VudCA/PyAwKTsKICAgIGNvbnN0IHJlYXNvbiA9IFN0cmluZyhhZnRlci5yZWFzb24gPz8gIlJlbW5hbnQgbW92ZW1lbnQiKTsKICAgIGNvbnN0IGJhbGFuY2UgPSBOdW1iZXIoYWZ0ZXIuYmFsYW5jZV9hZnRlciA/PyAwKTsKCiAgICBjb25zdCBtb3ZlbWVudCA9CiAgICAgIGFtb3VudCA8IDAKICAgICAgICA/IGAke01hdGguYWJzKGFtb3VudCl9IFJlbW5hbnRzIHNwZW50YAogICAgICAgIDogYW1vdW50ID4gMAogICAgICAgICAgPyBgJHthbW91bnR9IFJlbW5hbnRzIHJlY2VpdmVkYAogICAgICAgICAgOiAiUmVtbmFudCBiYWxhbmNlIHJlY29yZGVkIjsKCiAgICByZXR1cm4gYCR7bW92ZW1lbnR9IMK3ICR7cmVhc29ufSDCtyBCYWxhbmNlIGFmdGVyOiAke25ldyBJbnRsLk51bWJlckZvcm1hdCgiZW4tR0IiKS5mb3JtYXQoYmFsYW5jZSl9IFJgOwogIH0KCiAgaWYgKHJvdy5vcGVyYXRpb24gPT09ICJ1cGRhdGUiICYmIHJvdy5jaGFuZ2VkX2ZpZWxkcz8ubGVuZ3RoKSB7CiAgICBjb25zdCBmaWVsZHMgPSByb3cuY2hhbmdlZF9maWVsZHMKICAgICAgLmZpbHRlcigoZmllbGQpID0+IGZpZWxkICE9PSAidXBkYXRlZF9hdCIpCiAgICAgIC5zbGljZSgwLCA0KQogICAgICAubWFwKChmaWVsZCkgPT4KICAgICAgICBgJHtodW1hbkF1ZGl0TGFiZWwoZmllbGQpfTogJHthdWRpdERpc3BsYXlWYWx1ZShiZWZvcmVbZmllbGRdKX0g4oaSICR7YXVkaXREaXNwbGF5VmFsdWUoYWZ0ZXJbZmllbGRdKX1gLAogICAgICApOwoKICAgIGlmIChmaWVsZHMubGVuZ3RoKSByZXR1cm4gZmllbGRzLmpvaW4oIiDCtyAiKTsKICB9CgogIGNvbnN0IHNvdXJjZSA9IHJvdy5vcGVyYXRpb24gPT09ICJkZWxldGUiID8gYmVmb3JlIDogYWZ0ZXI7CiAgY29uc3QgZW50cmllcyA9IG1lYW5pbmdmdWxBdWRpdEVudHJpZXMoc291cmNlKS5zbGljZSgwLCA0KTsKCiAgaWYgKGVudHJpZXMubGVuZ3RoKSB7CiAgICByZXR1cm4gZW50cmllcwogICAgICAubWFwKChba2V5LCB2YWx1ZV0pID0+IGAke2h1bWFuQXVkaXRMYWJlbChrZXkpfTogJHthdWRpdERpc3BsYXlWYWx1ZSh2YWx1ZSl9YCkKICAgICAgLmpvaW4oIiDCtyAiKTsKICB9CgogIHJldHVybiBodW1hbkF1ZGl0TGFiZWwocm93LmV2ZW50X3R5cGUpOwp9CgpleHBvcnQgZnVuY3Rpb24gYXVkaXRDaGFuZ2VSb3dzKHJvdzogQ2hhcmFjdGVyQXVkaXREaXNwbGF5QmFzZSkgewogIGNvbnN0IGJlZm9yZSA9IHJvdy5vbGRfdmFsdWVzID8/IHt9OwogIGNvbnN0IGFmdGVyID0gcm93Lm5ld192YWx1ZXMgPz8ge307CgogIGNvbnN0IHJvd3MgPQogICAgcm93Lm9wZXJhdGlvbiA9PT0gInVwZGF0ZSIKICAgICAgPyAocm93LmNoYW5nZWRfZmllbGRzID8/IFtdKQogICAgICAgICAgLmZpbHRlcigoZmllbGQpID0+IGZpZWxkICE9PSAidXBkYXRlZF9hdCIgJiYgZmllbGQgIT09ICJpdGVtX2lkIikKICAgICAgICAgIC5tYXAoKGZpZWxkKSA9PiAoeyBmaWVsZCwgYmVmb3JlOiBiZWZvcmVbZmllbGRdLCBhZnRlcjogYWZ0ZXJbZmllbGRdIH0pKQogICAgICA6IG1lYW5pbmdmdWxBdWRpdEVudHJpZXMocm93Lm9wZXJhdGlvbiA9PT0gImRlbGV0ZSIgPyBiZWZvcmUgOiBhZnRlcikubWFwKAogICAgICAgICAgKFtmaWVsZCwgdmFsdWVdKSA9PiAoewogICAgICAgICAgICBmaWVsZCwKICAgICAgICAgICAgYmVmb3JlOiByb3cub3BlcmF0aW9uID09PSAiZGVsZXRlIiA/IHZhbHVlIDogbnVsbCwKICAgICAgICAgICAgYWZ0ZXI6IHJvdy5vcGVyYXRpb24gPT09ICJkZWxldGUiID8gbnVsbCA6IHZhbHVlLAogICAgICAgICAgfSksCiAgICAgICAgKTsKCiAgaWYgKGlzSW52ZW50b3J5KHJvdy5lbnRpdHlfdHlwZSkgJiYgcm93Lml0ZW1fbmFtZSkgewogICAgcmV0dXJuIFsKICAgICAgewogICAgICAgIGZpZWxkOiAiaXRlbSIsCiAgICAgICAgYmVmb3JlOiByb3cub3BlcmF0aW9uID09PSAiaW5zZXJ0IiA/IG51bGwgOiByb3cuaXRlbV9uYW1lLAogICAgICAgIGFmdGVyOiByb3cub3BlcmF0aW9uID09PSAiZGVsZXRlIiA/IG51bGwgOiByb3cuaXRlbV9uYW1lLAogICAgICB9LAogICAgICAuLi5yb3dzLmZpbHRlcigoY2hhbmdlKSA9PiBjaGFuZ2UuZmllbGQgIT09ICJpdGVtIiksCiAgICBdOwogIH0KCiAgcmV0dXJuIHJvd3M7Cn0K', 'lib/audit/enrich-character-audit-items.ts': 'aW1wb3J0ICJzZXJ2ZXItb25seSI7CgppbXBvcnQgeyBjcmVhdGVBZG1pbkNsaWVudCB9IGZyb20gIkAvbGliL3N1cGFiYXNlL2FkbWluIjsKCnR5cGUgQXVkaXRSb3dMaWtlID0gewogIGlkOiBzdHJpbmc7CiAgZW50aXR5X3R5cGU6IHN0cmluZzsKICBlbnRpdHlfaWQ6IHN0cmluZyB8IG51bGw7CiAgb2xkX3ZhbHVlczogUmVjb3JkPHN0cmluZywgdW5rbm93bj4gfCBudWxsOwogIG5ld192YWx1ZXM6IFJlY29yZDxzdHJpbmcsIHVua25vd24+IHwgbnVsbDsKfTsKCmZ1bmN0aW9uIHV1aWRMaWtlKHZhbHVlOiB1bmtub3duKSB7CiAgcmV0dXJuIHR5cGVvZiB2YWx1ZSA9PT0gInN0cmluZyIgJiYKICAgIC9eWzAtOWEtZl17OH0tWzAtOWEtZl17NH0tWzEtNV1bMC05YS1mXXszfS1bODlhYl1bMC05YS1mXXszfS1bMC05YS1mXXsxMn0kL2kudGVzdCh2YWx1ZSkKICAgID8gdmFsdWUKICAgIDogbnVsbDsKfQoKZnVuY3Rpb24gZGlyZWN0SXRlbUlkKHJvdzogQXVkaXRSb3dMaWtlKSB7CiAgcmV0dXJuIHV1aWRMaWtlKHJvdy5uZXdfdmFsdWVzPy5pdGVtX2lkKSA/PyB1dWlkTGlrZShyb3cub2xkX3ZhbHVlcz8uaXRlbV9pZCk7Cn0KCmV4cG9ydCBhc3luYyBmdW5jdGlvbiBlbnJpY2hDaGFyYWN0ZXJBdWRpdEl0ZW1OYW1lczxUIGV4dGVuZHMgQXVkaXRSb3dMaWtlPigKICByb3dzOiBUW10sCik6IFByb21pc2U8QXJyYXk8VCAmIHsgaXRlbV9uYW1lOiBzdHJpbmcgfCBudWxsIH0+PiB7CiAgY29uc3QgYWRtaW4gPSBjcmVhdGVBZG1pbkNsaWVudCgpOwogIGNvbnN0IGl0ZW1JZEJ5QXVkaXRJZCA9IG5ldyBNYXA8c3RyaW5nLCBzdHJpbmc+KCk7CiAgY29uc3QgY2hhcmFjdGVySXRlbUVudGl0eUlkczogc3RyaW5nW10gPSBbXTsKICBjb25zdCBpbnN0YW5jZUVudGl0eUlkczogc3RyaW5nW10gPSBbXTsKCiAgZm9yIChjb25zdCByb3cgb2Ygcm93cykgewogICAgY29uc3QgZGlyZWN0ID0gZGlyZWN0SXRlbUlkKHJvdyk7CiAgICBpZiAoZGlyZWN0KSB7CiAgICAgIGl0ZW1JZEJ5QXVkaXRJZC5zZXQocm93LmlkLCBkaXJlY3QpOwogICAgICBjb250aW51ZTsKICAgIH0KCiAgICBpZiAoIXJvdy5lbnRpdHlfaWQpIGNvbnRpbnVlOwogICAgaWYgKHJvdy5lbnRpdHlfdHlwZSA9PT0gImNoYXJhY3Rlcl9pdGVtcyIpIGNoYXJhY3Rlckl0ZW1FbnRpdHlJZHMucHVzaChyb3cuZW50aXR5X2lkKTsKICAgIGlmIChyb3cuZW50aXR5X3R5cGUgPT09ICJjaGFyYWN0ZXJfaXRlbV9pbnN0YW5jZXMiKSBpbnN0YW5jZUVudGl0eUlkcy5wdXNoKHJvdy5lbnRpdHlfaWQpOwogIH0KCiAgY29uc3QgW2NoYXJhY3Rlckl0ZW1zUmVzdWx0LCBpbnN0YW5jZXNSZXN1bHRdID0gYXdhaXQgUHJvbWlzZS5hbGwoWwogICAgY2hhcmFjdGVySXRlbUVudGl0eUlkcy5sZW5ndGgKICAgICAgPyBhZG1pbgogICAgICAgICAgLmZyb20oImNoYXJhY3Rlcl9pdGVtcyIpCiAgICAgICAgICAuc2VsZWN0KCJpZCwgaXRlbV9pZCIpCiAgICAgICAgICAuaW4oImlkIiwgQXJyYXkuZnJvbShuZXcgU2V0KGNoYXJhY3Rlckl0ZW1FbnRpdHlJZHMpKSkKICAgICAgOiBQcm9taXNlLnJlc29sdmUoeyBkYXRhOiBbXSwgZXJyb3I6IG51bGwgfSksCiAgICBpbnN0YW5jZUVudGl0eUlkcy5sZW5ndGgKICAgICAgPyBhZG1pbgogICAgICAgICAgLmZyb20oImNoYXJhY3Rlcl9pdGVtX2luc3RhbmNlcyIpCiAgICAgICAgICAuc2VsZWN0KCJpZCwgaXRlbV9pZCIpCiAgICAgICAgICAuaW4oImlkIiwgQXJyYXkuZnJvbShuZXcgU2V0KGluc3RhbmNlRW50aXR5SWRzKSkpCiAgICAgIDogUHJvbWlzZS5yZXNvbHZlKHsgZGF0YTogW10sIGVycm9yOiBudWxsIH0pLAogIF0pOwoKICBpZiAoY2hhcmFjdGVySXRlbXNSZXN1bHQuZXJyb3IpIHsKICAgIHRocm93IG5ldyBFcnJvcihgVW5hYmxlIHRvIHJlc29sdmUgQ2hhcmFjdGVyIExvZyBpbnZlbnRvcnkgSXRlbXM6ICR7Y2hhcmFjdGVySXRlbXNSZXN1bHQuZXJyb3IubWVzc2FnZX1gKTsKICB9CiAgaWYgKGluc3RhbmNlc1Jlc3VsdC5lcnJvcikgewogICAgdGhyb3cgbmV3IEVycm9yKGBVbmFibGUgdG8gcmVzb2x2ZSBDaGFyYWN0ZXIgTG9nIEl0ZW0gaW5zdGFuY2VzOiAke2luc3RhbmNlc1Jlc3VsdC5lcnJvci5tZXNzYWdlfWApOwogIH0KCiAgY29uc3QgaXRlbUlkQnlFbnRpdHlJZCA9IG5ldyBNYXA8c3RyaW5nLCBzdHJpbmc+KCk7CiAgZm9yIChjb25zdCByZWNvcmQgb2YgWwogICAgLi4uKGNoYXJhY3Rlckl0ZW1zUmVzdWx0LmRhdGEgPz8gW10pLAogICAgLi4uKGluc3RhbmNlc1Jlc3VsdC5kYXRhID8/IFtdKSwKICBdKSB7CiAgICBpZiAocmVjb3JkLmlkICYmIHJlY29yZC5pdGVtX2lkKSB7CiAgICAgIGl0ZW1JZEJ5RW50aXR5SWQuc2V0KFN0cmluZyhyZWNvcmQuaWQpLCBTdHJpbmcocmVjb3JkLml0ZW1faWQpKTsKICAgIH0KICB9CgogIGZvciAoY29uc3Qgcm93IG9mIHJvd3MpIHsKICAgIGlmICghaXRlbUlkQnlBdWRpdElkLmhhcyhyb3cuaWQpICYmIHJvdy5lbnRpdHlfaWQpIHsKICAgICAgY29uc3QgcmVzb2x2ZWQgPSBpdGVtSWRCeUVudGl0eUlkLmdldChyb3cuZW50aXR5X2lkKTsKICAgICAgaWYgKHJlc29sdmVkKSBpdGVtSWRCeUF1ZGl0SWQuc2V0KHJvdy5pZCwgcmVzb2x2ZWQpOwogICAgfQogIH0KCiAgY29uc3QgaXRlbUlkcyA9IEFycmF5LmZyb20obmV3IFNldChpdGVtSWRCeUF1ZGl0SWQudmFsdWVzKCkpKTsKICBjb25zdCBpdGVtTmFtZUJ5SWQgPSBuZXcgTWFwPHN0cmluZywgc3RyaW5nPigpOwoKICBpZiAoaXRlbUlkcy5sZW5ndGgpIHsKICAgIGNvbnN0IHsgZGF0YSwgZXJyb3IgfSA9IGF3YWl0IGFkbWluCiAgICAgIC5mcm9tKCJpdGVtcyIpCiAgICAgIC5zZWxlY3QoImlkLCBuYW1lIikKICAgICAgLmluKCJpZCIsIGl0ZW1JZHMpOwoKICAgIGlmIChlcnJvcikgewogICAgICB0aHJvdyBuZXcgRXJyb3IoYFVuYWJsZSB0byByZXNvbHZlIENoYXJhY3RlciBMb2cgSXRlbSBuYW1lczogJHtlcnJvci5tZXNzYWdlfWApOwogICAgfQoKICAgIGZvciAoY29uc3QgaXRlbSBvZiBkYXRhID8/IFtdKSB7CiAgICAgIGl0ZW1OYW1lQnlJZC5zZXQoU3RyaW5nKGl0ZW0uaWQpLCBTdHJpbmcoaXRlbS5uYW1lKSk7CiAgICB9CiAgfQoKICByZXR1cm4gcm93cy5tYXAoKHJvdykgPT4gewogICAgY29uc3QgaXRlbUlkID0gaXRlbUlkQnlBdWRpdElkLmdldChyb3cuaWQpID8/IG51bGw7CiAgICByZXR1cm4gewogICAgICAuLi5yb3csCiAgICAgIGl0ZW1fbmFtZTogaXRlbUlkID8gaXRlbU5hbWVCeUlkLmdldChpdGVtSWQpID8/IG51bGwgOiBudWxsLAogICAgfTsKICB9KTsKfQo=', 'components/characters/character-audit-entry.tsx': 'aW1wb3J0IHsKICBhdWRpdENoYW5nZVJvd3MsCiAgYXVkaXREaXNwbGF5VmFsdWUsCiAgYXVkaXRTdW1tYXJ5LAogIGZvcm1hdEF1ZGl0RGF0ZVRpbWUsCiAgaHVtYW5BdWRpdExhYmVsLAogIHByZXR0eUF1ZGl0VmFsdWUsCiAgdHlwZSBDaGFyYWN0ZXJBdWRpdERpc3BsYXlCYXNlLAp9IGZyb20gIkAvbGliL2F1ZGl0L2NoYXJhY3Rlci1hdWRpdC1kaXNwbGF5IjsKCmV4cG9ydCBmdW5jdGlvbiBDaGFyYWN0ZXJBdWRpdEVudHJ5KHsKICByb3csCiAgY2hhcmFjdGVyTGFiZWwgPSBudWxsLAp9OiB7CiAgcm93OiBDaGFyYWN0ZXJBdWRpdERpc3BsYXlCYXNlOwogIGNoYXJhY3RlckxhYmVsPzogc3RyaW5nIHwgbnVsbDsKfSkgewogIGNvbnN0IHN1bW1hcnkgPSBhdWRpdFN1bW1hcnkocm93KTsKICBjb25zdCBjaGFuZ2VzID0gYXVkaXRDaGFuZ2VSb3dzKHJvdyk7CiAgY29uc3QgYWN0b3JMYWJlbCA9IHJvdy5hY3Rvcl9sYWJlbCA/PyByb3cuYWN0b3JfdHlwZTsKICBjb25zdCBkYXRlTGFiZWwgPSBmb3JtYXRBdWRpdERhdGVUaW1lKHJvdy5jcmVhdGVkX2F0KTsKCiAgcmV0dXJuICgKICAgIDxhcnRpY2xlIGNsYXNzTmFtZT0iYm9yZGVyIGJvcmRlci1bcmdiKHZhcigtLXNlcC1jb2xvdXItNjA0ODJlKSldLzQ1IGJnLVtyZ2IodmFyKC0tc2VwLWNvbG91ci0xNTEwMGQpKV0gcC00Ij4KICAgICAgPGRpdiBjbGFzc05hbWU9ImZsZXggZmxleC13cmFwIGl0ZW1zLXN0YXJ0IGp1c3RpZnktYmV0d2VlbiBnYXAtNCI+CiAgICAgICAgPGRpdiBjbGFzc05hbWU9Im1pbi13LTAiPgogICAgICAgICAgPHAgY2xhc3NOYW1lPSJ0ZXh0LVs4cHhdIHVwcGVyY2FzZSB0cmFja2luZy1bMC4xOGVtXSB0ZXh0LVtyZ2IodmFyKC0tc2VwLWNvbG91ci05Njc3NGYpKV0iPgogICAgICAgICAgICB7aHVtYW5BdWRpdExhYmVsKHJvdy5ldmVudF90eXBlKX0KICAgICAgICAgIDwvcD4KICAgICAgICAgIHtjaGFyYWN0ZXJMYWJlbCA/ICgKICAgICAgICAgICAgPGgyIGNsYXNzTmFtZT0ibXQtMSBmb250LXNlcmlmIHRleHQtMnhsIHRleHQtW3JnYih2YXIoLS1zZXAtY29sb3VyLWQ4YmY5MSkpXSI+CiAgICAgICAgICAgICAge2NoYXJhY3RlckxhYmVsfQogICAgICAgICAgICA8L2gyPgogICAgICAgICAgKSA6IG51bGx9CiAgICAgICAgPC9kaXY+CgogICAgICAgIDxkaXYgY2xhc3NOYW1lPSJzaHJpbmstMCB0ZXh0LXJpZ2h0Ij4KICAgICAgICAgIDxwIGNsYXNzTmFtZT0idGV4dC1bOXB4XSB0ZXh0LVtyZ2IodmFyKC0tc2VwLWNvbG91ci1iNDlkN2IpKV0iPntkYXRlTGFiZWx9PC9wPgogICAgICAgICAgPHAgY2xhc3NOYW1lPSJtdC0xIHRleHQtWzhweF0gdXBwZXJjYXNlIHRyYWNraW5nLVswLjEyZW1dIHRleHQtW3JnYih2YXIoLS1zZXAtY29sb3VyLTc1Njk1OCkpXSI+CiAgICAgICAgICAgIHtodW1hbkF1ZGl0TGFiZWwocm93Lm9wZXJhdGlvbil9IMK3IHtodW1hbkF1ZGl0TGFiZWwocm93LmVudGl0eV90eXBlKX0KICAgICAgICAgIDwvcD4KICAgICAgICA8L2Rpdj4KICAgICAgPC9kaXY+CgogICAgICA8ZGl2IGNsYXNzTmFtZT0ibXQtNCBib3JkZXItbC0yIGJvcmRlci1bcmdiKHZhcigtLXNlcC1jb2xvdXItOTg3MzQ0KSldIGJnLVtyZ2IodmFyKC0tc2VwLWNvbG91ci0xMDBjMDkpKV0gcHgtNCBweS0zIj4KICAgICAgICA8cCBjbGFzc05hbWU9InRleHQtWzdweF0gdXBwZXJjYXNlIHRyYWNraW5nLVswLjE2ZW1dIHRleHQtW3JnYih2YXIoLS1zZXAtY29sb3VyLTgwNmI1MCkpXSI+CiAgICAgICAgICBXaGF0IGhhcHBlbmVkCiAgICAgICAgPC9wPgogICAgICAgIDxwIGNsYXNzTmFtZT0ibXQtMS41IHRleHQtWzExcHhdIGxlYWRpbmctNSB0ZXh0LVtyZ2IodmFyKC0tc2VwLWNvbG91ci1kNGJlYTApKV0iPgogICAgICAgICAge3N1bW1hcnl9CiAgICAgICAgPC9wPgogICAgICA8L2Rpdj4KCiAgICAgIHtjaGFuZ2VzLmxlbmd0aCA/ICgKICAgICAgICA8ZGl2IGNsYXNzTmFtZT0ibXQtMyBvdmVyZmxvdy1oaWRkZW4gYm9yZGVyIGJvcmRlci1bcmdiKHZhcigtLXNlcC1jb2xvdXItNTk0MzJjKSldLzM1Ij4KICAgICAgICAgIDxkaXYgY2xhc3NOYW1lPSJncmlkIGdyaWQtY29scy1bbWlubWF4KDE0MHB4LDAuNjVmcilfbWlubWF4KDAsMWZyKV8yNHB4X21pbm1heCgwLDFmcildIGdhcC0yIGJnLVtyZ2IodmFyKC0tc2VwLWNvbG91ci0xMDBjMDkpKV0gcHgtMyBweS0yIHRleHQtWzdweF0gdXBwZXJjYXNlIHRyYWNraW5nLVswLjE0ZW1dIHRleHQtW3JnYih2YXIoLS1zZXAtY29sb3VyLTc1Njk1OCkpXSI+CiAgICAgICAgICAgIDxzcGFuPkZpZWxkPC9zcGFuPjxzcGFuPkJlZm9yZTwvc3Bhbj48c3BhbiAvPjxzcGFuPkFmdGVyPC9zcGFuPgogICAgICAgICAgPC9kaXY+CiAgICAgICAgICA8ZGl2IGNsYXNzTmFtZT0iZGl2aWRlLXkgZGl2aWRlLVtyZ2IodmFyKC0tc2VwLWNvbG91ci01OTQzMmMpKV0vMjUiPgogICAgICAgICAgICB7Y2hhbmdlcy5tYXAoKGNoYW5nZSwgaW5kZXgpID0+ICgKICAgICAgICAgICAgICA8ZGl2CiAgICAgICAgICAgICAgICBrZXk9e2Ake2NoYW5nZS5maWVsZH0tJHtpbmRleH1gfQogICAgICAgICAgICAgICAgY2xhc3NOYW1lPSJncmlkIGdyaWQtY29scy1bbWlubWF4KDE0MHB4LDAuNjVmcilfbWlubWF4KDAsMWZyKV8yNHB4X21pbm1heCgwLDFmcildIGdhcC0yIHB4LTMgcHktMi41IHRleHQtWzlweF0iCiAgICAgICAgICAgICAgPgogICAgICAgICAgICAgICAgPHNwYW4gY2xhc3NOYW1lPSJmb250LW1lZGl1bSB0ZXh0LVtyZ2IodmFyKC0tc2VwLWNvbG91ci1iZmE3N2YpKV0iPgogICAgICAgICAgICAgICAgICB7aHVtYW5BdWRpdExhYmVsKGNoYW5nZS5maWVsZCl9CiAgICAgICAgICAgICAgICA8L3NwYW4+CiAgICAgICAgICAgICAgICA8c3BhbiBjbGFzc05hbWU9ImJyZWFrLXdvcmRzIHRleHQtW3JnYih2YXIoLS1zZXAtY29sb3VyLThmODI3MSkpXSI+CiAgICAgICAgICAgICAgICAgIHthdWRpdERpc3BsYXlWYWx1ZShjaGFuZ2UuYmVmb3JlKX0KICAgICAgICAgICAgICAgIDwvc3Bhbj4KICAgICAgICAgICAgICAgIDxzcGFuIGNsYXNzTmFtZT0idGV4dC1jZW50ZXIgdGV4dC1bcmdiKHZhcigtLXNlcC1jb2xvdXItNmY2MjUyKSldIj7ihpI8L3NwYW4+CiAgICAgICAgICAgICAgICA8c3BhbiBjbGFzc05hbWU9ImJyZWFrLXdvcmRzIHRleHQtW3JnYih2YXIoLS1zZXAtY29sb3VyLWNkYjU4ZCkpXSI+CiAgICAgICAgICAgICAgICAgIHthdWRpdERpc3BsYXlWYWx1ZShjaGFuZ2UuYWZ0ZXIpfQogICAgICAgICAgICAgICAgPC9zcGFuPgogICAgICAgICAgICAgIDwvZGl2PgogICAgICAgICAgICApKX0KICAgICAgICAgIDwvZGl2PgogICAgICAgIDwvZGl2PgogICAgICApIDogbnVsbH0KCiAgICAgIDxkaXYgY2xhc3NOYW1lPSJtdC0zIGdyaWQgZ2FwLTIgc206Z3JpZC1jb2xzLTMiPgogICAgICAgIHtbCiAgICAgICAgICBbIkFjdG9yIiwgYWN0b3JMYWJlbF0sCiAgICAgICAgICBbIlNvdXJjZSIsIGh1bWFuQXVkaXRMYWJlbChyb3cuc291cmNlKV0sCiAgICAgICAgICBbIlJlY29yZCB0eXBlIiwgaHVtYW5BdWRpdExhYmVsKHJvdy5lbnRpdHlfdHlwZSldLAogICAgICAgIF0ubWFwKChbbGFiZWwsIHZhbHVlXSkgPT4gKAogICAgICAgICAgPGRpdgogICAgICAgICAgICBrZXk9e2xhYmVsfQogICAgICAgICAgICBjbGFzc05hbWU9ImJvcmRlciBib3JkZXItW3JnYih2YXIoLS1zZXAtY29sb3VyLTU5NDMyYykpXS8zNSBiZy1bcmdiKHZhcigtLXNlcC1jb2xvdXItMTAwYzA5KSldIHAtMyIKICAgICAgICAgID4KICAgICAgICAgICAgPHAgY2xhc3NOYW1lPSJ0ZXh0LVs3cHhdIHVwcGVyY2FzZSB0cmFja2luZy1bMC4xNWVtXSB0ZXh0LVtyZ2IodmFyKC0tc2VwLWNvbG91ci03NTY5NTgpKV0iPgogICAgICAgICAgICAgIHtsYWJlbH0KICAgICAgICAgICAgPC9wPgogICAgICAgICAgICA8cCBjbGFzc05hbWU9Im10LTEgdGV4dC1bMTBweF0gdGV4dC1bcmdiKHZhcigtLXNlcC1jb2xvdXItYjhhNDg4KSldIj4KICAgICAgICAgICAgICB7dmFsdWV9CiAgICAgICAgICAgIDwvcD4KICAgICAgICAgIDwvZGl2PgogICAgICAgICkpfQogICAgICA8L2Rpdj4KCiAgICAgIDxkZXRhaWxzIGNsYXNzTmFtZT0ibXQtMyBib3JkZXIgYm9yZGVyLVtyZ2IodmFyKC0tc2VwLWNvbG91ci01OTQzMmMpKV0vMzAgYmctW3JnYih2YXIoLS1zZXAtY29sb3VyLTEwMGMwOSkpXSI+CiAgICAgICAgPHN1bW1hcnkgY2xhc3NOYW1lPSJjdXJzb3ItcG9pbnRlciBweC0zIHB5LTIgdGV4dC1bOHB4XSB1cHBlcmNhc2UgdHJhY2tpbmctWzAuMTRlbV0gdGV4dC1bcmdiKHZhcigtLXNlcC1jb2xvdXItYTk4ZDY1KSldIj4KICAgICAgICAgIFRlY2huaWNhbCBkZXRhaWxzCiAgICAgICAgPC9zdW1tYXJ5PgoKICAgICAgICA8ZGl2IGNsYXNzTmFtZT0iYm9yZGVyLXQgYm9yZGVyLVtyZ2IodmFyKC0tc2VwLWNvbG91ci01OTQzMmMpKV0vMjUgcC0zIj4KICAgICAgICAgIDxkaXYgY2xhc3NOYW1lPSJncmlkIGdhcC0yIHRleHQtWzhweF0gc206Z3JpZC1jb2xzLTIiPgogICAgICAgICAgICA8cD5BdWRpdCBJRDoge3Jvdy5pZH08L3A+CiAgICAgICAgICAgIDxwPkVudGl0eSBJRDoge3Jvdy5lbnRpdHlfaWQgPz8gIuKAlCJ9PC9wPgogICAgICAgICAgICB7cm93Lml0ZW1fbmFtZSA/IDxwPlJlc29sdmVkIEl0ZW06IHtyb3cuaXRlbV9uYW1lfTwvcD4gOiBudWxsfQogICAgICAgICAgPC9kaXY+CgogICAgICAgICAgPGRpdiBjbGFzc05hbWU9Im10LTMgZ3JpZCBnYXAtMyBsZzpncmlkLWNvbHMtMiI+CiAgICAgICAgICAgIDxkaXY+CiAgICAgICAgICAgICAgPHAgY2xhc3NOYW1lPSJ0ZXh0LVs3cHhdIHVwcGVyY2FzZSB0cmFja2luZy1bMC4xNGVtXSB0ZXh0LVtyZ2IodmFyKC0tc2VwLWNvbG91ci03NTY5NTgpKV0iPgogICAgICAgICAgICAgICAgUmF3IGJlZm9yZQogICAgICAgICAgICAgIDwvcD4KICAgICAgICAgICAgICA8cHJlIGNsYXNzTmFtZT0ibXQtMiBtYXgtaC02NCBvdmVyZmxvdy1hdXRvIHdoaXRlc3BhY2UtcHJlLXdyYXAgYnJlYWstd29yZHMgdGV4dC1bOHB4XSBsZWFkaW5nLTUgdGV4dC1bcmdiKHZhcigtLXNlcC1jb2xvdXItOGY4MjcxKSldIj4KICAgICAgICAgICAgICAgIHtwcmV0dHlBdWRpdFZhbHVlKHJvdy5vbGRfdmFsdWVzKX0KICAgICAgICAgICAgICA8L3ByZT4KICAgICAgICAgICAgPC9kaXY+CgogICAgICAgICAgICA8ZGl2PgogICAgICAgICAgICAgIDxwIGNsYXNzTmFtZT0idGV4dC1bN3B4XSB1cHBlcmNhc2UgdHJhY2tpbmctWzAuMTRlbV0gdGV4dC1bcmdiKHZhcigtLXNlcC1jb2xvdXItNzU2OTU4KSldIj4KICAgICAgICAgICAgICAgIFJhdyBhZnRlcgogICAgICAgICAgICAgIDwvcD4KICAgICAgICAgICAgICA8cHJlIGNsYXNzTmFtZT0ibXQtMiBtYXgtaC02NCBvdmVyZmxvdy1hdXRvIHdoaXRlc3BhY2UtcHJlLXdyYXAgYnJlYWstd29yZHMgdGV4dC1bOHB4XSBsZWFkaW5nLTUgdGV4dC1bcmdiKHZhcigtLXNlcC1jb2xvdXItOGY4MjcxKSldIj4KICAgICAgICAgICAgICAgIHtwcmV0dHlBdWRpdFZhbHVlKHJvdy5uZXdfdmFsdWVzKX0KICAgICAgICAgICAgICA8L3ByZT4KICAgICAgICAgICAgPC9kaXY+CiAgICAgICAgICA8L2Rpdj4KCiAgICAgICAgICB7cm93Lm1ldGFkYXRhICYmIE9iamVjdC5rZXlzKHJvdy5tZXRhZGF0YSkubGVuZ3RoID8gKAogICAgICAgICAgICA8ZGl2IGNsYXNzTmFtZT0ibXQtMyBib3JkZXItdCBib3JkZXItW3JnYih2YXIoLS1zZXAtY29sb3VyLTU5NDMyYykpXS8yNSBwdC0zIj4KICAgICAgICAgICAgICA8cCBjbGFzc05hbWU9InRleHQtWzdweF0gdXBwZXJjYXNlIHRyYWNraW5nLVswLjE0ZW1dIHRleHQtW3JnYih2YXIoLS1zZXAtY29sb3VyLTc1Njk1OCkpXSI+CiAgICAgICAgICAgICAgICBSYXcgbWV0YWRhdGEKICAgICAgICAgICAgICA8L3A+CiAgICAgICAgICAgICAgPHByZSBjbGFzc05hbWU9Im10LTIgbWF4LWgtNjQgb3ZlcmZsb3ctYXV0byB3aGl0ZXNwYWNlLXByZS13cmFwIGJyZWFrLXdvcmRzIHRleHQtWzhweF0gbGVhZGluZy01IHRleHQtW3JnYih2YXIoLS1zZXAtY29sb3VyLThmODI3MSkpXSI+CiAgICAgICAgICAgICAgICB7cHJldHR5QXVkaXRWYWx1ZShyb3cubWV0YWRhdGEpfQogICAgICAgICAgICAgIDwvcHJlPgogICAgICAgICAgICA8L2Rpdj4KICAgICAgICAgICkgOiBudWxsfQogICAgICAgIDwvZGl2PgogICAgICA8L2RldGFpbHM+CiAgICA8L2FydGljbGU+CiAgKTsKfQo=', 'components/characters/character-audit-trail-client.tsx': 'InVzZSBjbGllbnQiOwoKaW1wb3J0IHsgdXNlTWVtbywgdXNlU3RhdGUgfSBmcm9tICJyZWFjdCI7CmltcG9ydCB7IENoYXJhY3RlckF1ZGl0RW50cnkgfSBmcm9tICJAL2NvbXBvbmVudHMvY2hhcmFjdGVycy9jaGFyYWN0ZXItYXVkaXQtZW50cnkiOwppbXBvcnQgewogIGh1bWFuQXVkaXRMYWJlbCwKICB0eXBlIENoYXJhY3RlckF1ZGl0RGlzcGxheUJhc2UsCn0gZnJvbSAiQC9saWIvYXVkaXQvY2hhcmFjdGVyLWF1ZGl0LWRpc3BsYXkiOwoKZXhwb3J0IHR5cGUgQ2hhcmFjdGVyQXVkaXREaXNwbGF5Um93ID0gQ2hhcmFjdGVyQXVkaXREaXNwbGF5QmFzZTsKCmNvbnN0IGNvbnRyb2xDbGFzcyA9CiAgImgtOSBtaW4tdy0wIGJvcmRlciBib3JkZXItW3JnYih2YXIoLS1zZXAtY29sb3VyLTYwNDgyZSkpXS81NSBiZy1bcmdiKHZhcigtLXNlcC1jb2xvdXItMTAwYzA5KSldIHB4LTMgdGV4dC1bOXB4XSB0ZXh0LVtyZ2IodmFyKC0tc2VwLWNvbG91ci1kN2M0YTUpKV0gb3V0bGluZS1ub25lIHBsYWNlaG9sZGVyOnRleHQtW3JnYih2YXIoLS1zZXAtY29sb3VyLTYyNTc0NykpXSBmb2N1czpib3JkZXItW3JnYih2YXIoLS1zZXAtY29sb3VyLTliNzQ0NikpXSI7CgpmdW5jdGlvbiBkYXlWYWx1ZSh2YWx1ZTogc3RyaW5nKSB7CiAgY29uc3QgZGF0ZSA9IG5ldyBEYXRlKHZhbHVlKTsKICByZXR1cm4gTnVtYmVyLmlzTmFOKGRhdGUuZ2V0VGltZSgpKSA/ICIiIDogZGF0ZS50b0lTT1N0cmluZygpLnNsaWNlKDAsIDEwKTsKfQoKZXhwb3J0IGZ1bmN0aW9uIENoYXJhY3RlckF1ZGl0VHJhaWxDbGllbnQoewogIHJvd3MsCiAgc3RhZmZWaWV3LAp9OiB7CiAgcm93czogQ2hhcmFjdGVyQXVkaXREaXNwbGF5Um93W107CiAgc3RhZmZWaWV3OiBib29sZWFuOwp9KSB7CiAgY29uc3QgW3NlYXJjaCwgc2V0U2VhcmNoXSA9IHVzZVN0YXRlKCIiKTsKICBjb25zdCBbZXZlbnRUeXBlLCBzZXRFdmVudFR5cGVdID0gdXNlU3RhdGUoIiIpOwogIGNvbnN0IFthY3RvclR5cGUsIHNldEFjdG9yVHlwZV0gPSB1c2VTdGF0ZSgiIik7CiAgY29uc3QgW3NvdXJjZSwgc2V0U291cmNlXSA9IHVzZVN0YXRlKCIiKTsKICBjb25zdCBbZnJvbURhdGUsIHNldEZyb21EYXRlXSA9IHVzZVN0YXRlKCIiKTsKICBjb25zdCBbdG9EYXRlLCBzZXRUb0RhdGVdID0gdXNlU3RhdGUoIiIpOwoKICBjb25zdCBldmVudE9wdGlvbnMgPSB1c2VNZW1vKAogICAgKCkgPT4gQXJyYXkuZnJvbShuZXcgU2V0KHJvd3MubWFwKChyb3cpID0+IHJvdy5ldmVudF90eXBlKSkpLnNvcnQoKSwKICAgIFtyb3dzXSwKICApOwoKICBjb25zdCBzb3VyY2VPcHRpb25zID0gdXNlTWVtbygKICAgICgpID0+IEFycmF5LmZyb20obmV3IFNldChyb3dzLm1hcCgocm93KSA9PiByb3cuc291cmNlKS5maWx0ZXIoQm9vbGVhbikpKS5zb3J0KCksCiAgICBbcm93c10sCiAgKTsKCiAgY29uc3QgZmlsdGVyZWRSb3dzID0gdXNlTWVtbygoKSA9PiB7CiAgICBjb25zdCBuZWVkbGUgPSBzZWFyY2gudHJpbSgpLnRvTG93ZXJDYXNlKCk7CgogICAgcmV0dXJuIHJvd3MuZmlsdGVyKChyb3cpID0+IHsKICAgICAgaWYgKGV2ZW50VHlwZSAmJiByb3cuZXZlbnRfdHlwZSAhPT0gZXZlbnRUeXBlKSByZXR1cm4gZmFsc2U7CiAgICAgIGlmIChhY3RvclR5cGUgJiYgcm93LmFjdG9yX3R5cGUgIT09IGFjdG9yVHlwZSkgcmV0dXJuIGZhbHNlOwogICAgICBpZiAoc291cmNlICYmIHJvdy5zb3VyY2UgIT09IHNvdXJjZSkgcmV0dXJuIGZhbHNlOwoKICAgICAgY29uc3Qgcm93RGF5ID0gZGF5VmFsdWUocm93LmNyZWF0ZWRfYXQpOwogICAgICBpZiAoZnJvbURhdGUgJiYgcm93RGF5IDwgZnJvbURhdGUpIHJldHVybiBmYWxzZTsKICAgICAgaWYgKHRvRGF0ZSAmJiByb3dEYXkgPiB0b0RhdGUpIHJldHVybiBmYWxzZTsKCiAgICAgIGlmICghbmVlZGxlKSByZXR1cm4gdHJ1ZTsKCiAgICAgIHJldHVybiBbCiAgICAgICAgcm93LmV2ZW50X3R5cGUsCiAgICAgICAgcm93LmVudGl0eV90eXBlLAogICAgICAgIHJvdy5lbnRpdHlfaWQsCiAgICAgICAgcm93Lml0ZW1fbmFtZSwKICAgICAgICByb3cuYWN0b3JfbGFiZWwsCiAgICAgICAgcm93LmFjdG9yX3N0YWZmX3JvbGUsCiAgICAgICAgcm93LnNvdXJjZSwKICAgICAgICAuLi4ocm93LmNoYW5nZWRfZmllbGRzID8/IFtdKSwKICAgICAgICBKU09OLnN0cmluZ2lmeShyb3cub2xkX3ZhbHVlcyA/PyB7fSksCiAgICAgICAgSlNPTi5zdHJpbmdpZnkocm93Lm5ld192YWx1ZXMgPz8ge30pLAogICAgICAgIHN0YWZmVmlldyA/IEpTT04uc3RyaW5naWZ5KHJvdy5tZXRhZGF0YSA/PyB7fSkgOiAiIiwKICAgICAgXQogICAgICAgIC5maWx0ZXIoQm9vbGVhbikKICAgICAgICAuam9pbigiICIpCiAgICAgICAgLnRvTG93ZXJDYXNlKCkKICAgICAgICAuaW5jbHVkZXMobmVlZGxlKTsKICAgIH0pOwogIH0sIFtyb3dzLCBzZWFyY2gsIGV2ZW50VHlwZSwgYWN0b3JUeXBlLCBzb3VyY2UsIGZyb21EYXRlLCB0b0RhdGUsIHN0YWZmVmlld10pOwoKICBjb25zdCBoYXNGaWx0ZXJzID0gQm9vbGVhbigKICAgIHNlYXJjaCB8fCBldmVudFR5cGUgfHwgYWN0b3JUeXBlIHx8IHNvdXJjZSB8fCBmcm9tRGF0ZSB8fCB0b0RhdGUsCiAgKTsKCiAgZnVuY3Rpb24gcmVzZXRGaWx0ZXJzKCkgewogICAgc2V0U2VhcmNoKCIiKTsKICAgIHNldEV2ZW50VHlwZSgiIik7CiAgICBzZXRBY3RvclR5cGUoIiIpOwogICAgc2V0U291cmNlKCIiKTsKICAgIHNldEZyb21EYXRlKCIiKTsKICAgIHNldFRvRGF0ZSgiIik7CiAgfQoKICByZXR1cm4gKAogICAgPD4KICAgICAgPGRpdiBjbGFzc05hbWU9Im10LTQgYm9yZGVyIGJvcmRlci1bcmdiKHZhcigtLXNlcC1jb2xvdXItNjA0ODJlKSldLzQ1IGJnLVtyZ2IodmFyKC0tc2VwLWNvbG91ci0xNTEwMGQpKV0gcC0zIj4KICAgICAgICA8ZGl2IGNsYXNzTmFtZT0iZ3JpZCBnYXAtMiBtZDpncmlkLWNvbHMtMiB4bDpncmlkLWNvbHMtMyI+CiAgICAgICAgICA8aW5wdXQKICAgICAgICAgICAgdHlwZT0ic2VhcmNoIgogICAgICAgICAgICB2YWx1ZT17c2VhcmNofQogICAgICAgICAgICBvbkNoYW5nZT17KGV2ZW50KSA9PiBzZXRTZWFyY2goZXZlbnQudGFyZ2V0LnZhbHVlKX0KICAgICAgICAgICAgcGxhY2Vob2xkZXI9IlNlYXJjaCBDaGFyYWN0ZXIgTG9nLi4uIgogICAgICAgICAgICBjbGFzc05hbWU9e2NvbnRyb2xDbGFzc30KICAgICAgICAgIC8+CgogICAgICAgICAgPHNlbGVjdAogICAgICAgICAgICB2YWx1ZT17ZXZlbnRUeXBlfQogICAgICAgICAgICBvbkNoYW5nZT17KGV2ZW50KSA9PiBzZXRFdmVudFR5cGUoZXZlbnQudGFyZ2V0LnZhbHVlKX0KICAgICAgICAgICAgY2xhc3NOYW1lPXtjb250cm9sQ2xhc3N9CiAgICAgICAgICA+CiAgICAgICAgICAgIDxvcHRpb24gdmFsdWU9IiI+QWxsIGV2ZW50czwvb3B0aW9uPgogICAgICAgICAgICB7ZXZlbnRPcHRpb25zLm1hcCgodmFsdWUpID0+ICgKICAgICAgICAgICAgICA8b3B0aW9uIGtleT17dmFsdWV9IHZhbHVlPXt2YWx1ZX0+CiAgICAgICAgICAgICAgICB7aHVtYW5BdWRpdExhYmVsKHZhbHVlKX0KICAgICAgICAgICAgICA8L29wdGlvbj4KICAgICAgICAgICAgKSl9CiAgICAgICAgICA8L3NlbGVjdD4KCiAgICAgICAgICA8c2VsZWN0CiAgICAgICAgICAgIHZhbHVlPXthY3RvclR5cGV9CiAgICAgICAgICAgIG9uQ2hhbmdlPXsoZXZlbnQpID0+IHNldEFjdG9yVHlwZShldmVudC50YXJnZXQudmFsdWUpfQogICAgICAgICAgICBjbGFzc05hbWU9e2NvbnRyb2xDbGFzc30KICAgICAgICAgID4KICAgICAgICAgICAgPG9wdGlvbiB2YWx1ZT0iIj5BbGwgYWN0b3JzPC9vcHRpb24+CiAgICAgICAgICAgIDxvcHRpb24gdmFsdWU9InBsYXllciI+UGxheWVyPC9vcHRpb24+CiAgICAgICAgICAgIDxvcHRpb24gdmFsdWU9InN0YWZmIj5TdGFmZjwvb3B0aW9uPgogICAgICAgICAgICA8b3B0aW9uIHZhbHVlPSJzeXN0ZW0iPlN5c3RlbTwvb3B0aW9uPgogICAgICAgICAgPC9zZWxlY3Q+CgogICAgICAgICAgPHNlbGVjdAogICAgICAgICAgICB2YWx1ZT17c291cmNlfQogICAgICAgICAgICBvbkNoYW5nZT17KGV2ZW50KSA9PiBzZXRTb3VyY2UoZXZlbnQudGFyZ2V0LnZhbHVlKX0KICAgICAgICAgICAgY2xhc3NOYW1lPXtjb250cm9sQ2xhc3N9CiAgICAgICAgICA+CiAgICAgICAgICAgIDxvcHRpb24gdmFsdWU9IiI+QWxsIHNvdXJjZXM8L29wdGlvbj4KICAgICAgICAgICAge3NvdXJjZU9wdGlvbnMubWFwKCh2YWx1ZSkgPT4gKAogICAgICAgICAgICAgIDxvcHRpb24ga2V5PXt2YWx1ZX0gdmFsdWU9e3ZhbHVlfT4KICAgICAgICAgICAgICAgIHtodW1hbkF1ZGl0TGFiZWwodmFsdWUpfQogICAgICAgICAgICAgIDwvb3B0aW9uPgogICAgICAgICAgICApKX0KICAgICAgICAgIDwvc2VsZWN0PgoKICAgICAgICAgIDxkaXYgY2xhc3NOYW1lPSJncmlkIGdyaWQtY29scy0yIGdhcC0yIj4KICAgICAgICAgICAgPGlucHV0CiAgICAgICAgICAgICAgdHlwZT0iZGF0ZSIKICAgICAgICAgICAgICB2YWx1ZT17ZnJvbURhdGV9CiAgICAgICAgICAgICAgb25DaGFuZ2U9eyhldmVudCkgPT4gc2V0RnJvbURhdGUoZXZlbnQudGFyZ2V0LnZhbHVlKX0KICAgICAgICAgICAgICB0aXRsZT0iRnJvbSBkYXRlIgogICAgICAgICAgICAgIGNsYXNzTmFtZT17Y29udHJvbENsYXNzfQogICAgICAgICAgICAvPgogICAgICAgICAgICA8aW5wdXQKICAgICAgICAgICAgICB0eXBlPSJkYXRlIgogICAgICAgICAgICAgIHZhbHVlPXt0b0RhdGV9CiAgICAgICAgICAgICAgb25DaGFuZ2U9eyhldmVudCkgPT4gc2V0VG9EYXRlKGV2ZW50LnRhcmdldC52YWx1ZSl9CiAgICAgICAgICAgICAgdGl0bGU9IlRvIGRhdGUiCiAgICAgICAgICAgICAgY2xhc3NOYW1lPXtjb250cm9sQ2xhc3N9CiAgICAgICAgICAgIC8+CiAgICAgICAgICA8L2Rpdj4KCiAgICAgICAgICA8ZGl2IGNsYXNzTmFtZT0iZmxleCBpdGVtcy1jZW50ZXIganVzdGlmeS1iZXR3ZWVuIGdhcC0yIj4KICAgICAgICAgICAgPHAgY2xhc3NOYW1lPSJ0ZXh0LVs4cHhdIHVwcGVyY2FzZSB0cmFja2luZy1bMC4xMmVtXSB0ZXh0LVtyZ2IodmFyKC0tc2VwLWNvbG91ci03MTY2NTQpKV0iPgogICAgICAgICAgICAgIHtmaWx0ZXJlZFJvd3MubGVuZ3RofSAvIHtyb3dzLmxlbmd0aH0gZW50cmllcwogICAgICAgICAgICA8L3A+CiAgICAgICAgICAgIDxidXR0b24KICAgICAgICAgICAgICB0eXBlPSJidXR0b24iCiAgICAgICAgICAgICAgb25DbGljaz17cmVzZXRGaWx0ZXJzfQogICAgICAgICAgICAgIGRpc2FibGVkPXshaGFzRmlsdGVyc30KICAgICAgICAgICAgICBjbGFzc05hbWU9ImgtOSBib3JkZXIgYm9yZGVyLVtyZ2IodmFyKC0tc2VwLWNvbG91ci02MDQ4MmUpKV0vNTUgYmctW3JnYih2YXIoLS1zZXAtY29sb3VyLTE4MTEwZCkpXSBweC0zIHRleHQtWzhweF0gdXBwZXJjYXNlIHRyYWNraW5nLVswLjE0ZW1dIHRleHQtW3JnYih2YXIoLS1zZXAtY29sb3VyLWFlOWE3YikpXSBkaXNhYmxlZDpjdXJzb3Itbm90LWFsbG93ZWQgZGlzYWJsZWQ6b3BhY2l0eS00MCIKICAgICAgICAgICAgPgogICAgICAgICAgICAgIFJlc2V0CiAgICAgICAgICAgIDwvYnV0dG9uPgogICAgICAgICAgPC9kaXY+CiAgICAgICAgPC9kaXY+CgogICAgICAgIDxwIGNsYXNzTmFtZT0ibXQtMiB0ZXh0LVs4cHhdIHRleHQtW3JnYih2YXIoLS1zZXAtY29sb3VyLTc1Njk1OCkpXSI+CiAgICAgICAgICBGaWx0ZXJzIHVwZGF0ZSBpbW1lZGlhdGVseS4gTm8gcmVsb2FkIHJlcXVpcmVkLgogICAgICAgIDwvcD4KICAgICAgPC9kaXY+CgogICAgICB7ZmlsdGVyZWRSb3dzLmxlbmd0aCA9PT0gMCA/ICgKICAgICAgICA8cCBjbGFzc05hbWU9InB5LTYgdGV4dC1zbSB0ZXh0LVtyZ2IodmFyKC0tc2VwLWNvbG91ci04ZjgyNzEpKV0iPgogICAgICAgICAgTm8gQ2hhcmFjdGVyIExvZyBlbnRyaWVzIG1hdGNoIHRoZXNlIGZpbHRlcnMuCiAgICAgICAgPC9wPgogICAgICApIDogKAogICAgICAgIDxkaXYgY2xhc3NOYW1lPSJtdC00IHNwYWNlLXktMyI+CiAgICAgICAgICB7ZmlsdGVyZWRSb3dzLm1hcCgocm93KSA9PiAoCiAgICAgICAgICAgIDxDaGFyYWN0ZXJBdWRpdEVudHJ5IGtleT17cm93LmlkfSByb3c9e3Jvd30gLz4KICAgICAgICAgICkpfQogICAgICAgIDwvZGl2PgogICAgICApfQogICAgPC8+CiAgKTsKfQo='}
for relative, content64 in payloads.items():
    target = root / relative
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_bytes(base64.b64decode(content64))

text = admin_page.read_text(encoding="utf-8")

import_anchor = 'import Link from "next/link";\n\n'
imports = """import Link from "next/link";

import { CharacterAuditEntry } from "@/components/characters/character-audit-entry";
import {
  auditSummary,
  formatAuditDateTime,
  humanAuditLabel,
} from "@/lib/audit/character-audit-display";
import {
  enrichCharacterAuditItemNames,
} from "@/lib/audit/enrich-character-audit-items";

"""
if 'enrichCharacterAuditItemNames' not in text:
    if import_anchor not in text:
        raise SystemExit("Could not find Character Audit import anchor.")
    text = text.replace(import_anchor, imports, 1)

type_anchor = '  created_at: string;\n};'
type_new = '  created_at: string;\n  item_name?: string | null;\n};'
if 'item_name?: string | null;' not in text:
    if type_anchor not in text:
        raise SystemExit("Could not find AuditRow type anchor.")
    text = text.replace(type_anchor, type_new, 1)

text = re.sub(
    r'function formatDateTime\(value: string\) \{.*?\n\}\n\n(?=function characterName)',
    '',
    text,
    count=1,
    flags=re.S,
)

text = re.sub(
    r'function pretty\(value: unknown\) \{.*?\n\}\n\n(?=function startOfDay)',
    '',
    text,
    count=1,
    flags=re.S,
)

old_rows = """  const rawRows =
    allRows
      .filter(
        (row) =>
          !isExpertiseOnlyUpdate(
            row,
          ),
      )
      .map(
        scrubExpertise,
      );

  const needle = params.q?.trim().toLowerCase() ?? "";

  const rows = needle
    ? rawRows.filter((row) =>
"""
new_rows = """  const rawRows =
    allRows
      .filter(
        (row) =>
          !isExpertiseOnlyUpdate(
            row,
          ),
      )
      .map(
        scrubExpertise,
      );

  const enrichedRows =
    await enrichCharacterAuditItemNames(
      rawRows,
    );

  const needle = params.q?.trim().toLowerCase() ?? "";

  const rows = needle
    ? enrichedRows.filter((row) =>
"""
if 'const enrichedRows =' not in text:
    if old_rows not in text:
        raise SystemExit("Could not find Character Audit row-enrichment anchor.")
    text = text.replace(old_rows, new_rows, 1)

text = text.replace(
    '          row.source,\n          ...(row.changed_fields ?? []),',
    '          row.source,\n          row.item_name,\n          ...(row.changed_fields ?? []),',
    1,
)
text = text.replace('    : rawRows;', '    : enrichedRows;', 1)

start_literal = """              return (
                <article
                  key={row.id}
                  id={`character-audit-${row.id}`}
"""
# braces above are doubled because this script itself is an f-string; fix to actual source.
start_literal = start_literal.replace("{", "{").replace("}", "}")
# Simpler exact literal:
start_literal = '              return (\n                <article\n                  key={row.id}\n                  id={`character-audit-${row.id}`}\n'
start_literal = start_literal.replace('{row.id}','{row.id}')
# We'll locate by a safer short marker.
start = text.find('              return (\n                <article\n                  key={row.id}'.replace('{row.id}','{row.id}'))
if start == -1:
    start = text.find('              return (\n                <article\n                  key={row.id}'.replace('{','{').replace('}','}'))
# Actual braces are single in file:
if start == -1:
    start = text.find('              return (\n                <article\n                  key={row.id}'.replace('{row.id}','{row.id}'))
if start == -1:
    start = text.find('              return (\n                <article\n                  key=')
if start == -1:
    raise SystemExit("Could not find Character Audit entry render start.")

end_literal = '                </article>\n              );\n'
end = text.find(end_literal, start)
if end == -1:
    raise SystemExit("Could not find Character Audit entry render end.")
end += len(end_literal)

replacement = """              return (
                <div
                  key={row.id}
                  id={`character-audit-${row.id}`}
                  data-character-audit-id={row.id}
                  data-character-audit-character={characterLabel}
                  data-character-audit-event={humanAuditLabel(row.event_type)}
                  data-character-audit-actor={actorLabel}
                  data-character-audit-source={row.source}
                  data-character-audit-date={dateLabel}
                  data-character-audit-summary={summary}
                  className="scroll-mt-6"
                >
                  <CharacterAuditEntry
                    row={row}
                    characterLabel={characterLabel}
                  />
                </div>
              );
"""
text = text[:start] + replacement + text[end:]
text = text.replace(
    'const dateLabel = formatDateTime(row.created_at);',
    'const dateLabel = formatAuditDateTime(row.created_at);',
)
admin_page.write_text(text, encoding="utf-8")

route = api_route.read_text(encoding="utf-8")
route_import_anchor = """import {
  createClient,
} from "@/lib/supabase/server";
"""
route_import_new = """import {
  createClient,
} from "@/lib/supabase/server";
import {
  enrichCharacterAuditItemNames,
} from "@/lib/audit/enrich-character-audit-items";
"""
if 'enrichCharacterAuditItemNames' not in route:
    if route_import_anchor not in route:
        raise SystemExit("Could not find Character Audit API import anchor.")
    route = route.replace(route_import_anchor, route_import_new, 1)

raw_anchor = """  const rawRows =
    (data ?? []) as AuditRow[];

  const rows =
    rawRows
"""
raw_new = """  const rawRows =
    (data ?? []) as AuditRow[];

  const enrichedRows =
    await enrichCharacterAuditItemNames(
      rawRows,
    );

  const rows =
    enrichedRows
"""
if 'const enrichedRows =' not in route:
    if raw_anchor not in route:
        raise SystemExit("Could not find Character Audit API enrichment anchor.")
    route = route.replace(raw_anchor, raw_new, 1)

map_anchor = """        entity_id:
          row.entity_id,
        actor_type:
"""
map_new = """        entity_id:
          row.entity_id,
        operation:
          row.operation,
        item_name:
          row.item_name,
        actor_type:
"""
if 'item_name:\n          row.item_name' not in route:
    if map_anchor not in route:
        raise SystemExit("Could not find Character Audit API map anchor.")
    route = route.replace(map_anchor, map_new, 1)

api_route.write_text(route, encoding="utf-8")

print("Character Log refinement patch applied.")
print("Created/replaced shared display + enrichment modules.")
print("Updated /admin/character-audit and character-sheet LOG API.")
print("No LOG visibility or permission rules changed.")
print("Next: npm run build")
