from pathlib import Path
ROOT=Path.cwd()
if not (ROOT/'package.json').exists(): raise SystemExit('ERROR: Run from sepulchria-portal root.')

def replace_once(rel,old,new,label):
    p=ROOT/rel
    if not p.exists(): raise SystemExit(f'ERROR: Missing file: {rel}')
    text=p.read_text(encoding='utf-8')
    if new in text:
        print(f'SKIP: {label} already installed'); return
    if old not in text:
        raise SystemExit(f'ERROR: Expected code not found for {label} in {rel}. Send me this exact error; do not edit manually.')
    p.write_text(text.replace(old,new,1),encoding='utf-8')
    print(f'OK: {label}')

replace_once('app/(portal)/messages/actions.ts','    .eq("conversation_id", conversationId)\n    .eq("character_id", character.id);\n\n  if (error) throw new Error(error.message);\n  revalidatePath("/messages");\n}\n\nexport async function toggleArchive','    .eq("conversation_id", conversationId)\n    .eq("character_id", character.id)\n    .is("deleted_at", null);\n\n  if (error) throw new Error(error.message);\n  revalidatePath("/messages");\n}\n\nexport async function toggleArchive','Mark-read never revives/touches left memberships')
replace_once('app/(portal)/messages/actions.ts','    .update({\n      archived_at: archive ? new Date().toISOString() : null,\n      ...(archive ? {} : { deleted_at: null }),\n    })\n    .eq("conversation_id", conversationId)\n    .eq("character_id", character.id);','    .update({\n      archived_at: archive ? new Date().toISOString() : null,\n    })\n    .eq("conversation_id", conversationId)\n    .eq("character_id", character.id)\n    .is("deleted_at", null);','Archive cannot restore a left group membership')
replace_once('app/(portal)/messages/actions.ts','    const now =\n      new Date().toISOString();\n\n    const {\n      error: leaveError,\n    } = await supabase\n      .from(\n        "direct_conversation_participants",\n      )\n      .update({\n        deleted_at: now,\n        archived_at: now,\n        last_read_at: now,\n      })\n      .eq(\n        "conversation_id",\n        conversationId,\n      )\n      .eq(\n        "character_id",\n        character.id,\n      )\n      .is(\n        "deleted_at",\n        null,\n      );','    const {\n      error: leaveError,\n    } = await supabase.rpc(\n      "leave_group_conversation",\n      {\n        target_conversation_id:\n          conversationId,\n      },\n    );','Group leave uses authoritative database RPC')
replace_once('app/(portal)/messages/send-typed-message-action.ts','      .eq(\n        "character_id",\n        character.id,\n      )\n      .maybeSingle();','      .eq(\n        "character_id",\n        character.id,\n      )\n      .is(\n        "deleted_at",\n        null,\n      )\n      .maybeSingle();','Typed sender requires active membership')
replace_once('app/(portal)/messages/actions.ts','      .eq("conversation_id", conversationId)\n      .eq("character_id", character.id)\n      .maybeSingle();\n\n    if (participantError) return { ok: false, message: participantError.message };','      .eq("conversation_id", conversationId)\n      .eq("character_id", character.id)\n      .is("deleted_at", null)\n      .maybeSingle();\n\n    if (participantError) return { ok: false, message: participantError.message };','Legacy sender requires active membership')
replace_once('lib/portal/get-portal-context.ts','          .eq(\n            "character_id",\n            characterId,\n          )\n          .is("archived_at", null),','          .eq(\n            "character_id",\n            characterId,\n          )\n          .is("archived_at", null)\n          .is("deleted_at", null),','Portal header/sidebar unread count excludes left groups')
replace_once('components/messages/unread-message-badge.tsx','          .is(\n            "archived_at",\n            null,\n          );','          .is(\n            "archived_at",\n            null,\n          )\n          .is(\n            "deleted_at",\n            null,\n          );','Live unread badge excludes left groups')
replace_once('components/messages/unread-message-badge.tsx','  const pathname = usePathname();\n\n  const {\n    playPortalSound,','  const pathname = usePathname();\n\n  const currentConversationId =\n    pathname.match(\n      /^\\/messages\\/([^/]+)\\/?$/,\n    )?.[1] ?? null;\n\n  const {\n    playPortalSound,','Unread badge identifies currently open conversation')
replace_once('components/messages/unread-message-badge.tsx','        const rows =\n          (\n            memberships ??\n            []\n          ) as MembershipRow[];\n\n        const unreadCounts =','        const rows =\n          (\n            memberships ??\n            []\n          ) as MembershipRow[];\n\n        const countableRows =\n          currentConversationId\n            ? rows.filter(\n                (membership) =>\n                  membership.conversation_id !==\n                  currentConversationId,\n              )\n            : rows;\n\n        const unreadCounts =','Unread badge excludes open conversation from global total')
replace_once('components/messages/unread-message-badge.tsx','            rows.map(\n              async (\n                membership,','            countableRows.map(\n              async (\n                membership,','Unread badge counts filtered memberships')
replace_once('components/messages/unread-message-badge.tsx','      [],\n    );\n\n  const refreshCount =','      [currentConversationId],\n    );\n\n  const refreshCount =','Unread calculation tracks open conversation')
replace_once('app/(portal)/messages/[id]/components/ConversationRealtime.tsx','    let cancelled = false;\n\n    async function setup() {','    let cancelled = false;\n\n    function keepConversationRead() {\n      if (cancelled) {\n        return;\n      }\n\n      void markConversationRead(\n        conversationId,\n      );\n    }\n\n    async function setup() {','Open conversation defines persistent read sync')
replace_once('app/(portal)/messages/[id]/components/ConversationRealtime.tsx','      void markConversationRead(\n        conversationId,\n      );\n    }\n\n    void setup();\n\n    const channel =','      keepConversationRead();\n    }\n\n    void setup();\n\n    const handleFocus = () => {\n      keepConversationRead();\n    };\n\n    const handleVisibilityChange =\n      () => {\n        if (\n          document.visibilityState ===\n          "visible"\n        ) {\n          keepConversationRead();\n        }\n      };\n\n    window.addEventListener(\n      "focus",\n      handleFocus,\n    );\n\n    document.addEventListener(\n      "visibilitychange",\n      handleVisibilityChange,\n    );\n\n    const channel =','Open conversation resyncs read state on focus')
replace_once('app/(portal)/messages/[id]/components/ConversationRealtime.tsx','            void markConversationRead(\n              conversationId,\n            );\n\n            router.refresh();','            keepConversationRead();\n\n            router.refresh();\n\n            window.setTimeout(\n              keepConversationRead,\n              120,\n            );','Incoming open message stays read after refresh race')
replace_once('app/(portal)/messages/[id]/components/ConversationRealtime.tsx','    return () => {\n      cancelled = true;\n\n      void supabase.removeChannel(\n        channel,\n      );','    return () => {\n      cancelled = true;\n\n      window.removeEventListener(\n        "focus",\n        handleFocus,\n      );\n\n      document.removeEventListener(\n        "visibilitychange",\n        handleVisibilityChange,\n      );\n\n      void supabase.removeChannel(\n        channel,\n      );','Open conversation cleans read-state listeners')
replace_once('app/(portal)/messages/page.tsx','          .neq(\n            "character_id",\n            character.id,\n          )\n      : Promise.resolve({','          .neq(\n            "character_id",\n            character.id,\n          )\n          .is(\n            "deleted_at",\n            null,\n          )\n      : Promise.resolve({','Inbox group participant names omit leavers')

print()
print('SUCCESS: authoritative group leave + open-conversation unread fix installed.')
print('Now run: npm run build')