"use client";
import {useEffect,useMemo,useState} from "react";
export type ShapeCard=Record<string,any>&{id:string;name:string;description:string;level:number;school:string;word_of_power:string;movement:string;target_mode:string};
const ctl="w-full border border-[#59432c]/45 bg-[#100c09] px-3 py-2 text-[9px] text-[#cdb99a] outline-none focus:border-[#987344]";
const pretty=(v:any)=>v?String(v).replaceAll("_"," ").replace(/\b\w/g,(c:string)=>c.toUpperCase()):"—";
const signed=(n:number)=>n>0?`+${n}`:String(n);
function Box({label,value}:{label:string;value:string}){return <div className="border border-[#59432c]/30 bg-[#120e0b] px-2.5 py-2"><p className="text-[6px] uppercase tracking-[.13em] text-[#806a4c]">{label}</p><p className="mt-1 break-words text-[8px] leading-4 text-[#b8a382]">{value}</p></div>}
function mods(s:ShapeCard,p:"self"|"other"){const a=[["Mus",s[p+"_muscles_modifier"]],["Ref",s[p+"_reflexes_modifier"]],["Vig",s[p+"_vigour_modifier"]],["Bra",s[p+"_brains_modifier"]],["Shr",s[p+"_shrewd_modifier"]],["Pre",s[p+"_presence_modifier"]]];return a.filter(([,v])=>Number(v)!==0).map(([l,v])=>`${l} ${signed(Number(v))}`).join(" · ")||"None"}
function fx(s:ShapeCard,p:"self"|"other"){const a=[] as string[];if(s[p+"_damage_dice"])a.push(`Damage ${s[p+"_damage_dice"]}${s.damage_type?` ${s.damage_type}`:""}`);if(s[p+"_heal_dice"])a.push(`Heal ${s[p+"_heal_dice"]}`);if(s[p+"_max_hp_change"])a.push(`Max HP ${s[p+"_max_hp_change"]}`);const m=mods(s,p);if(m!=="None")a.push(m);if((s[p+"_conditions"]??[]).length)a.push(`Conditions: ${s[p+"_conditions"].join(", ")}`);return a.join(" · ")||"No mechanical effect"}
function req(s:ShapeCard){return [["Muscles",s.min_muscles],["Reflexes",s.min_reflexes],["Vigour",s.min_vigour],["Brains",s.min_brains],["Shrewd",s.min_shrewd],["Presence",s.min_presence]].filter(([,v])=>v).map(([l,v])=>`${l} ${v}`).join(" · ")||"None"}
export function ShapesCatalogue({shapes,characterMode=false}:{shapes:ShapeCard[];characterMode?:boolean}){
 const [q,setQ]=useState(""),[level,setLevel]=useState(""),[school,setSchool]=useState(""),[movement,setMovement]=useState(""),[target,setTarget]=useState("");
 const schools=useMemo(()=>Array.from(new Set(shapes.map(s=>s.school))).sort(),[shapes]);const moves=useMemo(()=>Array.from(new Set(shapes.map(s=>s.movement))).sort(),[shapes]);
 const filtered=useMemo(()=>shapes.filter(s=>(!q||`${s.name} ${s.word_of_power} ${s.description}`.toLowerCase().includes(q.toLowerCase()))&&(!level||String(s.level)===level)&&(!school||s.school===school)&&(!movement||s.movement===movement)&&(!target||s.target_mode===target)),[shapes,q,level,school,movement,target]);
 useEffect(()=>{const ids=filtered.map(s=>s.id);sessionStorage.setItem("sepulchria:shapes-visible-ids",JSON.stringify(ids));window.dispatchEvent(new CustomEvent("sepulchria:shapes-filter-change",{detail:{ids}}))},[filtered]);
 return <><section className="mt-4 border border-[#59432c]/45 bg-[#100c09] p-3"><div className="grid gap-2 xl:grid-cols-[1.4fr_repeat(4,1fr)_auto]">
 <input className={ctl} type="search" value={q} onChange={e=>setQ(e.target.value)} placeholder="Name, Word or description..."/>
 <select className={ctl} value={level} onChange={e=>setLevel(e.target.value)}><option value="">All Levels</option>{Array.from(new Set(shapes.map(s=>s.level))).sort((a,b)=>a-b).map(v=><option key={v} value={v}>Level {v}</option>)}</select>
 <select className={ctl} value={school} onChange={e=>setSchool(e.target.value)}><option value="">All Schools</option>{schools.map(v=><option key={v} value={v}>{pretty(v)}</option>)}</select>
 <select className={ctl} value={movement} onChange={e=>setMovement(e.target.value)}><option value="">All Movements</option>{moves.map(v=><option key={v} value={v}>{pretty(v)}</option>)}</select>
 <select className={ctl} value={target} onChange={e=>setTarget(e.target.value)}><option value="">All Targets</option><option value="self">Self</option><option value="other">Other</option><option value="either">Either</option><option value="written">Written / Fate</option></select>
 <button type="button" onClick={()=>{setQ("");setLevel("");setSchool("");setMovement("");setTarget("")}} className="border border-[#765937]/55 bg-[#21180f] px-4 py-2 text-[8px] uppercase text-[#c8aa7b]">Reset</button></div><p className="mt-2 text-right text-[7px] uppercase text-[#8a7558]">{filtered.length} / {shapes.length}</p></section>
 <section className="mt-3 space-y-2">{filtered.map(s=><article key={s.id} id={`shape-${s.id}`} className="scroll-mt-4 border border-[#59432c]/40 bg-[#100c09] px-4 py-3"><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="text-[7px] uppercase tracking-[.14em] text-[#8c704b]">Level {s.level} · {pretty(s.school)} · {s.word_of_power}</p><h2 className="mt-1 font-serif text-xl text-[#dec89f]">{s.name}</h2></div>{characterMode&&s.source?<span className="border border-[#60482e]/40 px-2 py-1 text-[6px] uppercase text-[#9b805c]">{pretty(s.source)}{s.level_override?" · Level Override":""}</span>:null}</div><p className="mt-2 whitespace-pre-line text-[10px] leading-5 text-[#9c8e7b]">{s.description||"No description."}</p>
 <div className="mt-3 grid grid-cols-2 gap-1.5 border-t border-[#59432c]/30 pt-3 md:grid-cols-3 xl:grid-cols-6">
 <Box label="Words" value={`${pretty(s.essence_word)} · ${pretty(s.action_word)} · ${pretty(s.law_word)}`}/><Box label="Casting" value={`${pretty(s.movement)} · ${s.requires_verbal?"Verbal":"No verbal"} · ${s.requires_movement?"Movement":"No movement"}`}/><Box label="Resolution" value={s.resolution_mode==="automatic"?"Automatic":`DC ${pretty(s.dc_attribute)} · ${(s.save_options??[]).map(pretty).join(", ")||"No saves"} · Save: ${pretty(s.save_success_damage)}`}/><Box label="Target / Duration" value={`${pretty(s.target_mode)} · ${pretty(s.target_scope)}${s.target_scope==="multiple"?` ≤ ${s.max_targets}`:""} · ${s.duration_unit==="until_dispelled"?"Until dispelled":`${s.duration_amount??"?"} ${s.duration_unit}`}`}/><Box label="Self" value={fx(s,"self")}/><Box label="Other" value={fx(s,"other")}/><Box label="Nature / Type" value={`${pretty(s.effect_nature)} · ${s.damage_type||"No damage type"}${s.is_dispel?" · Dispel":""}`}/><Box label="Price" value={pretty(s.price_key)}/><Box label="Requirements" value={req(s)}/></div></article>)}{!filtered.length?<p className="border border-[#59432c]/30 bg-[#100c09] p-4 text-[11px] text-[#8f8271]">No Shapes match these filters.</p>:null}</section></>
}