from pathlib import Path

ROOT = Path.cwd()
if not (ROOT / 'package.json').exists():
    raise SystemExit('ERROR: Run this patch from the root of sepulchria-portal.')

def replace_once(rel, old, new, label, all_occurrences=False):
    path = ROOT / rel
    if not path.exists():
        raise SystemExit(f'ERROR: Missing {rel}')
    text = path.read_text(encoding='utf-8')
    if old == new and new in text:
        print(f'SKIP: {label}')
        return
    if new in text:
        print(f'SKIP: {label} already installed')
        return
    if old not in text:
        raise SystemExit(f'ERROR: Expected code not found for {label} in {rel}. Send me this exact error.')
    text = text.replace(old, new) if all_occurrences else text.replace(old, new, 1)
    path.write_text(text, encoding='utf-8')
    print(f'OK: {label}')

replace_once('app/(portal)/game/components/RoomMessageList.tsx', '                        style={\n                          privateLocationTheme &&\n                          !isNaturalTwenty &&\n                          !isNaturalOne\n                            ? {\n                                color:\n                                  privateLocationTheme.systemColour,\n                              }\n                            : undefined\n                        }', '                        style={\n                          privateLocationTheme &&\n                          !isNaturalTwenty &&\n                          !isNaturalOne\n                            ? {\n                                color:\n                                  privateLocationTheme.systemColour,\n                              }\n                            : undefined\n                        }', 'critical symbol protection already present', False)
replace_once('app/(portal)/game/components/RoomMessageList.tsx', '                        style={\n                          privateLocationTheme\n                            ? {\n                                color:\n                                  privateLocationTheme.systemColour,\n                              }\n                            : undefined\n                        }\n                      >\n                        {formatRollText(', '                        style={\n                          privateLocationTheme &&\n                          !isNaturalTwenty &&\n                          !isNaturalOne\n                            ? {\n                                color:\n                                  privateLocationTheme.systemColour,\n                              }\n                            : undefined\n                        }\n                      >\n                        {formatRollText(', 'restore critical success/failure result colours', False)
replace_once('app/(portal)/game/export/route.ts', 'import { createClient } from "@/lib/supabase/server";', 'import { createClient } from "@/lib/supabase/server";\nimport {\n  getPrivateLocationAccess,\n} from "@/lib/private-locations/access";', 'export Private Location palette import', False)
replace_once('app/(portal)/game/export/route.ts', '  const room =\n    roomData as unknown as RoomRow;\n\n  const area =', '  const room =\n    roomData as unknown as RoomRow;\n\n  const privateAccess =\n    await getPrivateLocationAccess(\n      room.id,\n      character.id,\n    );\n\n  if (\n    privateAccess.isPrivate &&\n    !privateAccess.allowed\n  ) {\n    redirect("/game");\n  }\n\n  const privateTheme =\n    privateAccess.metadata;\n\n  const area =', 'export loads authorised Private Location palette', False)
replace_once('app/(portal)/game/export/route.ts', '      background: #090706;\n      color: #c9bba6;\n    }', '      background: #090706;\n      color: #c9bba6;\n\n      --chat-background: ${\n        privateTheme\n          ? escapeHtml(\n              privateTheme.backgroundColour,\n            )\n          : "#110d0a"\n      };\n\n      --speech-colour: ${\n        privateTheme\n          ? escapeHtml(\n              privateTheme.speechColour,\n            )\n          : "#cdbda7"\n      };\n\n      --action-colour: ${\n        privateTheme\n          ? escapeHtml(\n              privateTheme.actionColour,\n            )\n          : "#a78760"\n      };\n\n      --system-colour: ${\n        privateTheme\n          ? escapeHtml(\n              privateTheme.systemColour,\n            )\n          : "#aa9c87"\n      };\n\n      --whisper-background: ${\n        privateTheme\n          ? escapeHtml(\n              privateTheme.whisperBackgroundColour,\n            )\n          : "#241b2a"\n      };\n\n      --whisper-text: ${\n        privateTheme\n          ? escapeHtml(\n              privateTheme.whisperTextColour,\n            )\n          : "#bda5cb"\n      };\n\n      --offgame-background: ${\n        privateTheme\n          ? escapeHtml(\n              privateTheme.offgameBackgroundColour,\n            )\n          : "#182536"\n      };\n\n      --offgame-text: ${\n        privateTheme\n          ? escapeHtml(\n              privateTheme.offgameTextColour,\n            )\n          : "#a9c7e6"\n      };\n    }', 'export Private Location palette CSS variables', False)
replace_once('app/(portal)/game/export/route.ts', '      background:\n        rgba(\n          17,\n          13,\n          10,\n          0.97\n        );', '      background:\n        var(\n          --chat-background,\n          rgba(\n            17,\n            13,\n            10,\n            0.97\n          )\n        );', 'export chat background palette', False)
replace_once('app/(portal)/game/export/route.ts', '    .speech-text {\n      color: #cdbda7;\n    }\n\n    .action-text {\n      color: #a78760;\n\n      font-style: italic;\n    }', '    .speech-text {\n      color:\n        var(\n          --speech-colour,\n          #cdbda7\n        );\n    }\n\n    .action-text {\n      color:\n        var(\n          --action-colour,\n          #a78760\n        );\n\n      font-style: italic;\n    }', 'export speech/action palette', False)
replace_once('app/(portal)/game/export/route.ts', '      background:\n        linear-gradient(\n          90deg,\n          rgba(\n            62,\n            40,\n            75,\n            0.22\n          ),\n          rgba(\n            27,\n            20,\n            30,\n            0.12\n          ) 58%,\n          transparent\n        );', '      background:\n        var(\n          --whisper-background,\n          #241b2a\n        );', 'export whisper background palette', False)
replace_once('app/(portal)/game/export/route.ts', '    .whisper-label {\n      color: #bda5cb;', '    .whisper-label {\n      color:\n        var(\n          --whisper-text,\n          #bda5cb\n        );', 'export whisper label palette', False)
replace_once('app/(portal)/game/export/route.ts', '    /*\n     * OUT OF CHARACTER\n     */', '    .whisper-entry\n    .author-name,\n    .whisper-entry\n    .speech-text,\n    .whisper-entry\n    .action-text,\n    .whisper-entry\n    .role-body {\n      color:\n        var(\n          --whisper-text,\n          #bda5cb\n        );\n    }\n\n\n    /*\n     * OUT OF CHARACTER\n     */', 'export whisper message text palette', False)
replace_once('app/(portal)/game/export/route.ts', '      background:\n        linear-gradient(\n          90deg,\n          rgba(\n            33,\n            58,\n            83,\n            0.34\n          ),\n          rgba(\n            22,\n            34,\n            49,\n            0.20\n          ) 58%,\n          transparent\n        );', '      background:\n        var(\n          --offgame-background,\n          #182536\n        );', 'export Off-Game background palette', False)
replace_once('app/(portal)/game/export/route.ts', '    .ooc-label {\n      color: #a9c7e6;', '    .ooc-label {\n      color:\n        var(\n          --offgame-text,\n          #a9c7e6\n        );', 'export Off-Game label palette', False)
replace_once('app/(portal)/game/export/route.ts', '    /*\n     * ROLLS\n     */', '    .ooc-entry\n    .author-name,\n    .ooc-entry\n    .speech-text,\n    .ooc-entry\n    .action-text,\n    .ooc-entry\n    .role-body {\n      color:\n        var(\n          --offgame-text,\n          #a9c7e6\n        );\n    }\n\n\n    /*\n     * ROLLS\n     */', 'export Off-Game message text palette', False)
replace_once('app/(portal)/game/export/route.ts', '    .roll-symbol {\n      color: #b98849;', '    .roll-symbol {\n      color:\n        var(\n          --system-colour,\n          #b98849\n        );', 'export system symbol palette', False)
replace_once('app/(portal)/game/export/route.ts', '    .roll-author {\n      color: #cdb486;', '    .roll-author {\n      color:\n        var(\n          --system-colour,\n          #cdb486\n        );', 'export system author palette', False)
replace_once('app/(portal)/game/export/route.ts', '    .roll-result {\n      min-width: 0;\n\n      color: #aa9c87;', '    .roll-result {\n      min-width: 0;\n\n      color:\n        var(\n          --system-colour,\n          #aa9c87\n        );', 'export system result palette', False)
replace_once('app/(portal)/game/export/route.ts', '    .critical-success\n    .roll-symbol,\n    .critical-success\n    .roll-result {\n      color: #86d9a6;\n    }', '    .critical-success\n    .roll-symbol,\n    .critical-success\n    .roll-result {\n      color: #86d9a6 !important;\n    }', 'export critical-success override', False)
replace_once('app/(portal)/game/export/route.ts', '    .critical-failure\n    .roll-symbol,\n    .critical-failure\n    .roll-result {\n      color: #e99797;\n    }', '    .critical-failure\n    .roll-symbol,\n    .critical-failure\n    .roll-result {\n      color: #e99797 !important;\n    }', 'export critical-failure override', False)

print()
print('SUCCESS: Critical colours + exported Private Location palette fixed.')
print('Now run: npm run build')