export const CHAT_MAX_LENGTH = 1000;
export const CHAT_COOLDOWN_SECONDS = 3;
export const PRESENCE_ACTIVE_MINUTES = 5;
export const ROOM_ROLL_COOLDOWN_SECONDS = 3;
export const ROOM_HISTORY_HOURS = 6;
export const ROOM_INACTIVITY_RESET_HOURS = 5;
export const ROOM_HISTORY_BATCH_SIZE = 1000;

