"use client";
import {useActionState,useEffect,useMemo,useState} from "react";
import {createClient} from "@/lib/supabase/client";
import type {CharacterAttributes} from "@/types/game";
import {resolveIncomingShape,type WarpingActionState} from "../warping-actions";
const initial:WarpingActionState={ok:false,message:""};
const L:Record<string,string>={dodge:"Dodge — Reflexes",defend:"Defend — Vigour",resist_vigour:"Resist — Vigour",resist_shrewd:"Resist — Shrewd",resist_brains:"Resist — Brains",resist_presence:"Resist — Presence"};
const A:Record<string,keyof CharacterAttributes>={dodge:"reflexes",defend:"vigor",resist_vigour:"vigor",resist_shrewd:"shrewd",resist_brains:"brains",resist_presence:"presence_score"};
const sign=(n:number)=>n>=0?`+${n}`:String(n);
export function PendingShapeResponses({attributes}:{attributes:CharacterAttributes}){const db=useMemo(()=>createClient(),[]),[rows,setRows]=useState<any[]>([]),[state,action]=useActionState(resolveIncomingShape,initial);
useEffect(()=>{let live=true;async function load(){const me=await db.rpc("my_character_id");if(!live||!me.data)return;const q=await db.from("shape_cast_targets").select(`id,created_at,dispel_effect_id,cast:shape_casts!shape_cast_targets_cast_id_fkey(id,caster:characters!shape_casts_caster_character_id_fkey(id,display_name),shape:shapes!shape_casts_shape_id_fkey(id,name,word_of_power,level,school,description,save_options,dc_attribute,save_success_damage,is_dispel,resolution_mode))`).eq("target_character_id",me.data).eq("outcome","pending").order("created_at",{ascending:true});if(live)setRows((q.data??[]).filter((row:any)=>{const cast=Array.isArray(row.cast)?row.cast[0]:row.cast,caster=Array.isArray(cast?.caster)?cast.caster[0]:cast?.caster,s=Array.isArray(cast?.shape)?cast.shape[0]:cast?.shape;return s?.resolution_mode==="save"&&caster?.id!==me.data;}))}void load();const timer=window.setInterval(()=>void load(),2500);const ch=db.channel(`shape-target-${crypto.randomUUID()}`).on("postgres_changes",{event:"*",schema:"public",table:"shape_cast_targets"},()=>void load()).subscribe();return()=>{live=false;window.clearInterval(timer);void db.removeChannel(ch)}},[db,state.submittedAt]);
if(!rows.length)return null;return <div className="mb-2 space-y-2">{rows.map(row=>{const cast=Array.isArray(row.cast)?row.cast[0]:row.cast,caster=Array.isArray(cast?.caster)?cast.caster[0]:cast?.caster,s=Array.isArray(cast?.shape)?cast.shape[0]:cast?.shape;if(!s)return null;if(s.is_dispel&&!row.dispel_effect_id)return null;return <section key={row.id} className="border border-[rgb(var(--sep-colour-765937))] bg-[rgb(var(--sep-colour-20140c))] p-3"><p className="text-[7px] uppercase tracking-[0.18em] text-[rgb(var(--sep-colour-b88c55))]">Incoming Shape</p><p className="mt-1 font-serif text-base text-[rgb(var(--sep-colour-efd2a0))]">{caster?.display_name??"Someone"} — {s.name}</p><p className="mt-1 text-[9px] text-[rgb(var(--sep-colour-a18d6e))]">Level {s.level} · {s.school} · {s.word_of_power}</p><p className="mt-1 text-[10px] text-[rgb(var(--sep-colour-b6a58d))]">{s.description}</p><form action={action} className="mt-3 flex flex-wrap gap-2"><input type="hidden" name="shape_cast_target_id" value={row.id}/>{(s.save_options??[]).map((x:string)=><button key={x} type="submit" name="save_choice" value={x} className="border border-[rgb(var(--sep-colour-765937))] bg-[rgb(var(--sep-colour-2a1c11))] px-3 py-2 text-[8px] uppercase text-[rgb(var(--sep-colour-dfc18f))]">{L[x]??x} ({sign(Number(attributes[A[x]]??0))})</button>)}<button type="submit" name="save_choice" value="__do_nothing__" className="border border-[rgb(var(--sep-colour-765937))] bg-[rgb(var(--sep-colour-2a1c11))] px-3 py-2 text-[8px] uppercase text-[rgb(var(--sep-colour-dfc18f))]">Do nothing</button></form></section>})}{state.message?<p className={state.ok?"text-xs text-[rgb(var(--sep-colour-9bb58c))]":"text-xs text-[rgb(var(--sep-colour-d58d82))]"}>{state.message}</p>:null}</div>}
