from pathlib import Path

ROOT = Path.cwd()
PATCH = Path(__file__).resolve().parent

if not (ROOT / 'package.json').exists():
    raise SystemExit('ERROR: Run this patch from the sepulchria-portal root.')

def payload(name):
    return (PATCH / name).read_text(encoding='utf-8')

def write_file(rel, content):
    path = ROOT / rel
    path.parent.mkdir(parents=True, exist_ok=True)
    if path.exists() and path.read_text(encoding='utf-8') == content:
        print(f'SKIP: {rel} already current')
        return
    path.write_text(content, encoding='utf-8')
    print(f'OK: wrote {rel}')

def replace_once(rel, old, new, label):
    path = ROOT / rel
    if not path.exists():
        raise SystemExit(f'ERROR: Missing file: {rel}')
    text = path.read_text(encoding='utf-8')
    if new in text:
        print(f'SKIP: {label} already installed')
        return
    if old not in text:
        raise SystemExit(f'ERROR: Expected code not found for {label} in {rel}. Send me this exact error; do not edit manually.')
    path.write_text(text.replace(old, new, 1), encoding='utf-8')
    print(f'OK: {label}')

write_file('lib/forum/forum-notifications.ts', payload('forum-notifications.ts.payload'))
replace_once('app/(portal)/forum/actions.ts', 'import {\n  canCreateOrderTopic,', 'import {\n  notifyForumReplyAudience,\n} from "@/lib/forum/forum-notifications";\nimport {\n  canCreateOrderTopic,', 'Forum actions import automatic PM helper')
replace_once('app/(portal)/forum/actions.ts', 'type ForumTopicRecord = {\n  id: string;\n  section_id: string;\n  slug: string;\n  title: string;\n  is_locked: boolean;\n  deleted_at: string | null;\n};', 'type ForumTopicRecord = {\n  id: string;\n  section_id: string;\n  slug: string;\n  title: string;\n  author_character_id: string | null;\n  is_locked: boolean;\n  deleted_at: string | null;\n};', 'Forum topic record includes creator character')
replace_once('app/(portal)/forum/actions.ts', '        slug,\n        title,\n        is_locked,\n        deleted_at', '        slug,\n        title,\n        author_character_id,\n        is_locked,\n        deleted_at', 'Reply action loads topic creator character')
replace_once('app/(portal)/forum/actions.ts', '  revalidatePath(\n    `/forum/${finalSectionSlug}/${finalTopicSlug}`,\n  );\n\n  redirect(\n    `/forum/${finalSectionSlug}/${finalTopicSlug}#post-${createdPost.id}`,\n  );', '  revalidatePath(\n    `/forum/${finalSectionSlug}/${finalTopicSlug}`,\n  );\n\n  await notifyForumReplyAudience({\n    supabase,\n    actorCharacterId:\n      character!.id,\n    topicId: topic.id,\n    topicAuthorCharacterId:\n      topic.author_character_id,\n    topicTitle: topic.title,\n    href:\n      `/forum/${encodeURIComponent(\n        finalSectionSlug,\n      )}/${encodeURIComponent(\n        finalTopicSlug,\n      )}#post-${createdPost.id}`,\n  });\n\n  revalidatePath("/messages");\n\n  redirect(\n    `/forum/${finalSectionSlug}/${finalTopicSlug}#post-${createdPost.id}`,\n  );', 'Forum reply notifies creator and favourites')
replace_once('app/(portal)/forum/post-actions.ts', 'import { createClient } from "@/lib/supabase/server";', 'import { createClient } from "@/lib/supabase/server";\nimport {\n  resolveActorCharacterId,\n  sendForumNotification,\n} from "@/lib/forum/forum-notifications";', 'Forum post actions import notification helper')
replace_once('app/(portal)/forum/post-actions.ts', '  author_user_id: string | null;\n  body: string;', '  author_user_id: string | null;\n  author_character_id: string | null;\n  body: string;', 'Forum post record includes author character')
replace_once('app/(portal)/forum/post-actions.ts', '        author_user_id,\n        body,', '        author_user_id,\n        author_character_id,\n        body,', 'Post context loads author character')
replace_once('app/(portal)/forum/post-actions.ts', 'type ForumTopicRecord = {\n  id: string;\n  section_id: string;\n  slug: string;\n  author_user_id: string | null;', 'type ForumTopicRecord = {\n  id: string;\n  section_id: string;\n  slug: string;\n  title: string;\n  author_user_id: string | null;', 'Post edit topic context includes title')
replace_once('app/(portal)/forum/post-actions.ts', '        section_id,\n        slug,\n        author_user_id,', '        section_id,\n        slug,\n        title,\n        author_user_id,', 'Post edit loads topic title')
replace_once('app/(portal)/forum/post-actions.ts', '  revalidateForumPaths(\n    section.slug,\n    topic.slug,\n  );\n\n  redirect(\n    `/forum/${section.slug}/${topic.slug}#post-${post.id}`,\n  );', '  revalidateForumPaths(\n    section.slug,\n    topic.slug,\n  );\n\n  if (\n    !ownsPost &&\n    post.author_character_id\n  ) {\n    const actorCharacterId =\n      await resolveActorCharacterId(\n        supabase,\n        user.id,\n      );\n\n    if (actorCharacterId) {\n      await sendForumNotification({\n        supabase,\n        actorCharacterId,\n        recipientCharacterId:\n          post.author_character_id,\n        heading:\n          "Your forum content was edited",\n        message:\n          `Another user edited your post in “${topic.title}”.`,\n        href:\n          `/forum/${encodeURIComponent(\n            section.slug,\n          )}/${encodeURIComponent(\n            topic.slug,\n          )}#post-${post.id}`,\n        linkLabel:\n          "Open edited post",\n      });\n\n      revalidatePath(\n        "/messages",\n      );\n    }\n  }\n\n  redirect(\n    `/forum/${section.slug}/${topic.slug}#post-${post.id}`,\n  );', "Editing someone else's post sends automatic PM")
replace_once('app/(portal)/forum/post-moderation-actions.ts', 'import { createClient } from "@/lib/supabase/server";', 'import { createClient } from "@/lib/supabase/server";\nimport {\n  resolveActorCharacterId,\n  sendForumNotification,\n} from "@/lib/forum/forum-notifications";', 'Post moderation imports automatic PM helper')
replace_once('app/(portal)/forum/post-moderation-actions.ts', '  revalidatePostPages(\n    section.slug,\n    topic.slug,\n  );\n\n  return {\n    success: true,\n    message:\n      "The post has been removed.",\n  };', '  if (\n    post.author_character_id\n  ) {\n    const actorCharacterId =\n      await resolveActorCharacterId(\n        access.supabase,\n        access.user.id,\n      );\n\n    if (actorCharacterId) {\n      await sendForumNotification({\n        supabase:\n          access.supabase,\n        actorCharacterId,\n        recipientCharacterId:\n          post.author_character_id,\n        heading:\n          "Your forum post was moderated",\n        message:\n          reason\n            ? `Your post in “${topic.title}” was removed by staff. Reason: ${reason}`\n            : `Your post in “${topic.title}” was removed by staff.`,\n        href:\n          `/forum/${encodeURIComponent(\n            section.slug,\n          )}/${encodeURIComponent(\n            topic.slug,\n          )}`,\n        linkLabel:\n          "Open topic",\n      });\n\n      revalidatePath(\n        "/messages",\n      );\n    }\n  }\n\n  revalidatePostPages(\n    section.slug,\n    topic.slug,\n  );\n\n  return {\n    success: true,\n    message:\n      "The post has been removed.",\n  };', 'Deleted forum post automatically notifies author')
replace_once('app/(portal)/forum/post-moderation-actions.ts', '  revalidatePostPages(\n    section.slug,\n    topic.slug,\n  );\n\n  return {\n    success: true,\n    message:\n      "The post has been restored.",\n  };', '  if (\n    post.author_character_id\n  ) {\n    const actorCharacterId =\n      await resolveActorCharacterId(\n        access.supabase,\n        access.user.id,\n      );\n\n    if (actorCharacterId) {\n      await sendForumNotification({\n        supabase:\n          access.supabase,\n        actorCharacterId,\n        recipientCharacterId:\n          post.author_character_id,\n        heading:\n          "Your forum post was restored",\n        message:\n          reason\n            ? `Your post in “${topic.title}” was restored by staff. Note: ${reason}`\n            : `Your post in “${topic.title}” was restored by staff.`,\n        href:\n          `/forum/${encodeURIComponent(\n            section.slug,\n          )}/${encodeURIComponent(\n            topic.slug,\n          )}#post-${post.id}`,\n        linkLabel:\n          "Open restored post",\n      });\n\n      revalidatePath(\n        "/messages",\n      );\n    }\n  }\n\n  revalidatePostPages(\n    section.slug,\n    topic.slug,\n  );\n\n  return {\n    success: true,\n    message:\n      "The post has been restored.",\n  };', 'Restored forum post automatically notifies author')
replace_once('app/(portal)/forum/moderation-actions.ts', 'import { createClient } from "@/lib/supabase/server";', 'import { createClient } from "@/lib/supabase/server";\nimport {\n  resolveActorCharacterId,\n  sendForumNotification,\n} from "@/lib/forum/forum-notifications";', 'Topic moderation imports automatic PM helper')
replace_once('app/(portal)/forum/moderation-actions.ts', '  slug: string;\n  is_locked: boolean;', '  slug: string;\n  author_character_id: string | null;\n  is_locked: boolean;', 'Moderated topic record includes author character')
replace_once('app/(portal)/forum/moderation-actions.ts', '        title,\n        slug,\n        is_locked,', '        title,\n        slug,\n        author_character_id,\n        is_locked,', 'Topic moderation loads author character')
replace_once('app/(portal)/forum/moderation-actions.ts', 'function revalidateForumTopic(\n  sectionSlug: string,\n  topicSlug: string,\n) {\n  revalidatePath("/forum");\n  revalidatePath(\n    `/forum/${sectionSlug}`,\n  );\n  revalidatePath(\n    `/forum/${sectionSlug}/${topicSlug}`,\n  );\n}', 'function revalidateForumTopic(\n  sectionSlug: string,\n  topicSlug: string,\n) {\n  revalidatePath("/forum");\n  revalidatePath(\n    `/forum/${sectionSlug}`,\n  );\n  revalidatePath(\n    `/forum/${sectionSlug}/${topicSlug}`,\n  );\n}\n\nasync function notifyTopicAuthor({\n  supabase,\n  moderatorUserId,\n  topic,\n  heading,\n  message,\n  href,\n  linkLabel,\n}: {\n  supabase: Awaited<\n    ReturnType<typeof createClient>\n  >;\n  moderatorUserId: string;\n  topic: ForumTopicRecord;\n  heading: string;\n  message: string;\n  href: string;\n  linkLabel: string;\n}) {\n  if (\n    !topic.author_character_id\n  ) {\n    return;\n  }\n\n  const actorCharacterId =\n    await resolveActorCharacterId(\n      supabase,\n      moderatorUserId,\n    );\n\n  if (!actorCharacterId) {\n    return;\n  }\n\n  await sendForumNotification({\n    supabase,\n    actorCharacterId,\n    recipientCharacterId:\n      topic.author_character_id,\n    heading,\n    message,\n    href,\n    linkLabel,\n  });\n\n  revalidatePath("/messages");\n}', 'Topic moderation notification helper')
replace_once('app/(portal)/forum/moderation-actions.ts', '  revalidateForumTopic(\n    section.slug,\n    topic.slug,\n  );\n\n  return {\n    success: true,\n    message: nextLockedState', '  await notifyTopicAuthor({\n    supabase:\n      access.supabase,\n    moderatorUserId:\n      access.user.id,\n    topic,\n    heading:\n      nextLockedState\n        ? "Your forum topic was locked"\n        : "Your forum topic was unlocked",\n    message:\n      nextLockedState\n        ? `Staff locked “${topic.title}”.`\n        : `Staff unlocked “${topic.title}”.`,\n    href:\n      `/forum/${encodeURIComponent(\n        section.slug,\n      )}/${encodeURIComponent(\n        topic.slug,\n      )}`,\n    linkLabel:\n      "Open topic",\n  });\n\n  revalidateForumTopic(\n    section.slug,\n    topic.slug,\n  );\n\n  return {\n    success: true,\n    message: nextLockedState', 'Topic lock/unlock notifies author')
replace_once('app/(portal)/forum/moderation-actions.ts', '  revalidateForumTopic(\n    section.slug,\n    topic.slug,\n  );\n\n  return {\n    success: true,\n    message: nextPinnedState', '  await notifyTopicAuthor({\n    supabase:\n      access.supabase,\n    moderatorUserId:\n      access.user.id,\n    topic,\n    heading:\n      nextPinnedState\n        ? "Your forum topic was pinned"\n        : "Your forum topic was unpinned",\n    message:\n      nextPinnedState\n        ? `Staff pinned “${topic.title}”.`\n        : `Staff unpinned “${topic.title}”.`,\n    href:\n      `/forum/${encodeURIComponent(\n        section.slug,\n      )}/${encodeURIComponent(\n        topic.slug,\n      )}`,\n    linkLabel:\n      "Open topic",\n  });\n\n  revalidateForumTopic(\n    section.slug,\n    topic.slug,\n  );\n\n  return {\n    success: true,\n    message: nextPinnedState', 'Topic pin/unpin notifies author')
replace_once('app/(portal)/forum/moderation-actions.ts', '  revalidatePath("/forum");\n  revalidatePath(\n    `/forum/${currentSection.slug}`,\n  );\n  revalidatePath(\n    `/forum/${destinationSection.slug}`,\n  );', '  await notifyTopicAuthor({\n    supabase:\n      access.supabase,\n    moderatorUserId:\n      access.user.id,\n    topic,\n    heading:\n      "Your forum topic was moved",\n    message:\n      `Staff moved “${topic.title}” from ${currentSection.name} to ${destinationSection.name}.`,\n    href:\n      `/forum/${encodeURIComponent(\n        destinationSection.slug,\n      )}/${encodeURIComponent(\n        topic.slug,\n      )}`,\n    linkLabel:\n      "Open moved topic",\n  });\n\n  revalidatePath("/forum");\n  revalidatePath(\n    `/forum/${currentSection.slug}`,\n  );\n  revalidatePath(\n    `/forum/${destinationSection.slug}`,\n  );', 'Moved topic notifies author')
replace_once('app/(portal)/forum/moderation-actions.ts', '  revalidatePath("/forum");\n  revalidatePath(\n    `/forum/${section.slug}`,\n  );\n  revalidatePath(\n    "/admin/forum/topics",\n  );', '  await notifyTopicAuthor({\n    supabase:\n      access.supabase,\n    moderatorUserId:\n      access.user.id,\n    topic,\n    heading:\n      "Your forum topic was moderated",\n    message:\n      reason\n        ? `Staff removed “${topic.title}”. Reason: ${reason}`\n        : `Staff removed “${topic.title}”.`,\n    href:\n      `/forum/${encodeURIComponent(\n        section.slug,\n      )}`,\n    linkLabel:\n      "Open forum section",\n  });\n\n  revalidatePath("/forum");\n  revalidatePath(\n    `/forum/${section.slug}`,\n  );\n  revalidatePath(\n    "/admin/forum/topics",\n  );', 'Deleted topic notifies author')
replace_once('app/(portal)/forum/moderation-actions.ts', '  revalidateForumTopic(\n    section.slug,\n    topic.slug,\n  );\n\n  revalidatePath(\n    "/admin/forum/topics",\n  );', '  await notifyTopicAuthor({\n    supabase:\n      access.supabase,\n    moderatorUserId:\n      access.user.id,\n    topic,\n    heading:\n      "Your forum topic was restored",\n    message:\n      reason\n        ? `Staff restored “${topic.title}”. Note: ${reason}`\n        : `Staff restored “${topic.title}”.`,\n    href:\n      `/forum/${encodeURIComponent(\n        section.slug,\n      )}/${encodeURIComponent(\n        topic.slug,\n      )}`,\n    linkLabel:\n      "Open restored topic",\n  });\n\n  revalidateForumTopic(\n    section.slug,\n    topic.slug,\n  );\n\n  revalidatePath(\n    "/admin/forum/topics",\n  );', 'Restored topic notifies author')
replace_once('app/(portal)/forum/flag-actions.ts', '  associationName: string | null;\n};', '  associationName: string | null;\n  isFriend: boolean;\n};', 'Flag recipients expose Friend List membership')
replace_once('app/(portal)/forum/flag-actions.ts', '  const {\n    characters,\n    races,\n    associations,\n  } =\n    await getAccessibleCharacterRows(\n      sectionId,\n      senderData.id,\n    );\n\n  return characters.map(\n    (character) => ({', '  const {\n    characters,\n    races,\n    associations,\n  } =\n    await getAccessibleCharacterRows(\n      sectionId,\n      senderData.id,\n    );\n\n  const [\n    friendFeatureResult,\n    friendEntriesResult,\n  ] = await Promise.all([\n    supabase\n      .from(\n        "character_feature_entitlements",\n      )\n      .select("enabled")\n      .eq(\n        "character_id",\n        senderData.id,\n      )\n      .eq(\n        "feature_key",\n        "friend_list",\n      )\n      .maybeSingle(),\n    supabase\n      .from(\n        "character_friend_entries",\n      )\n      .select(\n        "target_character_id",\n      )\n      .eq(\n        "owner_character_id",\n        senderData.id,\n      ),\n  ]);\n\n  const friendIds =\n    friendFeatureResult.data\n      ?.enabled === true\n      ? new Set(\n          (\n            friendEntriesResult.data ??\n            []\n          ).map(\n            (row) =>\n              String(\n                row.target_character_id,\n              ),\n          ),\n        )\n      : new Set<string>();\n\n  return characters.map(\n    (character) => ({', 'Flag recipient loader resolves enabled Friend List')
replace_once('app/(portal)/forum/flag-actions.ts', '      associationName:\n        character.association_id\n          ? associations.get(\n              character.association_id,\n            ) ?? null\n          : null,\n    }),', '      associationName:\n        character.association_id\n          ? associations.get(\n              character.association_id,\n            ) ?? null\n          : null,\n      isFriend:\n        friendIds.has(\n          character.id,\n        ),\n    }),', 'Flag recipients mark friends')
replace_once('app/(portal)/forum/flag-actions.ts', '    const topicSlug = String(\n      formData.get("topicSlug") ?? "",\n    ).trim();\n\n    if (', '    const topicSlug = String(\n      formData.get("topicSlug") ?? "",\n    ).trim();\n\n    const customMessage =\n      String(\n        formData.get(\n          "customMessage",\n        ) ?? "",\n      )\n        .trim()\n        .slice(0, 1_000);\n\n    if (', 'Flag action reads custom note')
replace_once('app/(portal)/forum/flag-actions.ts', '    const messageBody =\n      `<p><strong>${safeSender}</strong> wants you to read this forum topic:</p>` +\n      `<p><strong>${safeTitle}</strong></p>` +\n      `<p><a href="${safePath}">Open topic →</a></p>`;', '    const safeCustomMessage =\n      customMessage\n        ? escapeHtml(\n            customMessage,\n          ).replaceAll(\n            "\\n",\n            "<br />",\n          )\n        : "";\n\n    const messageBody =\n      `<div data-forum-flag="true">` +\n      `<p><strong>Forum Flag for Reading</strong></p>` +\n      `<p><strong>${safeSender}</strong> wants you to read this forum topic:</p>` +\n      `<p><strong>${safeTitle}</strong></p>` +\n      (safeCustomMessage\n        ? `<p><em>Personal note:</em></p><blockquote>${safeCustomMessage}</blockquote>`\n        : "") +\n      `<p><a href="${safePath}">Open topic →</a></p>` +\n      `</div>`;', 'Flag PM includes optional custom note')
replace_once('components/forum/forum-topic-flag-button.tsx', '  const matchingCharacters =\n    useMemo(() => {', '  const friends =\n    useMemo(\n      () =>\n        characters\n          .filter(\n            (character) =>\n              character.isFriend,\n          )\n          .map(\n            (character) => ({\n              id: character.id,\n              name:\n                character.name,\n            }),\n          ),\n      [characters],\n    );\n\n  function selectAllFriends() {\n    setSelectedCharacters(\n      (current) =>\n        new Set([\n          ...current,\n          ...friends.map(\n            (friend) =>\n              friend.id,\n          ),\n        ]),\n    );\n  }\n\n  const matchingCharacters =\n    useMemo(() => {', 'Flag modal derives Friend List choices')
replace_once('components/forum/forum-topic-flag-button.tsx', '            <div className="space-y-5">\n              <SelectionGroup\n                title="Ancestries"', '            <div className="space-y-5">\n              {friends.length > 0 ? (\n                <section className="border border-[#59432c]/40 bg-[#0d0a08] p-3">\n                  <div className="mb-2 flex items-center justify-between gap-3">\n                    <h3 className="text-[8px] uppercase tracking-[0.2em] text-[#9b774b]">\n                      Friend List\n                    </h3>\n\n                    <button\n                      type="button"\n                      onClick={\n                        selectAllFriends\n                      }\n                      className="border border-[#765735] px-2.5 py-1.5 text-[8px] uppercase tracking-[0.13em] text-[#c4a578] hover:border-[#a47a45] hover:text-[#e3c79a]"\n                    >\n                      Select full Friend List\n                    </button>\n                  </div>\n\n                  <SelectionGroup\n                    title="Select individual friends"\n                    options={\n                      friends\n                    }\n                    selected={\n                      selectedCharacters\n                    }\n                    onToggle={(id) =>\n                      toggle(\n                        setSelectedCharacters,\n                        id,\n                      )\n                    }\n                  />\n                </section>\n              ) : null}\n\n              <SelectionGroup\n                title="Ancestries"', 'Flag modal includes Friend List selector and select-all')
replace_once('components/forum/forum-topic-flag-button.tsx', '          {state.message ? (\n            <p', '          <label className="mb-3 block">\n            <span className="mb-1.5 block text-[8px] uppercase tracking-[0.16em] text-[#9b774b]">\n              Personal message\n              <span className="ml-1 normal-case tracking-normal text-[#6f6254]">\n                (optional)\n              </span>\n            </span>\n\n            <textarea\n              name="customMessage"\n              maxLength={1000}\n              rows={3}\n              placeholder=\'Example: "Read this, I found Reply number 3 quite interesting."\'\n              className="w-full resize-y border border-[#59432c]/55 bg-[#0b0806] px-3 py-2.5 text-xs leading-5 text-[#d7c1a0] outline-none placeholder:text-[#62584b] focus:border-[#9a7445]"\n            />\n          </label>\n\n          {state.message ? (\n            <p', 'Flag modal adds custom message field')

print()
print('SUCCESS: Forum automatic PMs + Flag custom note installed.')
print('No SQL required.')
print('Now run: npm run build')